- src/ui/components/AppWrapper/AppWrapper.scss
- src/ui/components/AppWrapper/AppWrapper.tsx
Right now we depend on our DIDComm mediator and KERIA instance being online for the app to load, as well as the users internet connection. This is a quick message to give feedback to other users while we work on having an offline mode of the app.
> feat(ui): display connection error message connecting to KERIA, mediator

- src/core/agent/modules/signify/signifyApi.test.ts
- src/core/agent/modules/signify/signifyApi.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
Add rotation feature with AID of Keri
> feat(core): AID key rotation

- README.md
Fixed a broken link for the Testing Readme on the main Readme page.
> docs: fixed broken link for testing readme page

- src/locales/en/en.json
- src/ui/App.tsx
- src/ui/components/PageHeader/PageHeader.tsx
- src/ui/components/PageHeader/PageHeader.types.ts
- src/ui/components/layout/ResponsivePageLayout/ResponsivePageLayout.test.tsx
- src/ui/components/layout/ResponsivePageLayout/ResponsivePageLayout.tsx
- src/ui/components/layout/ResponsivePageLayout/ResponsivePageLayout.types.ts
- src/ui/components/layout/ScrollablePageLayout/ScrollablePageLayout.test.tsx
- src/ui/components/layout/ScrollablePageLayout/ScrollablePageLayout.tsx
- src/ui/components/layout/ScrollablePageLayout/ScrollablePageLayout.types.ts
- src/ui/globals/types.ts
- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/IncomingRequest/IncomingRequest.scss
- src/ui/pages/IncomingRequest/IncomingRequest.tsx
- src/ui/pages/Menu/Menu.tsx
- src/ui/pages/Settings/Settings.scss
- src/ui/pages/Settings/Settings.test.tsx
- src/ui/pages/Settings/Settings.tsx
- src/ui/pages/Settings/Settings.types.ts
- src/ui/pages/Settings/index.ts
In this PR I have added the Settings page (as a full size page) reachable from the gear icon in the Menu tab.
Nothing is clickable, yet.
---
> feat(ui): Settings screen

- src/ui/components/ArchivedCredentials/ArchivedCredentials.tsx
- src/ui/components/CardDetailsElements/CardDetails.scss
Commit I forgot to push in this PR: https://github.com/cardano-foundation/cf-identity-wallet/pull/342
> fix(UI)/archived credentials

- services/external/keria-config/cf-backer-oobis.json
- src/core/agent/agent.ts
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
Missing witness config from our deployed KERIA instance and proper bracketing in the agent.
> build: witness config

- src/core/agent/modules/signify/signifyApi.ts
- src/core/agent/modules/signify/signifyApi.types.ts
- src/core/agent/services/credentialService.ts
- src/store/reducers/stateCache/stateCache.types.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/pages/IncomingRequest/IncomingRequest.tsx
IDW must be able to handle an incoming request grant message from the tunnel and talk to the enterprise.
---
> feat: tunnel req handler

- src/core/agent/services/identifierService.ts
- src/ui/components/CardsStack/CardsStack.test.tsx
- src/ui/components/CardsStack/CardsStack.tsx
- src/ui/pages/Identifiers/Identifiers.test.tsx
Create an independent function to check for multi-sig complete
> feat: only open card details if multi-sig complete

- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/identifierService.types.ts
- src/store/reducers/identifiersCache/identifiersCache.test.ts
- src/ui/__fixtures__/filteredIdentifierFix.ts
- src/ui/__fixtures__/identifierFix.ts
- src/ui/components/CreateIdentifier/components/IdentifierStage0.tsx
Add `isPending` in `IdentifierShortDetails`
> feat: add isPending to IdentifierShortDetails

- src/core/agent/modules/signify/signifyApi.test.ts
- src/core/agent/modules/signify/signifyApi.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/ui/components/CreateIdentifier/components/IdentifierStage3.tsx
Add `threshold` parameter for `createMultisig`
> feat: threshold multi-sig

- src/locales/en/en.json
- src/ui/App.scss
- src/ui/__fixtures__/filteredIdentifierFix.ts
- src/ui/components/CardDetailsElements/CardDetails.scss
- src/ui/components/CardDetailsElements/CardDetailsBlock.tsx
- src/ui/components/CardDetailsElements/CardDetailsItem.tsx
- src/ui/components/CardsStack/CardsStack.scss
- src/ui/components/CardsStack/CardsStack.test.tsx
- src/ui/components/CardsStack/CardsStack.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.scss
- src/ui/components/CreateIdentifier/components/IdentifierStage0.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage3.tsx
- src/ui/components/IdentifierCardTemplate/IdentifierCardTemplate.scss
- src/ui/components/PageHeader/PageHeader.tsx
- src/ui/components/PageHeader/PageHeader.types.ts
- src/ui/components/layout/ScrollablePageLayout/ScrollablePageLayout.scss
- src/ui/components/layout/TabLayout/TabLayout.scss
- src/ui/components/layout/TabLayout/TabLayout.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.scss
- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
- src/ui/pages/Creds/Creds.scss
- src/ui/pages/IdentifierCardDetails/IdentifierCardDetails.scss
- src/ui/pages/IdentifierCardDetails/IdentifierCardDetails.tsx
- src/ui/pages/Identifiers/Identifiers.scss
- src/ui/pages/Identifiers/Identifiers.test.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
- src/ui/pages/Identifiers/components/IdentifiersList.test.tsx
- src/ui/pages/Identifiers/components/IdentifiersList.tsx
- src/ui/pages/Settings/Settings.scss
In this PR I am adding a "Pending Identifiers" section to the bottom of the Identity Screen.
When the threshold is set to 1, the identifier is accepted right away (so it's not in the "Pending" list).
When it's >= 2 it will go to the list of Pending Identifiers.
This is reflected also in the toast message, so in the first case it will say "The identifier has been created" while in the second case it will say "It has been requested".
I made a video of both cases and they are available below, along with screenshots of the pending items on iOS and Android.
**NOTE:**
While I was stuck waiting for core stuff to be ready I have been fixing other small stuff around the app to keep myself busy.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/119612231/50cb1486-95a4-4bee-9e2d-a44 …
> feat(ui): Multi-Sig feature - Pending Identifiers

- src/ui/components/ShareIdentifier/ShareIdentifier.test.tsx
- src/ui/components/ShareIdentifier/ShareIdentifier.tsx
Fix lack toast message when copy identifier
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/5a62d0fa-0369-44b6-8d2e-00e3af84ad16
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/d03eec68-d864-4956-a905-b862ba410313
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/1b465eaf-03dc-4653-8652-a8636d611534
[DTIS-702]: https://cardanofoundation.atlassian.net/browse/DTIS-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DTIS-702: Fix lack toast message when copy identifier

- src/locales/en/en.json
- src/ui/components/IdentifierCardInfoKey/IdentifierCardInfoKey.test.tsx
- src/ui/components/IdentifierCardInfoKey/IdentifierCardInfoKey.tsx
Remove controller field in identifier card info screen
---
[DTIS-706]: https://cardanofoundation.atlassian.net/browse/DTIS-706?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): remove controller field in identifier card info screen

- src/ui/components/Scanner/Scanner.scss
- src/ui/pages/FullPageScanner/FullPageScanner.scss
- src/ui/pages/FullPageScanner/FullPageScanner.tsx
- src/ui/pages/Scan/Scan.scss
Fix full page QR code position
---
[DTIS-515]: https://cardanofoundation.atlassian.net/browse/DTIS-515?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): fix full page QR code position

- src/ui/__fixtures__/shortCredsFix.ts
- src/ui/components/CardsStack/CardsStack.scss
- src/ui/components/CardsStack/CardsStack.test.tsx
- src/ui/components/CardsStack/CardsStack.tsx
- src/ui/components/CardsStack/CardsStack.types.ts
- src/ui/components/CredCardTemplate/CredCardTemplate.scss
- src/ui/components/CredCardTemplate/CredCardTemplate.test.tsx
- src/ui/components/CredCardTemplate/CredCardTemplate.tsx
- src/ui/components/CredCardTemplate/CredCardTemplate.types.ts
- src/ui/components/IdentifierCardTemplate/IdentifierCardTemplate.scss
- src/ui/components/IdentifierCardTemplate/IdentifierCardTemplate.tsx
- src/ui/components/IdentifierCardTemplate/IdentifierCardTemplate.types.ts
- src/ui/pages/CredCardDetails/CredCardDetail.scss
- src/ui/pages/CredCardDetails/CredCardDetails.tsx
- src/ui/pages/Creds/Creds.scss
- src/ui/pages/Creds/Creds.tsx
- src/ui/pages/IdentifierCardDetails/IdentifierCardDetails.scss
- src/ui/pages/IdentifierCardDetails/IdentifierCardDetails.tsx
- src/ui/pages/Identifiers/Identifiers.scss
- src/ui/pages/Identifiers/Identifiers.tsx
- src/ui/pages/Identifiers/Identifiers.type.ts
Improve transition effect when clicking on identifier cards and credential cards
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/7a51f96c-9d38-43d8-9642-147841fbfa43
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/822c76bf-82da-4de5-b43d-5ab9755d9f71
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/25e07f3f-f82c-42a6-8bd2-be7e7d40c34d
[DTIS-703]: https://cardanofoundation.atlassian.net/browse/DTIS-703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): improve transition effect when clicking on cards

- src/core/agent/services/signifyNotificationService.ts
There was some last minute bugs with that pagination PR that got merged but this resolves them.
> fix: signify notification pagination fixes

- README.md
- src/ui/App.test.tsx
- src/ui/App.tsx
- src/ui/components/CardDetailsElements/CardDetailsAttributes.tsx
- src/ui/components/CardsStack/CardsStack.tsx
- src/ui/components/CredCardTemplate/CredCardTemplate.scss
- src/ui/components/CredCardTemplate/CredCardTemplate.tsx
- src/ui/components/CredCardTemplate/CredCardTemplate.types.ts
- src/ui/components/IdentifierCardTemplate/IdentifierCardTemplate.scss
- src/ui/components/IdentifierCardTemplate/IdentifierCardTemplate.tsx
- src/ui/components/IdentifierCardTemplate/IdentifierCardTemplate.types.ts
- src/ui/components/MobileHeaderPreview/MobileHeaderPreview.scss
- src/ui/components/MobileHeaderPreview/MobileHeaderPreview.tsx
- src/ui/components/MobileHeaderPreview/index.ts
- src/ui/pages/CredCardDetails/components/CredContent.test.tsx
- src/ui/pages/Identifiers/Identifiers.scss
- src/ui/styles/colors.scss
- src/ui/styles/smartphoneLayout.scss
- Adjustments to the mobile preview (only web preview). 
- Fix card animation lag on preview mode.
- Fix some failed unit tests
I captured screen on browser and emulators to confirm:
- Preview mobile header only working on preview mode.
- After I fixed bug about card animation, it work well on other environments.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/a090528b-0a5d-4a76-88f5-0293758b7be0
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/2efcc7d1-e407-4e52-a5ed-48ab99504271
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/1b850ee3-1e4d-436b-8cd9-7bb7323ac6a5
[DTIS-704]: https://cardanofoundation.atlassian.net/browse/DTIS-704?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …
> feat(ui): Adjustments to the mobile preview

- src/core/agent/services/credentialService.test.ts
- src/core/agent/services/credentialService.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/signifyNotificationService.test.ts
- src/core/agent/services/signifyNotificationService.ts
- src/ui/App.test.tsx
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/pages/IncomingRequest/IncomingRequest.tsx
Ability to read notifications later
[DTIS-717]: https://cardanofoundation.atlassian.net/browse/DTIS-717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(core): dismiss notifications

- src/locales/en/en.json
- src/ui/components/CardsStack/CardsStack.tsx
- src/ui/components/CredCardTemplate/CredCardTemplate.scss
- src/ui/components/CredCardTemplate/CredCardTemplate.test.tsx
- src/ui/components/CredCardTemplate/CredCardTemplate.tsx
- src/ui/components/CredCardTemplate/CredCardTemplate.types.ts
- src/ui/components/IdentifierCardTemplate/IdentifierCardTemplate.tsx
- src/ui/components/IdentifierCardTemplate/IdentifierCardTemplate.types.ts
- src/ui/pages/CredCardDetails/CredCardDetails.tsx
- src/ui/pages/Creds/Creds.scss
- src/ui/pages/Creds/Creds.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
In this PR I am fixing a bug that would see the credential cards having more vertical space between them and as a result being cut off at the bottom.
The main bug was caused by a `top: 30px` inline custom style that was introduced initially when these cards were created (a year ago) and it wasn't removed after our latest refactoring last week. 
Due to some discrepancies in the code, the stack of cards was working well in the Identifiers tab but it was showing the bug in the Credentials tab. Based on that, after fixing the main bug I took this as an opportunity to review the code used in both pages and after carefully considering and discarding the idea of a possible refactoring where we could be using one single component for both pages (discarded because of too many custom props and …
> bugfix(ui): Last Credential Cut Off in Credentials Screen

- src/ui/components/navigation/TabsMenu/TabsMenu.tsx
This PR fixed the error about cannot re-access identifier list page.
About ionic tab button, It alway change `href` attribute to url of tab or tab child that displayed. Ex: tab button of Identifier tab: 
- If displayed view is Identifier tab =>  `href` attribute value is `/tabs/identifiers`
- If displayed view is Identifier card detail => `href` attribute value is `/tabs/identifiers/:id`
(You can see it in DOM or read docs)
And beside that we are storing navigate history in redux. And use it to back button of tab layout. (Identifier card detail is using it).
We push tab url to nav history store when enter tab by `useIonViewDidEnter` hook.
As I describe in this ticket: https://github.com/cardano-foundation/cf-identity-wallet/pull/399 
Ionic cannot destroy component when we navigate from …
> fix(ui): fix cannot re-access identifier list page

- src/ui/components/VerifyPasscode/VerifyPasscode.scss
- src/ui/components/VerifyPasscode/VerifyPasscode.test.tsx
- src/ui/components/VerifyPasscode/VerifyPasscode.tsx
Add cancel button for verify passcode modal.
---
[DTIS-776]: https://cardanofoundation.atlassian.net/browse/DTIS-776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): add cancel button for verify passcode modal

- src/ui/components/PasswordValidation/PasswordValidation.tsx
Fix create password screen auto scroll to top when input password hint value. Reason because we are using nested component in `PasswordValidation` (`ValidationItem`). 
When `PasswordValidation` re-render (because page re-render) => `ValidationItem` will be redefine => all instance `ValidationItem` will be destroy and create new (it should be updated instead destroy and create new)=> Maybe It make height of `PasswordValidation` change in few milliseconds and viewport scroll to top. 
Nested components is bad practice and I think we should avoid it in future.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/f3aa2d6c-c7f0-4e83-bf05-d010f3dc0770
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/55a53a11-476a-4ab6-9f9d-ce4291165a9c …
> fix(ui): fix create password screen auto scroll to top when input password hint value

- src/locales/en/en.json
- src/ui/components/CreateIdentifier/CreateIdentifier.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.types.ts
- src/ui/components/CreateIdentifier/components/IdentifierStage1.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1BodyInit.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1BodyResume.tsx
In this PR we are adding the possibility for the user to resume the process of creating a Multi-Sig.
According to the [design on Figma](https://www.figma.com/file/XN6K76yt13zxCUHPh1Egr8/Identity-wallet?node-id=7164%3A27172&mode=dev), resuming the Multi-Sig will show the user a slightly different version of the sharing screen. When they access that screen for the first time (`IdentifierStage1`), the will see some text, the QR code, some more text and a green scan button. When they access the same page the second time by clicking on the "For multiple signers" list in the identifiers screen, they will skip `IdentifierStage0` and go directly to `IdentifierStage1` where they will see, in addition to what mentioned before, a different shape for the green scan button saying "Scan QR code", …
> feat(ui): Status of Multi-Sig via Identity Screen

- src/ui/components/Alert/Alert.tsx
- src/ui/components/CredentialCardTemplate/CredentialCardTemplate.test.tsx
- src/ui/components/VerifyPasscode/VerifyPasscode.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/CredentialDetails/CredentialDetails.test.tsx
- src/ui/pages/GenerateSeedPhrase/GenerateSeedPhrase.test.tsx
This PR update new skip unit tests for CredCardTemplate, CredCardDetails, GenerateSeedPhras, ConnectionDetails and CredContent.
All unit tests that mention in this ticket has been updated. Beside that I also update skipped unit test that I see on test file except test case has issue about trigger event on `IonModal`.  
---
[DTIS-766]: https://cardanofoundation.atlassian.net/browse/DTIS-766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(test): update skip unit tests

- src/ui/components/ConnectionOptions/ConnectionOptions.test.tsx
- src/ui/components/ConnectionOptions/ConnectionOptions.tsx
- src/ui/pages/Connections/Connections.tsx
Standardise connection options modal
---
[DTIS-401]: https://cardanofoundation.atlassian.net/browse/DTIS-401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): standardise connection options modal

- src/locales/en/en.json
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/ConnectModal/ConnectModal.tsx
- src/ui/components/OptionsModal/OptionsModal.scss
- src/ui/components/OptionsModal/OptionsModal.tsx
- src/ui/components/OptionsModal/OptionsModal.types.ts
- src/ui/components/ShareQR/MoreOptions.tsx
- src/ui/components/ShareQR/ShareQR.scss
- src/ui/components/ShareQR/ShareQR.test.tsx
- src/ui/components/ShareQR/ShareQR.tsx
- src/ui/pages/Connections/Connections.tsx
Refactor share QR modal
Beside that, I also refactor add connection modal, fix an issue about open add connection modal when connection list is empty, fix verify password when delete identifier, cred,...
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/fce31900-c6bd-4bb3-a76d-2c3c5e10dd3c
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/0e1aadac-9158-4c3e-ae9d-9b8ba73752a7
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/6edfeb1d-956f-4428-943e-06c93da83301
[DTIS-404]: https://cardanofoundation.atlassian.net/browse/DTIS-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): standardise share QR modal

- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
- src/ui/pages/ConnectionDetails/components/ConnectionNotes/ConnectionNotes.tsx
- src/ui/pages/ConnectionDetails/components/EditConnectionsModal.scss
- src/ui/pages/ConnectionDetails/components/EditConnectionsModal.test.tsx
- src/ui/pages/ConnectionDetails/components/EditConnectionsModal.tsx
Standardise edit connection modal
---
[DTIS-421]: https://cardanofoundation.atlassian.net/browse/DTIS-421?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): standardise edit connection modal

- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
> test(ui): uncomment AppWrapper tests after Aries removal

- src/locales/en/en.json
- src/routes/backRoute/backRoute.test.ts
- src/routes/nextRoute/nextRoute.test.ts
- src/store/reducers/identifiersCache/identifiersCache.test.ts
- src/store/reducers/identifiersCache/identifiersCache.ts
- src/store/reducers/identifiersCache/identifiersCache.types.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.types.ts
- src/ui/components/CreateIdentifier/components/IdentifierStage0.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1BodyInit.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1BodyResume.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage2.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage4.tsx
- src/ui/components/CreateIdentifier/components/IdentifierThemeSelector.test.tsx
- src/ui/components/Scanner/Scanner.tsx
In this PR I am making sure the initiator can manage and select/deselect the connections they scanned during a multi sig. Both the initiator and the receiver (after the first scan) will make use of the full page scanner, which is calling `getMultisigLinkedContacts` to check if the connection they scanned is part of their current multi sig group and send that info to Redux, so that the other components in the app can make use of that information. This is because for now the URL has some of the details but we need to adjust the core function to return the ID, therefore we will review this again in the future in order to limit the number of calls to the DB.
**NOTES:**
- Unit tests and tests on emulators will be conducted in the next and final ticket of the story as [mentioned …
> feat(ui): Multi sig connections

- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
Remove internal mock test from multisig service
> test(core): remove internal mock from test multiSig service

- src/core/agent/records/identifierMetadataRecord.ts
- src/core/agent/services/identifierService.ts
Filter out “member” identifiers from the list of identifiers given to the UI - and this should be done using tags.
> feat(core): hide member identifiers

- src/ui/App.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/pages/LoadingPage/LoadingPage.scss
- src/ui/pages/LockPage/LockPage.tsx
Functionality has been extracted to check when to show the login page and when to show the load page into App.tsx.
Also after loading in AppWrapper we make sure that we update redux correctly with the initialisation to true.
> fix: loading page

- src/core/storage/ionicStorage/ionicStorage.test.ts
- src/core/storage/ionicStorage/ionicStorage.ts
- src/core/storage/sqliteStorage/migrations/version-0.0.1.ts
- src/core/storage/sqliteStorage/sqliteStorage.test.ts
- src/core/storage/sqliteStorage/sqliteStorage.ts
- src/core/storage/sqliteStorage/utils.ts
> feat(core): Find by undefined tag queries

- src/core/agent/services/connectionService.ts
[Please include a summary of the changes and a brief description about this PR
](https://github.com/jorgenavben/identity-wallet-credential-issuance-web-interface/pull/9)
> feat(core): remove OOBI auto-resolve hack with test credential server

- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
Filter all connections with groupId undefined
> feat(core): Filter all connections with groupId undefined

- docker-compose.yaml
- keria-oobi-config.json
- src/core/agent/services/identifierService.ts
Add witness demo docker-compose for local development
> build: Add witness in docker-compose

- src/core/agent/services/multiSigService.ts
set isPending to false if the multisig threshold is 1
> feat: set isPending to false if joining threshold 1 multisig

- src/core/agent/records/credentialMetadataRecord.test.ts
- src/core/agent/records/credentialMetadataRecord.ts
- src/core/agent/records/credentialMetadataRecord.types.ts
- src/core/agent/records/credentialStorage.test.ts
- src/core/agent/services/credentialService.test.ts
- src/core/agent/services/credentialService.ts
- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/ipexCommunicationService.types.ts
change connectionId is a mandatory field in the credential record
> feat(core): Link connectionId to ACDC

- src/locales/en/en.json
- src/routes/paths.ts
- src/ui/components/navigation/TabsMenu/TabsMenu.tsx
- src/ui/pages/Chat/Chat.test.tsx
- src/ui/pages/Chat/Chat.tsx
---
[DTIS-916]: https://cardanofoundation.atlassian.net/browse/DTIS-916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Update Nav Bar with Notifications (UI)

- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
- src/ui/components/CreateIdentifier/components/IdentifierStage4.tsx
Update for creating a multisig with more than 2 participants
> fix: multisig with more than 2 participants

- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
Make the @OnlineOnly annotations all in place.
> feat: add @OnlineOnly decorator to required functions

- README.md
> docs(readme): replace feature tables with list

- src/core/agent/agent.types.ts
Remove legacy connection detail items
> refactor(core): Remove legacy connection detail items

- src/locales/en/en.json
- src/routes/backRoute/backRoute.test.ts
- src/routes/backRoute/backRoute.ts
- src/routes/index.tsx
- src/routes/nextRoute/nextRoute.test.ts
- src/routes/nextRoute/nextRoute.ts
- src/routes/paths.ts
- src/store/index.ts
- src/store/reducers/ssiAgent/index.ts
- src/store/reducers/ssiAgent/ssiAgent.test.ts
- src/store/reducers/ssiAgent/ssiAgent.ts
- src/store/reducers/ssiAgent/ssiAgent.types.ts
- src/store/reducers/stateCache/stateCache.test.ts
- src/store/reducers/stateCache/stateCache.ts
- src/store/reducers/stateCache/stateCache.types.ts
- src/ui/App.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/CustomInput/CustomInput.tsx
- src/ui/components/CustomInput/CustomInput.types.ts
- src/ui/components/Scanner/Scanner.tsx
- src/ui/globals/types.ts
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.scss
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.test.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.types.ts
- src/ui/pages/CreateSSIAgent/index.ts
- src/ui/utils/urlChecker.test.ts
- src/ui/utils/urlChecker.ts
Implement UI for SSI agent page
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/69558dfa-6096-443b-a7fa-2306a2058440
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/b1660dd2-878a-43c0-a37a-ea1955b8efc4
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/a7ee35de-ebc7-4e72-b1ed-1f983fba1962
[DTIS-897]: https://cardanofoundation.atlassian.net/browse/DTIS-897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): SSI Agent Page

- src/ui/components/Spinner/Spinner.scss
- src/ui/components/Spinner/Spinner.tsx
- src/ui/components/Spinner/Spinner.type.ts
- src/ui/components/Spinner/index.ts
- src/ui/pages/SidePage/components/IncomingRequest/components/SignRequest.tsx
Add a spinner and blur while signing
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/4f13ccea-784f-4b30-adfb-e4d76c4db513
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/251f63e8-8af0-4133-938a-93313ba2d51d
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/58cc463b-164d-45c9-b009-2bbd9f0e6349
[DTIS-951]: https://cardanofoundation.atlassian.net/browse/DTIS-951?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Add a spinner and blur while signing

- src/core/agent/agent.ts
- src/core/agent/agent.types.ts
- src/core/agent/records/operationPendingRecord.type.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
- src/core/agent/services/signifyNotificationService.ts
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage0.test.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage4.test.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage4.tsx
- src/ui/pages/SidePage/components/IncomingRequest/components/MultiSigRequest.tsx
After accepting or initiating a multi-sig, the long running operation should be tracked in the background
> feat(core): long running operation tracker for multi sig

- src/locales/en/en.json
- src/ui/components/CardDetails/CardDetailsAttributes/CardDetailsAttributes.tsx
- src/ui/components/CardDetails/CardDetailsAttributes/CardDetailsAttributes.types.ts
- src/ui/components/CardDetails/CardDetailsAttributes/CardDetailsNestedAttributes.tsx
- src/ui/components/layout/ScrollablePageLayout/ScrollablePageLayout.tsx
- src/ui/components/layout/ScrollablePageLayout/ScrollablePageLayout.types.ts
- src/ui/pages/SidePage/components/IncomingRequest/components/SignRequest.scss
- src/ui/pages/SidePage/components/IncomingRequest/components/SignRequest.tsx
CSS tweaks for Cardano Connect sign modal
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/9ddb3519-7b11-4ceb-b504-04fe0e6d1253
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/d53a8643-dfbb-49e1-8c71-5b1f881d72c6
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/6c23f76c-255a-4a6d-b993-11ead03bb808
[DTIS-954]: https://cardanofoundation.atlassian.net/browse/DTIS-954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): CSS tweaks for Cardano Connect sign modal

- services/credential-issuance-server/src/agent.ts
- services/credential-issuance-server/src/apis/credential.api.ts
- services/credential-issuance-server/src/modules/signify/signifyApi.ts
Update cred server: requestDisclosure receives dynamic attributes fields
> feat(cred-serv): requestDisclosure receives dynamic attributes fields

- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/core/cardano/walletConnect/identityWalletConnect.test.ts
- src/core/cardano/walletConnect/identityWalletConnect.ts
- src/core/cardano/walletConnect/peerConnection.test.ts
- src/core/cardano/walletConnect/peerConnection.ts
- src/core/cardano/walletConnect/peerConnection.types.ts
Adjust experimental API to be KERI specific
> refactor: adjust experimental api to be keri specific

- services/credential-issuance-server/src/agent.ts
- services/credential-issuance-server/src/apis/credential.api.ts
- services/credential-issuance-server/src/modules/signify/signifyApi.ts
Dynamic lei when issuance credential
> feat: dynamic attributes for all credential types

- src/core/agent/agent.ts
Recovery by existing agent in the core
> feat(core): recover existing KERIA agent

- src/core/agent/services/identifier.types.ts
- src/ui/__fixtures__/identifierFix.ts
- src/ui/pages/IdentifierDetails/components/IdentifierContent.tsx
Ensure sequence numbers are not converted to integers throughout the app
> fix: hex identifier sn

- src/core/agent/agent.types.ts
- src/routes/backRoute/backRoute.test.ts
- src/routes/nextRoute/nextRoute.test.ts
- src/store/reducers/identifierViewTypeCache/identifierViewTypeCache.test.ts
- src/store/reducers/identifierViewTypeCache/identifierViewTypeCache.ts
- src/store/reducers/identifierViewTypeCache/identifierViewTypeCache.types.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/CardSlider/CardSlider.scss
- src/ui/components/CardSlider/CardSlider.test.tsx
- src/ui/components/CardSlider/CardSlider.tsx
- src/ui/components/CardSlider/CardSlider.types.ts
- src/ui/components/CardSlider/index.ts
- src/ui/components/Slides/Slides.scss
- src/ui/pages/Identifiers/Identifiers.tsx
Slider for Favourite Identifiers
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/6665a617-6cb4-4180-a9e2-f12af4303823
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/eef61c34-d4ae-4911-9667-b45ea26975ad
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/92617c9c-712d-47ec-88ce-93c5926e0913
[DTIS-676]: https://cardanofoundation.atlassian.net/browse/DTIS-676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Slider for Favourite Identifiers

- src/core/agent/agent.types.ts
- src/core/agent/records/notificationRecord.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/signifyNotificationService.ts
I changed the return type of `getAllNotifications`
- [] Added new Unit/Component testing (if relevant).
> feat(core): change getAllNotifications return type

- src/core/agent/services/ipexCommunicationService.ts
>  fix(core): filter matching credentials correctly from ipex apply

- src/core/agent/services/multiSigService.ts
- src/ui/components/CardsStack/CardsStack.test.tsx
- src/ui/components/SwitchCardView/SwitchCardView.types.ts
- src/ui/pages/Identifiers/Identifiers.test.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
- Remove checkMultisigComplete from the core as it’s no longer needed
- Remove the pending click check from the UI
[DTIS-974]: https://cardanofoundation.atlassian.net/browse/DTIS-974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(core): remove checkMultisigComplete

- src/core/agent/agent.types.ts
- src/core/agent/records/notificationRecord.ts
- src/core/agent/services/credentialService.ts
- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/signifyNotificationService.ts
- src/ui/pages/SidePage/components/IncomingRequest/IncomingRequest.test.tsx
- src/ui/pages/SidePage/components/IncomingRequest/components/RequestComponent.test.tsx
Update `KeriaNotification` interface
> update(core): change KeriaNotification interface

- src/ui/components/CreateIdentifier/components/IdentifierStage1.test.tsx
- src/ui/pages/CredentialDetails/CredentialDetails.test.tsx
- src/ui/pages/CredentialDetails/CredentialDetails.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.test.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.test.tsx
- src/ui/pages/Menu/components/Settings/Settings.scss
- src/ui/pages/Menu/components/Settings/Settings.tsx
- src/ui/pages/VerifySeedPhrase/VerifySeedPhrase.test.tsx
Prevent add identifier to favourite list when page details aren’t fully loaded
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/c09689db-6308-4b86-a89a-fd6ce2dd380a
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/e96778ac-6bcf-4947-a33d-e8a16b226fda
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/cd375052-2b7a-4036-90e2-90749ab86bd4
[DTIS-992]: https://cardanofoundation.atlassian.net/browse/DTIS-992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): fix favourite identifier broken

- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
- src/core/agent/services/signifyNotificationService.test.ts
- src/core/agent/services/signifyNotificationService.ts
- src/core/agent/services/utils.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
catch error at some endpoints that throw a 404 response
> fix: catch if signify throws errors

- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/pages/SidePage/SidePage.test.tsx
- src/ui/pages/SidePage/components/IncomingRequest/IncomingRequest.test.tsx
Rewrite UT for `IncomingRequest` and `SidePage` and fix an issue about save identifier favourite index (this issue not change layout style of identifier, therefore I only capture evidence on browser)
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/ac24f2e9-08be-42e3-88df-4867ee33da0d
[DTIS-1004]: https://cardanofoundation.atlassian.net/browse/DTIS-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): UI: Rewrite unit tests for SidePage

- src/routes/backRoute/backRoute.ts
- src/routes/nextRoute/nextRoute.ts
- src/ui/components/Scanner/Scanner.tsx
- src/ui/globals/types.ts
- src/ui/pages/Connections/Connections.test.tsx
- src/ui/pages/Connections/Connections.tsx
- src/ui/pages/Scan/Scan.test.tsx
- src/ui/pages/Scan/Scan.tsx
Update scan tab to make this tab redirect to correct page after scan data
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/3a3cfa4a-6c14-48f6-b79a-4d2e2d345241
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/e671e477-5733-468c-b382-86d70f4d3b52
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/4d2be5c0-46b5-4df0-a11c-82ad4d4127ac
[DTIS-845]: https://cardanofoundation.atlassian.net/browse/DTIS-845?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): UI: Refactor routes

- src/core/agent/services/ipexCommunicationService.ts
Dynamically resolve schemas of incoming credentials
---
> feat(core): dynamically resolve schemas of incoming credentials

- src/core/agent/services/signifyNotificationService.test.ts
- src/core/agent/services/signifyNotificationService.ts
- src/ui/App.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
Pause KERIA poll when logged out
> feat: pause KERIA poll when logged out

- src/ui/App.scss
- src/ui/components/Alert/Alert.tsx
- src/ui/components/Alert/Alert.types.ts
- src/ui/components/CreatePasscodeModule/CreatePasscodeModule.tsx
- src/ui/components/CreatePasscodeModule/CreatePasscodeModule.types.ts
- src/ui/components/ForgotAuthInfo/ForgotAuthInfo.tsx
- src/ui/components/ForgotAuthInfo/ForgotAuthInfo.types.ts
- src/ui/components/RecoverySeedPhraseModule/RecoverySeedPhraseModule.tsx
- src/ui/components/RecoverySeedPhraseModule/RecoverySeedPhraseModule.types.ts
- src/ui/components/SetUserName/SetUserName.tsx
- src/ui/pages/LockPage/LockPage.scss
- src/ui/pages/LockPage/LockPage.tsx
- src/ui/pages/Onboarding/Onboarding.scss
- src/ui/pages/SetPasscode/SetPasscode.scss
- src/ui/pages/VerifySeedPhrase/VerifySeedPhrase.scss
Fix input cursor caret display wrong position on set user name modal. This issue only occur on IOS (or maybe only occur on emulator). I think the reason of issue is modal animation and now I'm disabling animation of set user name modal on IOS.
Beside that I also fix an issue about `Lock Page` display under alert. 
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/defa37a2-3281-4c7f-87eb-df167a066766
`Lock Page` should be hidden all content of current page. 
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/3a21b235-00b9-4911-9c25-16a62340708e
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/202896d0-186d-4751-8626-22c5e2f6f7ae
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/5f6c1a25-ebfb- …
> fix(ui): UI::Username modal broken in iPhone SE 1st gen

- src/core/agent/services/signifyNotificationService.test.ts
- src/core/agent/services/signifyNotificationService.ts
Mark a notification as unread (core)
> feat(core): Mark a notification as unread

- .github/workflows/e2e_mobile_tests.yaml
Init file for new workflow to be able to test it.
> dtis-546 e2e ci new workflow file

- .github/workflows/docker-builds.yaml
- .github/workflows/gh-vercel-branch-deploys.yaml
- .github/workflows/gh-vercel-pr-deploys.yaml
- src/core/agent/services/connectionService.ts
End of sprint 14 - most commits were merged last week though so this PR does not contain much.
> Merge from develop to main

- src/core/agent/services/signifyNotificationService.ts
If a notification record exists by ID, continue
> fix(core): continue if a notification exists

- src/locales/en/en.json
- src/ui/globals/types.ts
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential.tsx
Add toast message after share credential
---
https://github.com/user-attachments/assets/26b0cdc3-aaa0-4c0c-9a19-012914706a61
https://github.com/user-attachments/assets/21830315-9912-4bf8-b162-687434e14691
[DTIS-1062]: https://cardanofoundation.atlassian.net/browse/DTIS-1062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): UI::Credential Request:Add toast message

- src/core/agent/agent.ts
- src/core/agent/agent.types.ts
- src/core/agent/records/operationPendingRecord.ts
- src/core/agent/records/operationPendingRecord.type.ts
- src/core/agent/services/credentialService.test.ts
- src/core/agent/services/credentialService.ts
- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/signifyNotificationService.ts
Long running operation tracker for credentials
> feat(core): long running operation tracker for credentials

- .github/workflows/docker-builds.yaml
- services/credential-server-ui/src/constants/index.ts
- services/credential-server/src/agent.ts
- services/credential-server/src/modules/signify/signifyApi.ts
- services/credential-server/src/utils/schemas/schemaAcdc.ts
- src/core/agent/services/ipexCommunicationService.ts
This PR replaces the credential used in the IIW demos with a new one for the Rare EVO event.
> feat(cred-serv): new Rare EVO cred replacing old IWW cred

- services/credential-server/src/agent.ts
- services/credential-server/src/apis/credential.api.ts
- services/credential-server/src/modules/signify/signifyApi.ts
- services/credential-server/src/routes.ts
- src/core/agent/services/credentialService.test.ts
- src/core/agent/services/credentialService.ts
- src/core/agent/services/signifyNotificationService.test.ts
- src/core/agent/services/signifyNotificationService.ts
> feat(core): revoke credentials

- src/ui/components/PasswordModule/PasswordModule.test.tsx
- src/ui/components/PasswordValidation/PasswordValidation.tsx
- src/ui/pages/CreatePassword/CreatePassword.test.tsx
- src/ui/pages/Menu/components/Settings/components/ManagePassword/ManagePassword.test.tsx
- src/ui/pages/Menu/components/Settings/components/ManagePassword/ManagePassword.tsx
Unit tests coverage for create password page
[DTIS-121]: https://cardanofoundation.atlassian.net/browse/DTIS-121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Unit tests coverage for create password page

- package-lock.json
- package.json
- src/locales/en/en.json
- src/ui/globals/constants.ts
- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/Settings/Settings.tsx
- src/ui/pages/Menu/components/Settings/Settings.types.ts
Update Documentation & Discord links
---
https://github.com/user-attachments/assets/2b577c3d-3805-4187-971b-2da816f81dcc
https://github.com/user-attachments/assets/1184f797-fbaf-49c8-9166-5cfc53dbed26
https://github.com/user-attachments/assets/d0255d96-6e1f-41af-b3e0-543e34d45b7b
[DTIS-1093]: https://cardanofoundation.atlassian.net/browse/DTIS-1093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Update Documentation & Discord links

- src/locales/en/en.json
- src/ui/pages/Menu/Menu.tsx
- src/ui/pages/Menu/Menu.types.ts
- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/Settings/Settings.tsx
- src/ui/pages/Menu/components/Settings/components/ManagePassword/ManagePassword.test.tsx
- src/ui/pages/Menu/components/Settings/components/TermAndPrivacy/TermAndPrivacy.test.tsx
- src/ui/pages/Menu/components/Settings/components/TermAndPrivacy/TermAndPrivacy.tsx
- src/ui/pages/Menu/components/Settings/components/TermAndPrivacy/index.ts
Add `Terms and Conditions` and `Privacy Policy` to 
---
https://github.com/user-attachments/assets/785dc951-fbbc-43dc-9650-71a6d094e136
https://github.com/user-attachments/assets/7fe1aece-820e-499f-89e4-8e9ee38baa44
https://github.com/user-attachments/assets/df4a9cd0-0d9d-439a-a4e0-5d1a302caa8e
[DTIS-1002]: https://cardanofoundation.atlassian.net/browse/DTIS-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): View Terms & Conditions / Privacy Policy

- src/locales/en/en.json
- src/ui/App.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.scss
- src/ui/components/CreateIdentifier/components/IdentifierStage2.tsx
- src/ui/pages/Connections/Connections.scss
- src/ui/pages/Connections/Connections.tsx
> feat(ui): Remove search bar feature

- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
- src/core/agent/services/signifyNotificationService.ts
- src/ui/components/Scanner/Scanner.tsx
Fix pending connection not being saved if the OOBI doesn't resolve
> fix(core): pending connection not being saved

- src/core/agent/agent.ts
- src/locales/en/en.json
- src/ui/components/SeedPhraseModule/SeedPhraseModule.tsx
- src/ui/components/SeedPhraseModule/SeedPhraseModule.types.ts
- src/ui/pages/Menu/Menu.tsx
- src/ui/pages/Menu/Menu.types.ts
- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/Settings/Settings.tsx
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/ConfirmModal.tsx
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/RecoverySeedPhrase.scss
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/RecoverySeedPhrase.test.tsx
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/RecoverySeedPhrase.tsx
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/RecoverySeedPhrase.types.ts
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/index.ts
- src/ui/pages/Menu/components/SubMenu/SubMenu.scss
- src/ui/pages/Menu/components/SubMenu/SubMenu.tsx
- src/ui/pages/Menu/components/SubMenu/SubMenu.types.ts
Update the Settings page to reflect the new design and enable the recovery phrase generation functionality to improve user experience and security.
---
https://github.com/user-attachments/assets/f6c72399-5d50-4a03-8bae-f16a8478f594
https://github.com/user-attachments/assets/bfb8e14a-30fa-42d0-a60c-90e846b1168b
https://github.com/user-attachments/assets/d144844b-bcaa-4b53-ba5b-21408aa32820
[DTIS-1091]: https://cardanofoundation.atlassian.net/browse/DTIS-1091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): recovery phrase

- src/locales/en/en.json
- src/ui/components/Scanner/Scanner.test.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/globals/types.ts
Implement basic validation for the Merkaat ID input in the Cardano Connect > Paste Merkaat ID option to ensure only valid input lengths are allowed to proceed, partially preventing some potential errors.
---
Not changing anything in the UI so just uploading video taken from the browser.
https://github.com/user-attachments/assets/48f5c5a9-15e1-409a-9bc6-a4ace02b509c
https://github.com/user-attachments/assets/2247bef4-2eba-4d96-a764-5e3718e4f36a
> fix(ui): Cardano connect functionality add basic validation

- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
Fixing error when trying to delete a connection.
---
https://github.com/user-attachments/assets/1e9745ff-11c6-46c7-8cd2-7a8cc126a7e9
> fix(ui): error when deleting a connection

- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/Settings/components/ChangePin/ChangePin.test.tsx
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/RecoverySeedPhrase.scss
Improve UT coverage
---
[DTIS-1151]: https://cardanofoundation.atlassian.net/browse/DTIS-1151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ut): Check and finalize UT coverage

- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
update getConnectionShortDetails to get the connection status by pending field
> fix(core): return correct pending status for connections

- src/ui/components/Alert/Alert.tsx
- src/ui/components/Alert/Alert.types.ts
- src/ui/components/PasswordModule/PasswordModule.tsx
- src/ui/components/VerifyPassword/VerifyPassword.tsx
Fix password reset alert redirecting on dismissal
---
https://github.com/user-attachments/assets/fbe6f210-6811-477d-afe5-2d153d1580ec
https://github.com/user-attachments/assets/79fc3360-a1af-428c-8423-bf3837ba5bbe
https://github.com/user-attachments/assets/fce2233f-ae68-47a2-b889-69e350a151ba
[DTIS-1147]: https://cardanofoundation.atlassian.net/browse/DTIS-1147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Password reset alert redirecting on dismissal

- src/locales/en/en.json
- src/routes/backRoute/backRoute.test.ts
- src/routes/nextRoute/nextRoute.test.ts
- src/store/reducers/notificationsCache/notificationsCache.test.ts
- src/store/reducers/stateCache/stateCache.test.ts
- src/store/reducers/stateCache/stateCache.ts
- src/store/reducers/stateCache/stateCache.types.ts
- src/ui/App.test.tsx
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/MaxLoginAttemptAlert/MaxLoginAttemptAlert.scss
- src/ui/components/MaxLoginAttemptAlert/MaxLoginAttemptAlert.test.tsx
- src/ui/components/MaxLoginAttemptAlert/MaxLoginAttemptAlert.tsx
- src/ui/components/MaxLoginAttemptAlert/MaxLoginAttemptAlert.types.ts
- src/ui/components/MaxLoginAttemptAlert/hooks/loginAttemptHook.ts
- src/ui/components/MaxLoginAttemptAlert/index.ts
- src/ui/pages/LockPage/LockPage.test.tsx
- src/ui/pages/LockPage/LockPage.tsx
Create Max Login Attempts for IDW with PIN
---
https://github.com/user-attachments/assets/c86fb365-6027-421a-8212-84ae528d1326
[DTIS-1183]: https://cardanofoundation.atlassian.net/browse/DTIS-1183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Max Login Attempts for IDW with PIN

- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/signifyNotificationService.test.ts
Add test coverage for the long running operations in the signify notification service
> test(core): long running operations tests

- src/ui/pages/Menu/components/ConfirmConnectModal/ConfirmConnectModal.scss
- src/ui/pages/SidePage/SidePage.test.tsx
- src/ui/pages/SidePage/SidePage.tsx
- src/ui/pages/SidePage/components/IncomingRequest/IncomingRequest.tsx
- src/ui/pages/SidePage/components/WalletConnect/WalletConnect.tsx
Fix signing page not appear after connect external wallet.
---
https://github.com/user-attachments/assets/8c0e5097-2206-4b76-937f-3ddff74f23a9
[DTIS-1189]: https://cardanofoundation.atlassian.net/browse/DTIS-1189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): CIP45 - Connect with wallet. Signing page does not appear

- src/ui/components/IdentifierOptions/IdentifierOptions.test.tsx
- src/ui/components/IdentifierOptions/IdentifierOptions.tsx
- src/ui/components/IdentifierOptions/IdentifierOptions.types.ts
- src/ui/components/ShareConnection/ShareConnection.scss
- src/ui/components/ShareConnection/ShareConnection.test.tsx
- src/ui/components/ShareConnection/ShareConnection.tsx
- src/ui/components/ShareConnection/ShareConnection.types.ts
- src/ui/pages/Connections/Connections.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.test.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.tsx
- src/ui/pages/IdentifierDetails/components/IdentifierContent.test.tsx
Replacing wrong sharing information.
This PR doesn't include any changes to the current UI.
---
> feat(ui): Share option in identifier options should share the connection and not identifier

- src/ui/pages/ConnectionDetails/components/ConnectionHistoryEvent.tsx
> fix: wrong ConnectionHistoryType that was breaking unit tests

- src/core/agent/agent.ts
> fix(core): correctly strip padding from mnemonic

- src/core/agent/agent.ts
> feat(core): bootAndConnect should not call connect if boot returns 404

- src/locales/en/en.json
- src/ui/components/CardsStack/CardsStack.test.tsx
- src/ui/components/CloudError/CloudError.scss
- src/ui/components/CloudError/CloudError.tsx
- src/ui/components/CloudError/CloudError.types.ts
- src/ui/components/CloudError/index.ts
- src/ui/components/PageHeader/PageHeader.scss
- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
- src/ui/pages/CredentialDetails/CredentialDetails.test.tsx
- src/ui/pages/CredentialDetails/CredentialDetails.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.test.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.tsx
- src/ui/pages/Identifiers/Identifiers.test.tsx
Capturing and showing an error message when some information is missing from the cloud (Identifier/Credential/Connection).
Note:
We are using a specific error for showing the error message on Identifiers and Connections and return in the console any other errors, while for Credentials this error is not ready in the core yet so for now we're will just capture any any error and will integrate this later when the error for missing info in the cloud for Credentials will be ready.
---
https://github.com/user-attachments/assets/ad5f9501-544d-4335-b89c-2aa39452c6cf
https://github.com/user-attachments/assets/67e50eb1-7b9b-4001-afc8-e80b27a4d56a
> feat(ui): Error messages when information is missing from the cloud

- Earthfile
Just bumping keria source to https://github.com/WebOfTrust/keria.git#cfc55d4de3948663e01a8f55c994112453efc17b
> chore(Earthfile): update keria docker image source

- src/core/agent/agent.types.ts
- src/core/agent/services/signifyNotificationService.test.ts
- src/core/agent/services/signifyNotificationService.ts
Create processOperation function
> refactor(core): create processOperation function

- src/core/agent/records/ipexMessageStorage.test.ts
- src/core/agent/records/ipexMessageStorage.ts
- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
Delete IPEX history items when deleting connection
> feat(core): delete connection ipex histories when delete a connection

- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCrendential.test.tsx
Fix animation is cut short for receiving a credential
---
https://github.com/user-attachments/assets/4b49968d-b857-47b7-b0da-ae88ffd7d60f
[DTIS-1233]: https://cardanofoundation.atlassian.net/browse/DTIS-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Animation glitching

- .gitignore
- docker-compose.yaml
- services/credential-server-ui/src/App.tsx
- services/credential-server-ui/src/components/GetQRButton.tsx
- services/credential-server-ui/src/components/inputOOBI/GetInputButton.tsx
- services/credential-server-ui/src/config.ts
- services/credential-server-ui/src/pages/ConnectionPage.tsx
- services/credential-server-ui/src/pages/CredentialPage.tsx
- services/credential-server-ui/src/pages/RequestCredential.tsx
- services/credential-server/package-lock.json
- services/credential-server/package.json
- services/credential-server/src/agent.ts
- services/credential-server/src/apis/contact.api.ts
- services/credential-server/src/apis/credential.api.ts
- services/credential-server/src/apis/invitation.api.ts
- services/credential-server/src/apis/oobi.api.ts
- services/credential-server/src/apis/ping.api.ts
- services/credential-server/src/config.ts
- services/credential-server/src/modules/signify/signifyApi.ts
- services/credential-server/src/routes.ts
- services/credential-server/src/server.ts
- I added A global catch for unexpected errors 
- Change the way we use the bran
- Added a list to manage connections
> feat(cred-server): manage connections && support server longevity

- src/ui/App.test.tsx
- src/ui/App.tsx
> fix(ui): show app offline only after onboarding

- src/locales/en/en.json
- src/ui/pages/Menu/Menu.test.tsx
- src/ui/pages/Menu/Menu.tsx
- src/ui/pages/Menu/Menu.types.ts
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.tsx
- src/ui/pages/Menu/components/Profile/Profile.scss
- src/ui/pages/Menu/components/Profile/Profile.test.tsx
- src/ui/pages/Menu/components/Profile/Profile.tsx
- src/ui/pages/Menu/components/Profile/Profile.types.ts
- src/ui/pages/Menu/components/Profile/index.ts
- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/SubMenu/SubMenu.scss
- src/ui/pages/Menu/components/SubMenu/SubMenu.tsx
- src/ui/pages/Menu/components/SubMenu/SubMenu.types.ts
Adding an option in the Menu/Profile giving the user the possibility to edit their own username.
---
https://github.com/user-attachments/assets/766836ed-c891-41bb-bdb5-fdb9455d0489
https://github.com/user-attachments/assets/693016e0-fc6b-456b-9ccb-4e9f111d6703
> feat(ui): Edit username from profile in main menu

- src/core/agent/agent.types.ts
- src/store/reducers/stateCache/stateCache.ts
- src/store/reducers/stateCache/stateCache.types.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/components/Scanner/Scanner.types.ts
- src/ui/components/Scanner/hook/useCameraDirection.ts
- src/ui/components/layout/TabLayout/TabLayout.tsx
- src/ui/components/layout/TabLayout/TabLayout.types.ts
- src/ui/pages/FullPageScanner/FullPageScanner.test.tsx
- src/ui/pages/FullPageScanner/FullPageScanner.tsx
- src/ui/pages/Scan/Scan.scss
- src/ui/pages/Scan/Scan.tsx
Add Camera Switch Button in Scan Options
---
https://github.com/user-attachments/assets/cefa7f29-d2a2-49fb-bd26-ea56781af6dc
https://github.com/user-attachments/assets/a5098378-8aeb-4103-9c7a-9f7ddbc93cf8
[DTIS-1239]: https://cardanofoundation.atlassian.net/browse/DTIS-1239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Add Camera Switch Button in Scan Options

- src/locales/en/en.json
- src/ui/globals/constants.ts
- src/ui/pages/Menu/Menu.test.tsx
- src/ui/pages/Menu/Menu.tsx
- src/ui/pages/Menu/Menu.types.ts
- src/ui/pages/Menu/components/Profile/Profile.scss
- src/ui/pages/Menu/components/Profile/Profile.test.tsx
- src/ui/pages/Menu/components/Profile/Profile.tsx
Adding links to videos for Profile/Crypto/Chat.
---
https://github.com/user-attachments/assets/29b921da-a63c-4a04-8c7d-c256b5b02030
https://github.com/user-attachments/assets/c4897b6c-503e-4a7c-8276-d703bdcda55e
> feat(ui): Profile crypto chat options under more not active

- src/locales/en/en.json
- src/ui/components/SwitchOnboardingMode/SwitchOnboardingMode.tsx
- src/ui/components/TermsModal/TermsModal.scss
- src/ui/components/TermsModal/TermsModal.tsx
- src/ui/components/TermsModal/TermsModal.types.ts
- src/ui/globals/constants.ts
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.test.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
Adding text and link to documentation on the existing (currently empty) SSI Agent information modal.
---
https://github.com/user-attachments/assets/da4b4399-f556-4f86-8d48-68bd30aba208
https://github.com/user-attachments/assets/58ce0cec-7373-4160-85a0-e8755aacd43c
https://github.com/user-attachments/assets/807e20d8-902c-4c4d-b8b2-1b85024a92ba
https://github.com/user-attachments/assets/8058a08f-aeab-43a2-9464-9960c8455ca5
> feat(ui): SSI agent details get more information button

- src/locales/en/en.json
- src/store/reducers/connectionsCache/connectionsCache.test.ts
- src/store/reducers/connectionsCache/connectionsCache.ts
- src/ui/App.scss
- src/ui/components/ArchivedCredentials/ArchivedCredentials.test.tsx
- src/ui/components/Scanner/Scanner.scss
- src/ui/components/Scanner/Scanner.test.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/components/Scanner/Scanner.types.ts
- src/ui/globals/types.ts
- src/ui/pages/Connections/Connections.test.tsx
- src/ui/pages/Connections/Connections.tsx
- src/ui/utils/urlChecker.test.ts
- src/ui/utils/urlChecker.ts
Update feedback when scan connection fail
---
https://github.com/user-attachments/assets/430e8c21-acce-4441-a1c4-0acbbfeadfe0
[DTIS-1251]: https://cardanofoundation.atlassian.net/browse/DTIS-1251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): normal scan feedback

- src/core/agent/services/connectionService.ts
- src/core/storage/storage.types.ts
- src/locales/en/en.json
- src/store/reducers/identifiersCache/identifiersCache.test.ts
- src/store/reducers/identifiersCache/identifiersCache.ts
- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.types.ts
- src/ui/components/CreateIdentifier/components/IdentifierStage1.tsx
- src/ui/components/Scanner/Scanner.test.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/components/Scanner/Scanner.types.ts
- src/ui/globals/types.ts
- src/ui/pages/Identifiers/Identifiers.test.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
- src/ui/pages/Scan/Scan.test.tsx
Multi-Sig Scan Feedback
---
https://github.com/user-attachments/assets/fbf98639-1eab-40c4-b343-6829f260a42b
https://github.com/user-attachments/assets/5926bed1-6e9c-498b-a15d-159400ab7afd
https://github.com/user-attachments/assets/67527f70-2b5c-495f-99a2-1ce9573e2a12
[DTIS-1250]: https://cardanofoundation.atlassian.net/browse/DTIS-1250?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Multi-Sig Scan Feedback

- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.test.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.tsx
Fix deleting a stale connection fails
---
https://github.com/user-attachments/assets/df009c45-6835-40f4-96e1-75e1a42817f9
https://github.com/user-attachments/assets/2a17c682-8aa1-4003-9b8f-89deee64c642
[DTIS-1292]: https://cardanofoundation.atlassian.net/browse/DTIS-1292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): fix delete stale connection fail

- src/ui/components/SideSlider/SideSlider.scss
- src/ui/components/SideSlider/SideSlider.test.tsx
- src/ui/components/SideSlider/SideSlider.tsx
- src/ui/components/SideSlider/SideSlider.types.ts
- src/ui/pages/Menu/Menu.tsx
Improve animation of side slider by using css animation instead of Ionic Animation
---
https://github.com/user-attachments/assets/d19e4952-d944-40da-addb-fe5835545277
[Screen_recording_20240909_142446.webm](https://github.com/user-attachments/assets/8e7daa75-3615-4eaa-a494-c27e5ba6ba2b)
[DTIS-1293]: https://cardanofoundation.atlassian.net/browse/DTIS-1293?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Animation improvements

- src/locales/en/en.json
- src/ui/components/TermsModal/TermsModal.scss
- src/ui/components/TermsModal/TermsModal.tsx
- src/ui/globals/constants.ts
- src/ui/pages/Menu/components/Settings/components/TermsAndPrivacy/TermsAndPrivacy.test.tsx
- src/ui/pages/Menu/components/Settings/components/TermsAndPrivacy/TermsAndPrivacy.tsx
Updating Terms of use, Privacy policy and Link to documentation.
---
> fix(ui): Terms of use & privacy policy

- src/ui/App.scss
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/CardsPlaceholder/CardsPlaceholder.scss
- src/ui/components/Scanner/Scanner.tsx
- src/ui/pages/Credentials/Credentials.scss
- src/ui/pages/Credentials/Credentials.tsx
- src/ui/pages/Menu/components/Profile/Profile.scss
- src/ui/pages/VerifyRecoverySeedPhrase/VerifyRecoverySeedPhrase.tsx
In this PR I am fixing the following bugs detailed in the ticket linked below.
1. Page content jumping when empty credentials page loads, as soon as the Archived button loads up 
2. Onboarding as a new user and entering + verifying recovery phrase, from the SSI Agent page if we switch to recovery and fill up all the words we never get to the SSI Agent page again.
3. Edit profile: show video button shouldn’t be so close to the edit field in the Profile section (or maybe not even show up at all when editing)
4. Extra padding in ion-list
5. Stuck on spinner when scanning from browser
---
https://github.com/user-attachments/assets/879864bd-6829-4cf0-bfef-dac8db072ee9
https://github.com/user-attachments/assets/5be40441-cb32-4177-bd40-74c07869ba8c …
> fix(ui): Various bugs

- src/ui/pages/SidePage/components/WalletConnect/WalletConnect.test.tsx
- src/ui/pages/SidePage/components/WalletConnect/WalletConnectStageTwo.tsx
Disable the confirm button when connecting
> feat(ui): disable confirm button when connecting

- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
Refactor the long running operation flow
> feat(core): long running operation hardening

- src/ui/components/PageFooter/PageFooter.scss
- src/ui/components/Scanner/Scanner.scss
- src/ui/components/Scanner/Scanner.tsx
- src/ui/pages/Credentials/Credentials.scss
- src/ui/pages/FullPageScanner/FullPageScanner.scss
- src/ui/pages/Identifiers/Identifiers.scss
- src/ui/pages/Identifiers/Identifiers.tsx
- src/ui/pages/Scan/Scan.scss
Fixing the following issues:
1. No space above the create identifier button (bug)
2. Page jumping between Identifiers and Credentials (before and after)
https://github.com/user-attachments/assets/eaf26bc9-172a-4e1b-a831-8a255b98f6cc
3. Scanner page scrolling vertically (before and after)
https://github.com/user-attachments/assets/64d2fe40-254d-4a92-8966-a6bb61e596d9
4. Stuck on spinner when no camera is available 
---
####
> fix(ui): More bug fixes

- src/ui/components/ArchivedCredentials/ArchivedCredentials.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
- src/ui/pages/ConnectionDetails/components/EditConnectionsModal.scss
- src/ui/pages/Connections/Connections.tsx
- src/ui/pages/Credentials/Credentials.scss
- src/ui/pages/Credentials/Credentials.tsx
- src/ui/pages/Identifiers/Identifiers.scss
- src/ui/pages/Identifiers/Identifiers.tsx
Fixing bugs documented in the ticket linked below.
---
> fix(ui):  Pre-release bug fix 2

- src/ui/pages/Menu/components/SubMenu/SubMenu.scss
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.scss
Fix new UI bug
---
[DTIS-1305]: https://cardanofoundation.atlassian.net/browse/DTIS-1305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): fix UI bug

- src/locales/en/en.json
- src/ui/components/CreateIdentifier/CreateIdentifier.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.types.ts
- src/ui/components/CreateIdentifier/components/IdentifierStage1.test.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1BodyInit.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1BodyResume.tsx
Add delete button  for group identifier
---
https://github.com/user-attachments/assets/117db4ee-8c09-488c-b50e-eb023d51d3eb
[DTIS-1253]: https://cardanofoundation.atlassian.net/browse/DTIS-1253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Delete Pending Group Identifier

- docs/Running-in-an-Emulator.md
The instructions on how to build the app didn't include the requirement of `CocoaPods` for  iOS builds and there was a redundant command.
This PR removes the redundant command and includes a requirements section for Android and iOS builds and a link to the capacitor documentation for more information.   
[DTIS-1328]: https://cardanofoundation.atlassian.net/browse/DTIS-1328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: Improved the requirements description for building the app

- README.md
The video from the README contains outdated information on the features of the Identity Wallet. This PR removed the video from the README.
[DTIS-1304]: https://cardanofoundation.atlassian.net/browse/DTIS-1304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: Removed video with outdated information from README

- src/core/agent/agent.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
Handle deletion of multisig identifiers
> feat(core): Handle deletion of multisig identifiers

- src/locales/en/en.json
- src/routes/backRoute/backRoute.test.ts
- src/routes/nextRoute/nextRoute.test.ts
- src/store/reducers/notificationsCache/notificationsCache.test.ts
- src/store/reducers/stateCache/stateCache.ts
- src/store/reducers/stateCache/stateCache.types.ts
- src/ui/App.scss
- src/ui/App.test.tsx
- src/ui/App.tsx
- src/ui/components/CustomToast/CustomToast.scss
- src/ui/components/CustomToast/CustomToast.test.tsx
- src/ui/components/CustomToast/CustomToast.tsx
- src/ui/components/CustomToast/CustomToast.types.ts
- src/ui/components/CustomToast/ToastStack.tsx
- src/ui/components/Scanner/Scanner.test.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/globals/types.ts
- src/ui/pages/CreatePassword/CreatePassword.test.tsx
- src/ui/pages/FullPageScanner/FullPageScanner.test.tsx
- src/ui/pages/Menu/components/ConfirmConnectModal/ConfirmConnectModal.test.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.test.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.tsx
- src/ui/pages/Scan/Scan.test.tsx
- src/ui/pages/Scan/Scan.tsx
Implement new UI for toast element:
- Add dismiss button
- Support stack toast message 
---
https://github.com/user-attachments/assets/c53142aa-eae8-4416-8a60-8e73591a88f6
https://github.com/user-attachments/assets/535ad066-7882-447d-a142-1915dbf5c4b5
[DTIS-1185]: https://cardanofoundation.atlassian.net/browse/DTIS-1185?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): New Toast UI Elements

- src/locales/en/en.json
- src/ui/components/CardList/CardList.scss
- src/ui/components/CardList/CardList.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential.tsx
- src/ui/pages/SidePage/components/WalletConnect/WalletConnectStageTwo.tsx
In this PR I am fixing a misleading description in the ChooseCredential page (when we receive a request to provide a credential).
In addition to that, I have fixed a bug where before you couldn't select the credential if you were clicking slightly off the title as documented [here](https://cardanofoundation.slack.com/archives/C04DUEK6B25/p1726568000649399).
Some adjustments were made to remove the padding and make the entire item area clickable.
Since I am not introducing any new UI element, I am only capturing a video of the changes on the browser for two different places where that items list is being used (one of them is the one where we replace the misleading page description).
---
https://github.com/user-attachments/assets/5dae2f5f-db43-4251-929b-de2b148ceccf …
> bugfix(ui): Choose credential list showing misleading title

- services/credential-server/src/modules/signify/signifyApi.ts
wait for the credential to be revoked
> feat(cred-server): wait for the credential to be revoked

- src/ui/__fixtures__/notificationsFix.ts
- src/ui/pages/Notifications/Notifications.test.tsx
- src/ui/pages/Notifications/Notifications.tsx
Update click action of revoked credential notification.
---
https://github.com/user-attachments/assets/eb4b5337-ed06-4549-9331-c3a82dcc273e
[DTIS-1349]: https://cardanofoundation.atlassian.net/browse/DTIS-1349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Archived credentials: wrong redirection

- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
return when credential has not been revoked
> feat(core): return when credential has not been revoked

- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
Get acdc details from grant exn
> feat(core): Get acdc details from grant exn

- src/locales/en/en.json
- src/store/reducers/stateCache/stateCache.ts
- src/ui/components/CredentialDetailModule/CredentialDetailModal.tsx
- src/ui/components/CredentialDetailModule/CredentialDetailModule.test.tsx
- src/ui/components/CredentialDetailModule/CredentialDetailModule.tsx
- src/ui/components/CredentialDetailModule/CredentialDetailModule.types.ts
- src/ui/components/CredentialDetailModule/components/CredentialContent.tsx
- src/ui/components/Spinner/Spinner.scss
- src/ui/pages/NotificationDetails/NotificationDetails.test.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.scss
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCrendential.test.tsx
This PR use to implement view details about the issued credential.
---
https://github.com/user-attachments/assets/409841f1-6de6-48ae-9701-a0e42b610bd6
https://github.com/user-attachments/assets/f769c03b-0be9-4ac4-82c7-f356fe797ba9
[DTIS-1338]: https://cardanofoundation.atlassian.net/browse/DTIS-1338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Credential Details from Receive Credential

- package-lock.json
- package.json
- src/ui/components/PasswordModule/PasswordModule.tsx
- src/ui/components/Scanner/Scanner.test.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/components/VerifyPassword/VerifyPassword.tsx
- src/ui/pages/FullPageScanner/FullPageScanner.test.tsx
- src/ui/pages/Scan/Scan.test.tsx
Clean up all warnings after updating to Capacitor 6
---
https://github.com/user-attachments/assets/60a46469-acdc-40fe-96ba-f830b4e7d25f
https://github.com/user-attachments/assets/731b48ba-d502-4dc3-a4f3-06290998cc80
https://github.com/user-attachments/assets/e52f223e-77d1-44d0-8d55-29eb075c73ca
https://github.com/user-attachments/assets/89f571ec-dd89-4dce-bb38-29a7b9d9c602
https://github.com/user-attachments/assets/1cdc2afe-13cb-4a7c-8444-7b24980c1371
https://github.com/user-attachments/assets/618fac44-37df-48d0-a115-7628d1bed98a
[DTIS-1341]: https://cardanofoundation.atlassian.net/browse/DTIS-1341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(ui): UI: Clean up all warnings after updating to Capacitor 6

- src/core/agent/agent.ts
- src/core/agent/services/authService.test.ts
- src/core/agent/services/authService.ts
- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
- src/core/agent/services/credentialService.test.ts
- src/core/agent/services/credentialService.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
Final core cleanup (Agent.agent)
> refactor(core): final core cleanup (Agent.agent)

- src/core/storage/ionicStorage/ionicStorage.ts
- src/core/storage/sqliteStorage/migrations/v0.0.2-credentialPrefix.ts
- src/core/storage/sqliteStorage/sqliteStorage.ts
- src/core/storage/utils.ts
Storage: Enforce type of record
> fix: enforce type of record in storage

- src/ui/pages/Menu/Menu.tsx
- src/ui/pages/Menu/components/MenuItem.tsx
- src/ui/pages/Menu/components/SubMenu/SubMenuComponents.tsx
- src/ui/pages/Menu/components/SubMenuItems.tsx
In this PR I am refactoring all the sub menus which are currently all in one list, when some are accessed from Menu and some from within Settings. I am creating a separate component which includes two separate lists, one for the menu elements and another one for all settings elements.
No changes to the UI, just adding videos to show that nothing got broken.
---
https://github.com/user-attachments/assets/6b484093-1e78-4bb0-a2ef-3a65975fa4a5
https://github.com/user-attachments/assets/e6ba3705-5564-415e-bfd0-8fc3acd92446
> fix(ui): Refactoring sub menu elements

- src/locales/en/en.json
- src/ui/components/SideSlider/SideSlider.tsx
- src/ui/components/layout/TabLayout/TabLayout.tsx
- src/ui/hooks/toggleConnectionHook.ts
- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/Connections/Connections.scss
- src/ui/pages/Connections/Connections.test.tsx
- src/ui/pages/Connections/Connections.tsx
- src/ui/pages/Connections/components/ConnectionsBody/ConnectionsBody.scss
- src/ui/pages/Connections/components/ConnectionsBody/ConnectionsBody.tsx
- src/ui/pages/Connections/components/ConnectionsBody/ConnectionsBody.types.ts
- src/ui/pages/Connections/components/ConnectionsBody/SearchInput.test.tsx
- src/ui/pages/Connections/components/ConnectionsBody/SearchInput.tsx
- src/ui/pages/Connections/components/ConnectionsBody/index.ts
- src/ui/pages/Connections/components/SearchConnectionContent/SearchConnectionContent.scss
- src/ui/pages/Connections/components/SearchConnectionContent/SearchConnectionContent.tsx
- src/ui/pages/Connections/components/SearchConnectionContent/index.ts
- src/ui/pages/Credentials/Credentials.test.tsx
Implement search bar for connections
---
https://github.com/user-attachments/assets/0bee6bf1-4c2e-4d54-9d7e-d973e9701971
https://github.com/user-attachments/assets/4137ca7c-9498-4c85-8cb6-3c7cd9e2b46a
[DTIS-1337]: https://cardanofoundation.atlassian.net/browse/DTIS-1337?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): [UI] Search Bar

- src/ui/components/SideSlider/SideSlider.tsx
- src/ui/components/SideSlider/SideSlider.types.ts
- src/ui/pages/Connections/Connections.scss
- src/ui/pages/Connections/Connections.test.tsx
- src/ui/pages/Connections/Connections.tsx
- src/ui/pages/Notifications/Notifications.tsx
- Fix an issue about filter credential
- Fix connection slider animation issue
---
https://github.com/user-attachments/assets/755dabd5-8a74-4345-8174-8a6b3da57c3c
https://github.com/user-attachments/assets/3a305418-0f43-44e0-a93b-ce94502d67d0
https://github.com/user-attachments/assets/7023a8f4-ed52-448c-873a-77b70ddbb639
[DTIS-1391]: https://cardanofoundation.atlassian.net/browse/DTIS-1391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Buggy Notifications filters

- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.test.tsx
- Fix UT of connect wallet page
---
[DTIS-1391]: https://cardanofoundation.atlassian.net/browse/DTIS-1391?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ut): fix connect wallet UT

- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
[Core] Receive credential UI supporting functionality
> feat(core): receive credential UI supporting functionality

- src/core/agent/services/keriaNotificationService.ts
Handle operation long running with multi-sig present credential
> fix: update handle operation long running with multi-sig present credential

- src/store/reducers/walletConnectionsCache/walletConnectionsCache.test.ts
- src/store/reducers/walletConnectionsCache/walletConnectionsCache.ts
- src/store/reducers/walletConnectionsCache/walletConnectionsCache.types.ts
- src/ui/App.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.test.tsx
- src/ui/components/IdentifierOptions/IdentifierOptions.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/globals/types.ts
- src/ui/pages/FullPageScanner/FullPageScanner.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.tsx
- src/ui/pages/Menu/Menu.test.tsx
- src/ui/pages/Menu/Menu.tsx
- src/ui/pages/Menu/components/Profile/Profile.test.tsx
- src/ui/pages/WalletConnect/WalletConnect.test.tsx
- src/ui/pages/WalletConnect/WalletConnectStageOne.tsx
- Fix wrong navigating to connections
- Add missing identifier alert when connect wallet by scan tab
---
https://github.com/user-attachments/assets/c8ee0d05-f327-45d4-a79e-99ad3df42c74
https://github.com/user-attachments/assets/80f9a71f-d9b8-4e25-add4-e95ee02dc2f4
[DTIS-1447]: https://cardanofoundation.atlassian.net/browse/DTIS-1447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Wrongfully navigating to Connections

- src/locales/en/en.json
- src/ui/components/CardDetails/CardDetailsItem/CardDetailsItem.scss
- src/ui/components/CardDetails/CardDetailsItem/CardDetailsItem.test.tsx
- src/ui/components/CardDetails/CardDetailsItem/CardDetailsItem.tsx
- src/ui/components/CardDetails/CardDetailsItem/CardDetailsItem.types.ts
- src/ui/pages/IdentifierDetails/components/IdentifierContent.tsx
- src/ui/pages/IdentifierDetails/components/RotateKeyModal/RotateKeyModal.tsx
Updating identifier details removing the letter icons before some of the items listed in the description.
NOTE:
I am not introducing any new UI element so I will only take a screenshot of the preview in the browser.
---
> feat(ui): Improve identifier details - remove letter icons

- src/core/__fixtures__/agent/ipexCommunicationFixture.ts
- src/core/__fixtures__/agent/multSigFixtures.ts
- src/core/agent/records/identifierMetadataRecord.ts
- src/core/agent/services/identifier.types.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
- Remove signifyOpName and any checks relating to it
- Remove markMultisigCompleteIfReady
> feat(core): removal of signifyOpName

- src/core/agent/event.types.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
- src/ui/App.test.tsx
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/AppWrapper/coreEventListeners.ts
Add event to remove notification after receiving credential confirm
> fix(core): remove notification after credential has confirmed

- src/core/agent/event.types.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
- src/locales/en/en.json
- src/ui/App.test.tsx
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/AppWrapper/coreEventListeners.ts
- src/ui/components/Scanner/Scanner.tsx
- src/ui/pages/NotificationDetails/NotificationDetails.test.tsx
- src/ui/pages/NotificationDetails/components/MultisigMember/MultisigMember.scss
- src/ui/pages/NotificationDetails/components/MultisigMember/MultisigMember.tsx
- src/ui/pages/NotificationDetails/components/MultisigMember/MultisigMember.types.ts
- src/ui/pages/NotificationDetails/components/MultisigMember/index.ts
- src/ui/pages/NotificationDetails/components/ReceiveCredential/Member.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.scss
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.test.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.types.ts
Implement issue group credential.
---
https://github.com/user-attachments/assets/717a8a4d-ecee-4a05-a93f-f314df70dcd5
https://github.com/user-attachments/assets/9078dcad-1df4-419a-bf6b-6fcdf4cc2176
[DTIS-1436]: https://cardanofoundation.atlassian.net/browse/DTIS-1436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui):  [Frontend] Multi-sig IPEX: Group Status in Credential Issuance

- Earthfile
- docker-compose.yaml
- services/docker-compose.yaml
- src/core/agent/agent.test.ts
- src/core/agent/agent.ts
409 if KERIA already booted on new version instead of 400.
> chore: upgrade keria version and switch to 409 check

- services/credential-server-ui/src/App.tsx
- services/credential-server-ui/src/components/ConnectionQR.tsx
- services/credential-server-ui/src/components/NavBar.tsx
- services/credential-server-ui/src/components/credentialForms/prescriptionForm.tsx
- services/credential-server-ui/src/components/credentialForms/relationshipCredential.tsx
- services/credential-server-ui/src/components/inputOOBI/InputOobi.tsx
- services/credential-server-ui/src/config.ts
- services/credential-server-ui/src/index.tsx
- services/credential-server-ui/src/pages/ConnectionPage.tsx
- services/credential-server-ui/src/pages/ConnectionsIssuerPage.tsx
- services/credential-server-ui/src/pages/CredentialPage.tsx
- services/credential-server-ui/src/pages/RequestCredential.tsx
- services/credential-server-ui/src/pages/RevocationPage.tsx
- services/credential-server/src/agent.ts
- services/credential-server/src/apis/credential.api.ts
- services/credential-server/src/apis/oobi.api.ts
- services/credential-server/src/cli/multiSigIncept.ts
- services/credential-server/src/cli/revokeCredential.ts
- services/credential-server/src/cli/utils.ts
- services/credential-server/src/modules/signify/signifyApi.ts
- services/credential-server/src/modules/signify/utils.ts
- services/credential-server/src/server.ts
- services/credential-server/src/utils/schemas.ts
Ran prettier on the entire project after fixing the prettier pre-commit hook [PR](https://github.com/cardano-foundation/cf-identity-wallet/pull/789)
> style: ran prettier on entire project

- services/credential-server-ui/package-lock.json
- services/credential-server-ui/package.json
Added again the eslint configuration in the package.json of the cred ui
> fix: add eslint config in cred UI

- src/ui/pages/Credentials/Credentials.test.tsx
- src/ui/pages/Credentials/Credentials.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
> feat(ui): Ensure Favorites appear in both “Favorites” and “All Identifiers/Credentials” screens

- src/locales/en/en.json
- src/ui/globals/types.ts
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.test.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/MultiSigRequest.tsx
Handle error when input SSI agent details. Beside that, I also fix an issue about footer of Receive Identifier screen not display.
---
https://github.com/user-attachments/assets/b45ab529-7080-48a7-ad22-754932fed8be
https://github.com/user-attachments/assets/4c4c4b9c-7153-47b0-98e4-6a2ffeb7d18e
https://github.com/user-attachments/assets/a8a8e407-891e-4e65-ab48-c47caff24652
https://github.com/user-attachments/assets/3687ce34-630b-40bd-b04c-0acff65a7416
[DTIS-1252]: https://cardanofoundation.atlassian.net/browse/DTIS-1252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): SSI Agent Details: Error Handling

- src/locales/en/en.json
- src/ui/components/CardsPlaceholder/CardsPlaceholder.scss
- src/ui/components/CardsPlaceholder/CardsPlaceholder.tsx
- src/ui/components/CardsPlaceholder/CardsPlaceholder.types.ts
- src/ui/pages/Connections/Connections.tsx
- src/ui/pages/Credentials/Credentials.test.tsx
- src/ui/pages/Credentials/Credentials.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.tsx
> feat(ui): Remove add a credential button

- android/app/capacitor.build.gradle
- android/capacitor.settings.gradle
- ios/App/Podfile
- ios/App/Podfile.lock
These were hanging around and should be removed.
> build: remove preferences from native build files

- src/ui/components/CardSlider/CardSlider.scss
- src/ui/components/CardSlider/CardSlider.tsx
- src/ui/components/CardSlider/CardSlider.types.ts
- src/ui/components/IdentifierCardTemplate/cardOffsetTopHook.ts
- src/ui/pages/Credentials/Credentials.scss
- src/ui/pages/Credentials/Credentials.test.tsx
- src/ui/pages/Credentials/Credentials.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
Add slider to favourites in Credentials
---
[DTIS-1506]: https://cardanofoundation.atlassian.net/browse/DTIS-1506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): change favourite cred from stack to slider

- src/locales/en/en.json
- src/ui/components/Scanner/Scanner.scss
- src/ui/components/Scanner/Scanner.test.tsx
- src/ui/components/Scanner/Scanner.tsx
Handle error when camera is not available
---
[DTIS-1484]: https://cardanofoundation.atlassian.net/browse/DTIS-1484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Error in camera not available

- src/locales/en/en.json
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/InfoCard/InfoCard.scss
- src/ui/components/InfoCard/InfoCard.tsx
- src/ui/components/InfoCard/InfoCard.types.ts
- src/ui/components/InfoCard/index.ts
- src/ui/pages/IdentifierDetails/IdentifierDetails.test.tsx
- src/ui/pages/IdentifierDetails/components/IdetifierDetailModal/IdentifierDetailModal.scss
- src/ui/pages/IdentifierDetails/components/IdetifierDetailModal/IdentifierDetailModal.tsx
- src/ui/pages/IdentifierDetails/components/RotateKeyModal/RotateKeyModal.scss
- src/ui/pages/IdentifierDetails/components/RotateKeyModal/RotateKeyModal.tsx
- src/ui/styles/colors.scss
Present the user a message when rotating key informing about potential delays in using the identifier.
---
https://github.com/user-attachments/assets/644431d6-7679-47c4-82b4-ce169461fe92
[DTIS-1479]: https://cardanofoundation.atlassian.net/browse/DTIS-1479?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): add message for rotate key modal

- src/locales/en/en.json
- src/ui/components/CreateIdentifier/CreateIdentifier.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.test.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage0.test.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage0.tsx
- src/ui/components/EditIdentifier/EditIdentifier.scss
- src/ui/components/EditIdentifier/EditIdentifier.test.tsx
- src/ui/components/EditIdentifier/EditIdentifier.tsx
- src/ui/components/InputRequest/InputRequest.scss
- src/ui/components/InputRequest/InputRequest.test.tsx
- src/ui/components/InputRequest/InputRequest.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/pages/IdentifierDetails/components/RotateKeyModal/RotateKeyModal.scss
- src/ui/pages/Menu/Menu.tsx
- src/ui/pages/Menu/components/Profile/Profile.scss
- src/ui/pages/Menu/components/Profile/Profile.test.tsx
- src/ui/pages/Menu/components/Profile/Profile.tsx
- src/ui/pages/Menu/components/SubMenu/SubMenu.scss
- src/ui/utils/nameChecker.test.ts
- src/ui/utils/nameChecker.ts
Add validation for connection name, identifier name and user name
---
https://github.com/user-attachments/assets/8be1508b-e424-4132-b086-8d73a122e91d
https://github.com/user-attachments/assets/51349a1f-5afc-4d9a-ba53-c911866c57a8
https://github.com/user-attachments/assets/7cdc5699-850d-4146-b003-2238394cfe1b
https://github.com/user-attachments/assets/54aeb331-f3a1-439e-8751-02b6799f602e
Currently, Core team didn't checked when user input duplicate identifier name on edit identifier modal. 
https://github.com/user-attachments/assets/1c1af103-b904-42c0-abf9-efdf8e5ebe46
https://github.com/user-attachments/assets/bf61cc04-3630-4b9e-9095-3f797d6df15e
https://github.com/user-attachments/assets/06158b5e-0427-47ce-8b37-544f4698b77a
https://github.com/user-attachments/assets/de36c936-51b6-48d6-930 …
> feat(ui): Validation: Connections - Identifier - User Name

- src/ui/App.test.tsx
- src/ui/App.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.scss
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.scss
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
- src/ui/styles/colors.scss
- src/ui/utils/nameChecker.ts
Fix bugs:
- Blur missing when submitting SSI agent details
- Missing “Pending” connection 
- After entering a manual URL for a connection and rebooting the emulator, the scan page doensn’t seem to work.
- Icon too big for double arrow when accepting credential
- Issue with animation not smooth when accepting credential
- Error message when loading app, right after login
- Check webpack warning
---
https://github.com/user-attachments/assets/0ea222b9-f85c-4e37-8a55-1f981d30b065
https://github.com/user-attachments/assets/6d2d5130-5716-4e80-90c0-98a517e51c28
https://github.com/user-attachments/assets/2c441799-13d9-4c86-84c6-3ab114dd778d
https://github.com/user-attachments/assets/d9b175ae-7469-403a-afb7-f0360fb12f1e
https://github.com/user-attachments/assets/9106e64c-fe3c-4e96-bed7-0f4bb4d8fba5 …
> fix(ui): Bug fixes 13 Nov 2024

- src/ui/components/Scanner/Scanner.test.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/components/SwitchOnboardingMode/SwitchOnboardingMode.test.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.test.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
- src/ui/pages/Scan/Scan.test.tsx
Handle error when opening a Receive credential notification
---
https://github.com/user-attachments/assets/3509a24d-d8ee-4837-8382-fddc78417d06
[DTIS-1545]: https://cardanofoundation.atlassian.net/browse/DTIS-1545?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Error when opening a Receive credential notification

- src/ui/components/CreateGroupIdentifier/CreateGroupIdentifier.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
- src/ui/components/ShareConnection/ShareConnection.test.tsx
- src/ui/components/ShareConnection/ShareConnection.tsx
- Handle unexpected error when closing more sharing options menu
- Clear error message after close create identifier modal
- Update footer style for create identifier and setup connections page
---
https://github.com/user-attachments/assets/bc420f75-fff1-4dae-b161-eb6c22b0c535
https://github.com/user-attachments/assets/36a75137-0323-4b59-a116-160cfb091060
[DTIS-1566]: https://cardanofoundation.atlassian.net/browse/DTIS-1566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Unexpected error when closing more sharing options menu

- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
Update the identifier sync function to create any missing identifiers locally
Identifiers related to multi-sig should be correctly created and not appear as an individual identifier
Identifiers should be marked as pending if a long running operation exists on KERIA in the correct format that has not completed (witness.<ID>, group.<ID> etc)
> feat: Syncing of identifier

- src/locales/en/en.json
- src/ui/components/CredentialDetailModule/CredentialDetailModule.tsx
- src/ui/components/CredentialDetailModule/components/CredentialContent.tsx
- src/ui/components/Scanner/Scanner.test.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/pages/FullPageScanner/FullPageScanner.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential/ChooseCredential.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/MultiSigRequest.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
- src/ui/pages/Notifications/NotificationItem.tsx
- src/ui/pages/Scan/Scan.test.tsx
Create dummy connection name when connection is missing.
I also fix an issue about show multiple toasts after scan connection
---
https://github.com/user-attachments/assets/e2911461-64f9-4424-abad-40fbdb53cbf4
https://github.com/user-attachments/assets/64bc78f6-2a0b-42fc-ab5a-60809fc47243
[DTIS-1571]: https://cardanofoundation.atlassian.net/browse/DTIS-1571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Connection deleted

- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
No ticket for this, just in preparation for the UI ticket. Very small change.
> feat(core): expose witness set function to UI

- src/locales/en/en.json
- src/store/reducers/stateCache/stateCache.ts
- src/store/reducers/stateCache/stateCache.types.ts
- src/ui/App.test.tsx
- src/ui/App.tsx
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.test.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
- src/ui/components/Error/NoWitnessAlert.tsx
- src/ui/components/Error/index.ts
Display alert when no witness availability
---
[DTIS-1602]: https://cardanofoundation.atlassian.net/browse/DTIS-1602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): No witness availability

- src/ui/App.scss
- src/ui/components/CardDetails/CardDetailsItem/CardDetailsItem.scss
- src/ui/styles/colors.scss
Adjust black color
---
[DTIS-1623]: https://cardanofoundation.atlassian.net/browse/DTIS-1623?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): adjust black color

- src/locales/en/en.json
Update new text content for password screen
---
[DTIS-1613]: https://cardanofoundation.atlassian.net/browse/DTIS-1613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Revise adding password copy

- src/locales/en/en.json
- src/ui/components/CardDetails/CardDetailsExpandAttributes/CardDetailsExpandAttributes.tsx
- src/ui/components/CredentialDetailModule/components/CredentialContent.test.tsx
Changes to Attribute view
---
[DTIS-1625]: https://cardanofoundation.atlassian.net/browse/DTIS-1625?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): [Frontend] Changes to Attribute view

- src/core/agent/services/connectionService.ts
Add resolve oobi for individual.
> fix: resolve oobi for connect with individual

- src/locales/en/en.json
- src/ui/App.tsx
- src/ui/components/AppOffline/AppOffline.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
- src/ui/components/PageHeader/PageHeader.types.ts
- src/ui/pages/LockPage/LockPage.tsx
- src/ui/pages/Menu/components/SubMenu/SubMenu.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.tsx
- src/ui/styles/colors.scss
Fix bugs
---
https://github.com/user-attachments/assets/110301d6-2394-4138-a2ed-e2af0abcbca9
https://github.com/user-attachments/assets/d6d7f22a-2371-4963-a1e1-cb4564bfa532
[DTIS-1634]: https://cardanofoundation.atlassian.net/browse/DTIS-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Multi sig bugs 30 Dec 2024

- src/ui/components/CreateGroupIdentifier/CreateGroupIdentifier.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.test.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
- src/ui/components/EditIdentifier/EditIdentifier.test.tsx
- src/ui/components/EditIdentifier/EditIdentifier.tsx
Implement new validation to ensure identifier names are unique at the UI level.
Beside that, I also fix an issue about UI when initiate group identifier.
---
https://github.com/user-attachments/assets/43cc621a-0bab-4368-82ca-ff8c191a9e16
https://github.com/user-attachments/assets/680a47b6-a86b-4f2a-8954-9c87f06ec0d5
https://github.com/user-attachments/assets/2fcb12d4-e1ee-46f1-a273-b320aa35749b
[DTIS-1633]: https://cardanofoundation.atlassian.net/browse/DTIS-1633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Ensure identifier names are unique at the UI level

- src/core/agent/services/credentialService.test.ts
- src/core/agent/services/credentialService.ts
- src/core/agent/services/credentialService.types.ts
- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/utils.ts
- src/locales/en/en.json
- src/store/reducers/credsArchivedCache/credsArchivedCache.test.ts
- src/store/reducers/credsCache/credsCache.test.ts
- src/ui/__fixtures__/connectionsFix.ts
- src/ui/__fixtures__/credsFix.ts
- src/ui/__fixtures__/filteredCredsFix.ts
- src/ui/__fixtures__/shortCredsFix.ts
- src/ui/components/CreateIdentifier/CreateIdentifier.scss
- src/ui/components/CredentialCardTemplate/components/KeriCardTemplate/KeriCardTemplate.scss
- src/ui/components/CredentialCardTemplate/components/KeriCardTemplate/KeriCardTemplate.test.tsx
- src/ui/components/CredentialCardTemplate/components/KeriCardTemplate/KeriCardTemplate.tsx
- src/ui/components/CredentialDetailModule/CredentialDetailModule.test.tsx
- src/ui/components/CredentialDetailModule/components/CredentialContent.test.tsx
- src/ui/components/SwitchCardView/SwitchCardView.test.tsx
- src/ui/components/VerifyPasscode/VerifyPasscode.test.tsx
- src/ui/pages/CredentialDetails/CredentialDetails.test.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
Consider adding issuer name in single credential view
---
[DTIS-1622]: https://cardanofoundation.atlassian.net/browse/DTIS-1622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Consider adding issuer name in single credential view

- src/ui/components/CardDetails/CardDetailsBlock/CardBlock.tsx
- src/ui/components/CardDetails/CardDetailsItem/CardDetailsItem.tsx
- src/ui/components/CredentialDetailModule/components/CredentialContent.tsx
- src/ui/components/IdentifierDetailModule/components/IdentifierAttributeDetailModal/Advanced.tsx
- src/ui/components/IdentifierDetailModule/components/IdentifierAttributeDetailModal/List.tsx
- src/ui/components/IdentifierDetailModule/components/IdentifierAttributeDetailModal/RotationThreshold.tsx
- src/ui/components/IdentifierDetailModule/components/IdentifierAttributeDetailModal/SigningThreshold.tsx
- src/ui/components/IdentifierDetailModule/components/IdentifierContent.tsx
- src/ui/components/PageFooter/PageFooter.tsx
Fix test id contain `undefined` value.
---
[DTIS-1649]: https://cardanofoundation.atlassian.net/browse/DTIS-1649?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): CardDetailsItem: undefined test id

- src/ui/components/CreateGroupIdentifier/CreateGroupIdentifier.scss
- src/ui/components/CreateGroupIdentifier/CreateGroupIdentifier.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
- src/ui/components/Spinner/Spinner.tsx
- src/ui/components/navigation/TabsMenu/TabsMenu.scss
- src/ui/components/navigation/TabsMenu/TabsMenu.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/MultiSigRequest.scss
- src/ui/pages/NotificationDetails/components/MultiSigRequest/MultiSigRequest.tsx
Bug fixes for spike DTIS-1592
---
https://github.com/user-attachments/assets/08975a14-6774-4fe1-ad05-cb422c87ac3b
https://github.com/user-attachments/assets/a92f24e7-4625-4cb8-b8b7-3a69f40b651d
https://github.com/user-attachments/assets/eca551e8-b431-4b79-b14f-249b5f6d9d63
https://github.com/user-attachments/assets/a04e62fc-f8d8-4148-870a-3be7b9e9a4c6
[DTIS-1661]: https://cardanofoundation.atlassian.net/browse/DTIS-1661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Bug fixes for spike DTIS-1592

- src/ui/components/Alert/Alert.test.tsx
- src/ui/components/CardSlider/CardSlider.test.tsx
- src/ui/pages/Identifiers/Identifiers.test.tsx
Revisit skipped tests
[DTIS-114]: https://cardanofoundation.atlassian.net/browse/DTIS-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ut): Revisit skipped tests

- src/routes/nextRoute/nextRoute.ts
Fix lock screen asking for biometrics automatically
---
https://github.com/user-attachments/assets/7c3765b9-6136-4bb7-89b1-e45d8e319504
> fix(ui): Lock screen asking for biometrics automatically

- src/ui/components/CardsStack/CardsStack.scss
Add drop shadow on identifiers and credentials cards
---
> feat(ui): Add drop shadow on identifiers and credentials cards

- services/cip45-sample-dapp/src/pages/Demo.tsx
- src/core/cardano/walletConnect/peerConnection.ts
Using stable tracker: `wss://tracker.webtorrent.dev:443/announce`
We can monitor it from  [here](https://tracker.webtorrent.dev/).
CF tracker: `wss://dev.btt.cf-identity-wallet.metadata.dev.cf-deployments.org`
> fix: trackers and demo connection

- ios/App/Podfile.lock
- package-lock.json
- package.json
- [] There is no unused functionality or blocks of commented out code (otherwise, please explain below)
- [] In addition to this PR, all relevant documentation (e.g. Confluence) and architecture diagrams (e.g. Miro) were updated
> fix: upgrade capacitor-secure-storage-plugin to 3.1.5

- src/locales/en/en.json
- src/ui/components/CreateGroupIdentifier/CreateGroupIdentifier.scss
- src/ui/components/CreateGroupIdentifier/CreateGroupIdentifier.tsx
- src/ui/components/CreateGroupIdentifier/CreateGroupIdentifier.types.ts
- src/ui/components/CreateGroupIdentifier/components/SetupConnectionBodyInit.tsx
- src/ui/components/CreateGroupIdentifier/components/SetupConnectionBodyResume.tsx
- src/ui/components/CreateGroupIdentifier/components/SetupConnections.test.tsx
- src/ui/components/CreateGroupIdentifier/components/SetupConnections.tsx
- src/ui/pages/Identifiers/Identifiers.test.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
Handle delays in creating group local member identifier
---
https://github.com/user-attachments/assets/36596b84-a4b9-47f0-9ed4-b1e0ed812808
> feat(ui): [frontend] Handle delays in creating group local member identifier

- tests/features/identifiers/individual-identifier-delete.feature
- tests/features/identifiers/individual-identifier-details.feature
- tests/features/identifiers/individual-identifier-edit.feature
- tests/features/identifiers/individual-identifier-favourite.feature
- tests/features/identifiers/individual-identifier-share.feature
- tests/features/identifiers/individual-identifier.feature
- tests/features/menu/menu.feature
- tests/features/onboarding/create-password.feature
- tests/features/onboarding/onboarding.feature
- tests/features/onboarding/passcode.feature
- tests/features/onboarding/verify-your-recovery-phrase.feature
- tests/features/onboarding/your-recovery-phrase.feature
Added case ID from TestRail for each scenario title in all features files.
> QA DTIS-1548 import scenarios into TestRail

- src/locales/en/en.json
- src/ui/__fixtures__/filteredIdentifierFix.ts
- src/ui/components/CreateGroupIdentifier/CreateGroupIdentifier.scss
- src/ui/components/CreateGroupIdentifier/components/SetupConnectionBodyInit.tsx
- src/ui/components/CreateGroupIdentifier/components/SetupConnectionBodyResume.tsx
- src/ui/pages/Identifiers/Identifiers.test.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
Show an alert when Identifier is created and got creation status is `ERROR` because witness is not available.  
---
https://github.com/user-attachments/assets/9cbcfcb2-fb93-4770-b938-894cf2083690
[DTIS-1743]: https://cardanofoundation.atlassian.net/browse/DTIS-1743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Identifier creation: whiteness time out message

- src/ui/pages/LockPage/LockPage.tsx
Prevent biometrics auth method re-open after user cancel.
---
https://github.com/user-attachments/assets/3ee3726c-1ba5-40a2-a2ae-e3b566276386
> fix(ui): Cannot revert to using passcode to login

- Earthfile
For auto-deploys from merges to main.
> build: point to forked KERIA in earthfile

- services/credential-server-ui/src/components/NavBar/NavBar.scss
- services/credential-server-ui/src/components/NavBar/NavBar.tsx
- services/credential-server-ui/src/components/NavBar/components/DrawerContent/DrawerContent.tsx
- services/credential-server-ui/src/components/NavBar/components/DrawerContent/DrawerContent.types.ts
- services/credential-server-ui/src/components/NavBar/components/DrawerContent/index.ts
- services/credential-server-ui/src/components/SwitchAccount/SwitchAccount.scss
- services/credential-server-ui/src/components/SwitchAccount/SwitchAccount.tsx
- services/credential-server-ui/src/components/SwitchAccount/components/HolderModal/HolderModal.scss
- services/credential-server-ui/src/components/SwitchAccount/components/HolderModal/HolderModal.tsx
- services/credential-server-ui/src/components/SwitchAccount/components/HolderModal/HolderModal.types.ts
- services/credential-server-ui/src/components/SwitchAccount/components/HolderModal/index.ts
- services/credential-server-ui/src/constants/roles.ts
- services/credential-server-ui/src/main.tsx
- services/credential-server-ui/src/pages/Connections/Connections.tsx
- services/credential-server-ui/src/pages/Credentials/Credentials.tsx
- services/credential-server-ui/src/pages/Overview/Overview.tsx
- services/credential-server-ui/src/store/hooks.ts
- services/credential-server-ui/src/store/index.ts
- services/credential-server-ui/src/store/reducers/index.ts
- services/credential-server-ui/src/store/reducers/stateCache.ts
- services/credential-server-ui/src/store/reducers/stateCache.types.ts
- services/credential-server-ui/src/styles/main.scss
* Adding the possibility to switch view between users using Redux.
* Added a new full screen modal for the Holder (keeping it hidden with style until we will decide what to do with it).
* Updated the icons in the NavBar as they switch between empty and full when we select them.
* Refactored the NavBar extracting the Drawer content into a separate file.
* Simplified imports across all files.
https://github.com/user-attachments/assets/08c48893-b0f6-4646-904f-734a62589f8c
> feat(cred-ui): Role based views

- android/app/capacitor.build.gradle
- android/capacitor.settings.gradle
- ios/App/Podfile
- ios/App/Podfile.lock
These should be committed when adding new Capacitor plugins @Sotatek-DukeVu
> build: commit android/ios updates for new plugin

- src/locales/en/en.json
- src/ui/components/ArchivedCredentials/ArchivedCredentials.test.tsx
- src/ui/components/CreateGroupIdentifier/components/SetupConnections.test.tsx
- src/ui/components/CreatePasscodeModule/CreatePasscodeModule.test.tsx
- src/ui/components/CreatePasscodeModule/CreatePasscodeModule.tsx
- src/ui/components/CredentialDetailModule/CredentialDetailModule.test.tsx
- src/ui/components/ForgotAuthInfo/ForgotAuthInfo.test.tsx
- src/ui/components/IdentifierDetailModule/IdentifierDetailModule.test.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/Connections/Connections.test.tsx
- src/ui/pages/Credentials/Credentials.test.tsx
- src/ui/pages/Identifiers/Identifiers.test.tsx
- src/ui/pages/IncomingRequest/IncomingRequest.test.tsx
- src/ui/pages/LockPage/LockPage.test.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.test.tsx
- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/Settings/components/ChangePin/ChangePin.test.tsx
- src/ui/pages/Menu/components/Settings/components/ManagePassword/ManagePassword.test.tsx
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/RecoverySeedPhrase.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential/ChooseCredential.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.test.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/MultiSigRequest.test.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.test.tsx
- src/ui/pages/SetPasscode/SetPasscode.test.tsx
- src/ui/utils/passcodeChecker.test.ts
- src/ui/utils/passcodeChecker.ts
- src/ui/utils/passcodeFiller.ts
Block sequential or repetitive passkey characters
---
https://github.com/user-attachments/assets/14f0a89c-0eef-4528-8747-9a005e7b33d6
https://github.com/user-attachments/assets/d2df4b75-80fb-4504-ad9d-89c6b740e418
> feat(ui): block sequential or repetitive passkey characters

- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
Passcode prompt in notification removal
---
https://github.com/user-attachments/assets/a7ff76fb-6f1b-4e3b-a43d-b32bd2179eb8
> fix(ui): Passcode prompt in notification removal

- capacitor.config.ts
- src/ui/components/SeedPhraseModule/SeedPhraseModule.tsx
- src/ui/hooks/privacyScreenHook.test.tsx
- src/ui/hooks/privacyScreenHook.ts
- src/ui/pages/LockPage/LockPage.tsx
- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/Settings/Settings.tsx
Blocking recording of the entire app 
---
https://github.com/user-attachments/assets/1c23967f-5940-4491-825e-3101c508860a
https://github.com/user-attachments/assets/22c53061-258e-4c5d-b0a9-caabf5d2a7fe
> fix(ui): prevent record and capture screen on all app

- README.md
- configs/remote.yaml
Migration to our K8s dev sandbox. Every merge to main that has changes to KERIA/cred tool etc will deploy changes automatically with a short delay.
> build: migrate to k8s dev

- src/locales/en/en.json
- src/ui/globals/constants.ts
- src/ui/pages/Menu/Menu.test.tsx
- src/ui/pages/Menu/Menu.tsx
Removing Chat and Crypto tiles from the Menu.
> fix(ui): Remove chat and crypto in release branch

- src/ui/components/Scanner/Scanner.tsx
- src/ui/pages/Scan/Scan.test.tsx
Fix UI broken in Verify your Recovery Phrase Popup in Scan Menu on Android.
---
https://github.com/user-attachments/assets/1aadda2a-d0c8-4f95-a97d-cc278ebeda63
> fix(ui): Android - UI broken in Verify your Recovery Phrase Popup in Scan Menu

- src/ui/components/CredentialDetailModule/components/CredentialContent.test.tsx
- src/ui/components/Scanner/Scanner.test.tsx
- src/ui/pages/VerifyRecoverySeedPhrase/VerifyRecoverySeedPhrase.test.tsx
> fix(ut): Unit tests failing in release branch

- .nsprc
- ios/App/Podfile.lock
- package-lock.json
Resolves https://security.snyk.io/vuln/SNYK-COCOAPODS-ZIPFOUNDATION-5876636
Also resolve/update some NPM vulnerabilities.
> build: dependency updates/nsprc changes

- android/.idea/misc.xml
- android/app/capacitor.build.gradle
- android/capacitor.settings.gradle
- ios/App/Podfile
- ios/App/Podfile.lock
- package-lock.json
- package.json
- src/ui/components/AppWrapper/AppWrapper.tsx
See https://ionic.io/docs/tutorials/mobile-security/tap-jacking
> feat: tap jacking protection

- src/locales/en/en.json
- src/ui/globals/constants.ts
- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/Settings/Settings.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.test.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.tsx
Update the support link to direct users to the new support system
---
https://github.com/user-attachments/assets/08b29e45-17c6-4079-bb70-79dcda2a0dee
> feat(ui): FE: Support URL

- src/locales/en/en.json
- src/ui/components/TermsModal/TermsModal.scss
- src/ui/components/TermsModal/TermsModal.tsx
- src/ui/components/TermsModal/TermsModal.types.ts
- src/ui/globals/constants.ts
Update Privacy policy
---
https://github.com/user-attachments/assets/fedae547-9129-4a23-9c45-565e15b32e5f
> feat(ui): Update Privacy policy - Veridian Wallet

- Earthfile
- services/cip45-sample-dapp/package-lock.json
- services/cip45-sample-dapp/package.json
- services/credential-server-ui/package-lock.json
- services/credential-server/README.md
- services/credential-server/package-lock.json
- services/credential-server/package.json
Fixed the `setuptools` issue with KERIA again. Also fixed a number of npm audit issues as I want to close the Dependabot issues on Github.
The remaining chunk of ones are from the old credential UI, so those will go away when we delete it.
> build: working keria build 

- package-lock.json
- package.json
Upgrade @jimcase/capacitor-exit-app with CI CD pipeline for build and publish
---
> build: upgrade @jimcase/capacitor-exit-app with ci cd build

- services/credential-server-ui/src/const/index.ts
- services/credential-server-ui/src/locales/en/en.json
- services/credential-server-ui/src/pages/ConnectionDetail/CredentialTable.tsx
- services/credential-server-ui/src/pages/Credentials/Credential.types.ts
- services/credential-server-ui/src/pages/Credentials/Credentials.tsx
Implement credential list template
---
https://github.com/user-attachments/assets/5f755a8b-e72c-4c8f-a573-69e4737dd762
> feat(cred-ui): [credentials] Issuer: Credential List - Frontend

- src/locales/en/en.json
- src/ui/components/TermsModal/TermsModal.tsx
- src/ui/globals/constants.ts
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
- src/ui/pages/Menu/components/Settings/Settings.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.tsx
- src/ui/utils/openBrowserLink.ts
Updates to links + mailto: support@veridian.id
---
https://github.com/user-attachments/assets/37d870be-3ed6-445e-a4a0-b2f8397a3cc6
https://github.com/user-attachments/assets/90987126-17ab-48b8-8608-66cb3f62a1ca
> feat(ui): Updates to links + mailto: support@veridian.id

- src/ui/globals/constants.ts
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.tsx
Ticket was incorrect for last PR; we cannot bring back the support URL. We should be using the Discord link for the Discord text.
> fix(ui): remove support URL and 

- src/locales/en/en.json
> fix(ui): Update privacy policy

- services/credential-server-ui/src/components/AppTable/useTable.ts
- services/credential-server-ui/src/components/IssueCredentialModal/InputAttribute.tsx
- services/credential-server-ui/src/components/IssueCredentialModal/IssueCredentialModal.scss
- services/credential-server-ui/src/components/IssueCredentialModal/IssueCredentialModal.tsx
- services/credential-server-ui/src/components/IssueCredentialModal/IssueCredentialModal.types.ts
- services/credential-server-ui/src/components/IssueCredentialModal/Review.tsx
- services/credential-server-ui/src/components/IssueCredentialModal/SelectConnectionStage.tsx
- services/credential-server-ui/src/components/IssueCredentialModal/helper.ts
- services/credential-server-ui/src/components/IssueCredentialModal/index.ts
- services/credential-server-ui/src/components/PopupModal/PopupModal.tsx
- services/credential-server-ui/src/const/index.ts
- services/credential-server-ui/src/locales/en/en.json
- services/credential-server-ui/src/pages/ConnectionDetails/CredentialsTable.tsx
- services/credential-server-ui/src/pages/Connections/components/ConnectionsTable/ConnectionsTable.tsx
- services/credential-server-ui/src/pages/CredentialDetails/CredentialDetails.tsx
- services/credential-server-ui/src/pages/CredentialDetails/CredentialDetails.types.ts
- services/credential-server-ui/src/pages/CredentialDetails/CredentialsTable.tsx
- services/credential-server-ui/src/pages/Credentials/Credentials.tsx
- services/credential-server-ui/src/services/credential.ts
- services/credential-server-ui/src/services/credential.types.ts
Issue cred modal
---
https://github.com/user-attachments/assets/ceabca10-6501-4f3b-86a5-632b4193b9b7
> feat(cred-ui): [credentials] Issue

- services/credential-server-ui/src/locales/en/en.json
- services/credential-server-ui/src/pages/ConnectionDetails/ConnectionContactCard.tsx
- services/credential-server-ui/src/pages/ConnectionDetails/ConnectionDetails.scss
- services/credential-server-ui/src/pages/Connections/components/ConnectionsTable/ConnectionsTable.tsx
> feat(ui): add oobi for connection

- services/credential-server/package.json
- services/credential-server/src/modules/signify/signifyApi.ts
- services/credential-server/src/utils/response.util.ts
- services/credential-server/src/utils/utils.ts
We currently have no way to retrieve connection creation date & time, so need to store / send it
> feat: add date time to connections

- services/credential-server-ui/src/components/AppTable/AppTable.scss
- services/credential-server-ui/src/pages/ConnectionDetails/ConnectionContactCard.tsx
- services/credential-server-ui/src/pages/ConnectionDetails/ConnectionDetails.scss
- services/credential-server-ui/src/pages/ConnectionDetails/ConnectionDetails.tsx
- services/credential-server-ui/src/pages/ConnectionDetails/CredentialsTable.tsx
- services/credential-server-ui/src/pages/Connections/Connections.scss
- services/credential-server-ui/src/pages/CredentialDetails/CredentialDetails.scss
- services/credential-server-ui/src/utils/dateFormatter.ts
Add navigation link from the Connection details page / selecting view template / to the template page.
Also adding:
- Some style fixes (ellipsis for long names - some changes to adapt to tablet view)
- Some changes to the date formatter because the time isn't supposed to show up everywhere
https://github.com/user-attachments/assets/82b7f6d9-a4fb-4b3d-ab4f-57e072d4e2bc
**Here's some before and after (not all of them)**
> feat(cred-ui): Connections navigation of view template to credential template page

- services/credential-server-ui/src/components/IssueCredentialModal/IssueCredListTemplate.tsx
- services/credential-server-ui/src/components/IssueCredentialModal/IssueCredentialModal.tsx
- services/credential-server-ui/src/components/IssueCredentialModal/IssueCredentialModal.types.ts
- services/credential-server-ui/src/locales/en/en.json
- services/credential-server-ui/src/pages/ConnectionDetails/ConnectionContactCard.tsx
- services/credential-server-ui/src/pages/ConnectionDetails/ConnectionDetails.tsx
- services/credential-server-ui/src/pages/ConnectionDetails/CredentialsTable.tsx
- services/credential-server-ui/src/pages/Connections/components/ConnectionsTable/ConnectionsTable.tsx
- services/credential-server-ui/src/pages/CredentialDetails/CredentialDetails.tsx
- services/credential-server-ui/src/pages/CredentialDetails/CredentialsTable.tsx
- services/credential-server-ui/src/pages/Credentials/Credentials.tsx
- services/credential-server-ui/src/pages/RequestPresentation/IssueCredentialModal/helper.ts
- services/credential-server-ui/src/utils/toast.ts
Implement issue cred feature for:
- Connection Details
- Credentials 
---
https://github.com/user-attachments/assets/a6ff7a63-c79a-408e-8822-76d0e2ece3bf
https://github.com/user-attachments/assets/3f38c882-901c-4fe4-8894-92772d9d980b
https://github.com/user-attachments/assets/c85e2b9a-e297-4eb0-a76c-71c446364f7b
> feat(cred-ui): [credentials] Issuer: Issue credential - frontend

- services/credential-server-ui/src/App.tsx
- services/credential-server-ui/src/components/NavBar/NavBar.scss
- services/credential-server-ui/src/components/NavBar/NavBar.tsx
- services/credential-server-ui/src/components/NavBar/components/DrawerContent/DrawerContent.tsx
- services/credential-server-ui/src/components/NavBar/helper.ts
- services/credential-server-ui/src/const/route.ts
- services/credential-server-ui/src/locales/en/en.json
- services/credential-server-ui/src/pages/RequestPresentation/RequestPresentation.scss
- services/credential-server-ui/src/pages/RequestPresentation/RequestPresentation.tsx
- services/credential-server-ui/src/pages/RequestPresentation/RequestPresentationModal/InputAttribute.tsx
- services/credential-server-ui/src/pages/RequestPresentation/RequestPresentationModal/RequestPresentationModal.scss
- services/credential-server-ui/src/pages/RequestPresentation/RequestPresentationModal/RequestPresentationModal.tsx
- services/credential-server-ui/src/pages/RequestPresentation/RequestPresentationModal/RequestPresentationModal.types.ts
- services/credential-server-ui/src/pages/RequestPresentation/RequestPresentationModal/Review.tsx
- services/credential-server-ui/src/pages/RequestPresentation/RequestPresentationModal/SelectList.tsx
- services/credential-server-ui/src/pages/RequestPresentation/RequestPresentationModal/index.ts
- services/credential-server-ui/src/pages/RequestPresentation/index.ts
- services/credential-server-ui/src/services/credential.ts
- services/credential-server-ui/src/store/reducers/connectionsSlice.ts
- services/credential-server-ui/src/store/reducers/connectionsSlice.types.ts
Implement credential request page
---
https://github.com/user-attachments/assets/80b7e93a-0587-4b3e-b403-ee9ec58c3c7d
> feat(cred-ui): Build request page

- .nsprc
- Earthfile
- README.md
> build: bump keria version

- src/ui/App.scss
- src/ui/components/PageFooter/PageFooter.tsx
- src/ui/components/PageFooter/PageFooter.types.ts
- src/ui/components/SidePage/SidePage.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.scss
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/MultiSigRequest.scss
- src/ui/pages/NotificationDetails/components/MultiSigRequest/MultiSigRequest.test.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/MultiSigRequest.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.scss
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.test.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
- src/ui/pages/WalletConnect/WalletConnect.test.tsx
- src/ui/pages/WalletConnect/WalletConnectStageOne.tsx
Create a new button in PageFooter for declining action
---
> feat(ui): Create a new button in PageFooter for declining action

- src/ui/components/Scanner/Scanner.tsx
Fix scanner not detecting QR after scan invalid value.
---
https://github.com/user-attachments/assets/7a3b0cca-d03c-45ae-87fb-0985eebba2da
> fix(ui): Scanner not detecting QR

- services/credential-server-ui/src/components/AppTable/useTable.ts
- services/credential-server-ui/src/pages/ConnectionDetails/ConnectionContactCard.tsx
- services/credential-server-ui/src/pages/Connections/components/ConnectionsTable/ConnectionsTable.types.ts
- services/credential-server-ui/src/pages/Connections/components/ConnectionsTable/helpers.ts
Update Connection Date & Time EP in Frontend
---
> feat(cred-ui): [Cred Issuance Tool] Update Connection Date & Time EP in Frontend

- src/locales/en/en.json
- src/ui/pages/Notifications/Notifications.test.tsx
- src/ui/pages/Notifications/Notifications.tsx
Show alert when unknown request connection
---
https://github.com/user-attachments/assets/d60933a1-8dc6-4333-b659-414c0affcb2e
> feat(ui): Unknown connection credential handling 

- package.json
- tests/features/menu/menu-profile.feature
- tests/screen-objects/menu/menu-edit-profile.screen.ts
- tests/screen-objects/menu/menu-profile.screen.ts
- tests/screen-objects/menu/menu.screen.ts
- tests/steps-definitions/menu/menu-edit-profile.step.ts
- tests/steps-definitions/menu/menu-profile.step.ts
- tests/steps-definitions/menu/menu.steps.ts
> finish DTIS-2123

- package.json
- tests/features/menu/menu-profile.feature
- tests/screen-objects/menu/menu-edit-profile.screen.ts
- tests/screen-objects/menu/menu-profile.screen.ts
- tests/screen-objects/menu/menu.screen.ts
- tests/steps-definitions/menu/menu-edit-profile.step.ts
- tests/steps-definitions/menu/menu-profile.step.ts
- tests/steps-definitions/menu/menu.steps.ts
Implement 
C387 MenuProfile - Loads 
C388 MenuProfile - Cancel editing	
C389 MenuProfile - Confirm edit
> QA - automation for menu-profile.feature

- services/credential-server/src/apis/contact.api.ts
- services/credential-server/src/apis/credential.api.ts
- services/credential-server/src/apis/invitation.api.ts
- services/credential-server/src/apis/oobi.api.ts
- services/credential-server/src/apis/ping.api.ts
- services/credential-server/src/apis/shorten.api.ts
- services/credential-server/src/types/response.type.ts
- services/credential-server/src/utils/response.util.ts
Simplify response handling by removing ResponseData interface and httpResponse utility
[DTIS-1677]: https://cardanofoundation.atlassian.net/browse/DTIS-1677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> refactor(cred-server): simplify response handling

- .eslintrc.json
- src/core/agent/agent.types.ts
- src/locales/en/en.json
- src/ui/pages/NotificationDetails/NotificationDetails.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential/ChooseCredential.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential/ChooseCredential.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.scss
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignConfirmation/RemoteSignConfirmation.scss
- src/ui/pages/NotificationDetails/components/RemoteSignConfirmation/RemoteSignConfirmation.test.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignConfirmation/RemoteSignConfirmation.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignConfirmation/index.ts
- src/ui/pages/Notifications/NotificationItem.tsx
---
https://github.com/user-attachments/assets/5cd35c8d-e96e-48f6-ad95-a6081bed0f1c
https://github.com/user-attachments/assets/a1c13c70-7ff8-452f-be02-f6b384e82d4e
https://github.com/user-attachments/assets/8578c43b-67d0-4fca-b2a1-78a00f6411e7
https://github.com/user-attachments/assets/f3995120-ad88-416d-a73c-96540a9f074f
> feat(ui): Add Notification message type: Link

- package-lock.json
- package.json
Including the last visual bug fixes.
> build: version 1.0.1

- src/locales/en/en.json
Update 2 toast messages after identifier creation as discussed in [this thread](https://cardanofoundation.slack.com/archives/C07EQ1MV3GT/p1743694271749499).
---
https://github.com/user-attachments/assets/352d070d-a712-4124-94e6-ca4fa0ac3261
https://github.com/user-attachments/assets/060cea1d-80e3-44ba-b76b-f632d09aac16
> fix: language file

- .eslintrc.json
- Earthfile
- docker-compose.yaml
- package-lock.json
- package.json
- src/core/__fixtures__/agent/identifierFixtures.ts
- src/core/agent/agent.ts
- src/core/agent/agent.types.ts
- src/core/agent/records/connectionRecord.ts
- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
- src/core/agent/services/connectionService.types.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
- src/locales/en/en.json
- src/ui/components/InputRequest/InputRequest.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/pages/NotificationDetails/NotificationDetails.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential/ChooseCredential.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential/ChooseCredential.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.scss
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignConfirmation/RemoteSignConfirmation.scss
- src/ui/pages/NotificationDetails/components/RemoteSignConfirmation/RemoteSignConfirmation.test.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignConfirmation/RemoteSignConfirmation.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignConfirmation/index.ts
- src/ui/pages/Notifications/NotificationItem.tsx
> get latest code back to local branch

- src/ui/components/CustomToast/CustomToast.scss
- src/ui/styles/colors.scss
Create variable for toast message to support custom toast background colour that use in this repo: https://github.com/cardano-foundation/undp-veridian-wallet/pull/2
> feat(ui): [White labeled UX] Apply Custom Color  scheme - done in backend

- src/core/agent/agent.types.ts
- src/locales/en/en.json
- src/ui/pages/NotificationDetails/NotificationDetails.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignInformation/RemoteSignConfirmation.test.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignInformation/RemoteSignInformation.scss
- src/ui/pages/NotificationDetails/components/RemoteSignInformation/RemoteSignInformation.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignInformation/index.ts
- src/ui/pages/Notifications/NotificationItem.tsx
Generic notification that leads to a screen with a scan CTA
---
https://github.com/user-attachments/assets/fe9c24bb-9cda-4d96-94ff-d7d181e6f245
https://github.com/user-attachments/assets/4f64ecca-16dc-42de-beaf-f30be9e161ce
> feat(ui): Notification message type: Text only

- src/core/agent/agent.types.ts
- src/locales/en/en.json
- src/ui/App.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/globals/types.ts
- src/ui/pages/NotificationDetails/NotificationDetails.tsx
- src/ui/pages/NotificationDetails/components/RemoteConnectInstructions/RemoteConnectInstructions.scss
- src/ui/pages/NotificationDetails/components/RemoteConnectInstructions/RemoteConnectInstructions.test.tsx
- src/ui/pages/NotificationDetails/components/RemoteConnectInstructions/RemoteConnectInstructions.tsx
- src/ui/pages/NotificationDetails/components/RemoteConnectInstructions/index.ts
- src/ui/pages/Notifications/NotificationItem.tsx
Generic notification that leads to a screen with a scan CTA
---
https://github.com/user-attachments/assets/29d923f3-5a39-44df-b0f7-06b70ee99cae
https://github.com/user-attachments/assets/958180de-d669-497c-977d-3b3210e1df31
> feat(ui): Notification message type: Scan to connect

- package-lock.json
Webpack dev server vulnerabilities.
> build: audit fix

- services/credential-server-ui/src/pages/ConnectionDetails/CredentialsTable.tsx
- services/credential-server-ui/src/pages/Connections/components/ConnectionsTable/ConnectionsTable.tsx
- services/credential-server-ui/src/pages/CredentialDetails/CredentialsTable.tsx
- services/credential-server-ui/src/pages/RequestPresentation/RequestPresentation.tsx
- services/credential-server-ui/src/styles/main.scss
- services/credential-server-ui/src/utils/dateFormatter.ts
Adding tooltips to som of the elements in the tables to make ti easier for the user accessing all details.
https://github.com/user-attachments/assets/361e6634-84da-4258-b3ea-6b5075f55a5e
> feat(ui): Add tooltips on tables

- src/locales/en/en.json
- src/ui/pages/NotificationDetails/components/RemoteSignConfirmation/RemoteSignConfirmation.test.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignConfirmation/RemoteSignConfirmation.tsx
- src/ui/pages/Notifications/NotificationItem.tsx
Complete signing confirm message UI with real data.
Steps to get notification:
- run `docker compose up -d`
- Go to this branch of our fork: https://github.com/cardano-foundation/signify-ts/tree/build/v1.1
- Create a new examples/integration-scripts/remoteSigningConfirm.test.tsx file
- Flow:
- Create identifier in our wallet
- Use Signify-TS script to create an agent and a new identifier and OOBI
- Add the OOBI as a connection in the wallet on my branch
- Use a different Signify-TS script to use the same identifier to send a remote signing request
```
const hab = await client1.identifiers().get('alice');
const hab = await client1.identifiers().get('alice');
await client1.exchanges().send(
'alice',
'sign',
hab,
'/hmessage',
{
m: "Wow 2!",
t: "Title",
st: "Sub-title",
c: ["paragraph 1", …
```
> feat(ui): Complete human readable messaging UI with real data

- src/ui/pages/Connections/Connections.scss
- src/ui/pages/Connections/components/AlphabetSelector.tsx
- src/ui/pages/Connections/components/ConnectionsBody/ConnectionsBody.scss
Alphabet slider increase tap surface
---
https://github.com/user-attachments/assets/5809d331-efa9-4c71-8982-69b34610a086
https://github.com/user-attachments/assets/27ba3f4d-de4f-456d-9224-2089a40c3061
> feat(ui): Alphabet slider increase tap surface

- package-lock.json
- package.json
Upgrade library to fix errors when creating PR and running jobs
> Upgrade library

- src/core/agent/agent.types.ts
- src/core/configuration/configurationService.ts
- src/core/configuration/configurationService.types.ts
- src/store/reducers/identifiersCache/identifiersCache.ts
- src/store/reducers/identifiersCache/identifiersCache.types.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.test.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
Improve creating identifier flow. Now user can setting identifier type is individual and hidden type selection box when create identifier first time.
---
https://github.com/user-attachments/assets/836420e0-d249-42bd-bb34-bccf11fde470
> feat(ui): [White labeled UX] improvement: creating identifier flow

- tests/constants/text.constants.ts
- tests/steps-definitions/onboarding/passcode.steps.ts
- tests/steps-definitions/toolbar.steps.ts
automation for
fix the locator for menu settings passcode change
> fix the locator for menu settings passcode change

- tests/features/menu/menu-settings-support.feature
- tests/screen-objects/menu/menu-settings-support.screen.ts
- tests/screen-objects/menu/menu-settings.screen.ts
- tests/steps-definitions/menu/menu-settings-support.step.ts
automation for
Handle menu settings support screen
> automation for menu settings support screen

- src/ui/pages/LockPage/LockPage.tsx
Fix input cursor visible in passcode screen
---
https://github.com/user-attachments/assets/34770cff-2c71-4c76-923e-8a19bfc39bb1
> fix(ui): Input cursor visible in passcode screen

- services/credential-server/src/modules/signify/signifyApi.ts
- services/credential-server/src/utils/schemas.ts
Resolve all schema when cred server start.
---
> feat(cred-serv): Credential server schema list incomplete

- src/ui/components/CreateGroupIdentifier/CreateGroupIdentifier.scss
- src/ui/components/CreateGroupIdentifier/components/GroupMembers.tsx
- src/ui/components/CreateGroupIdentifier/components/SetupConnectionBodyResume.tsx
- src/ui/components/CreateGroupIdentifier/components/SetupThreshold.tsx
- src/ui/components/CreateGroupIdentifier/components/Summary.tsx
- src/ui/components/CredentialDetailModule/components/CredentialContent.tsx
- src/ui/components/CredentialDetailModule/components/CredentialContent.types.ts
- src/ui/components/IdentifierDetailModule/IdentifierDetailModal.tsx
- src/ui/components/IdentifierDetailModule/IdentifierDetailModule.tsx
- src/ui/components/InfoCard/InfoCard.scss
- src/ui/components/InfoCard/InfoCard.tsx
- src/ui/components/InfoCard/InfoCard.types.ts
- src/ui/components/RemovePendingAlert/RemovePendingAlert.scss
- src/ui/components/RemovePendingAlert/RemovePendingAlert.tsx
- src/ui/pages/LockPage/LockPage.tsx
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/RecoverySeedPhrase.scss
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/RecoverySeedPhrase.tsx
- src/ui/pages/Menu/components/SubMenu/SubMenu.scss
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential/ChooseCredential.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.scss
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
Improvements our app:
- Optimization re-render when open modal for Identifier and Credential Detail
- Update footer of Create Group Identifier UI use ionic suggest.
- Replace alert by common component `InfoCard`
- Fix bottom cut off on Seed Phrase UI and reload notification on when request group credential.
https://github.com/user-attachments/assets/2598647c-4c1f-4a62-a143-bed67a75cea9
https://github.com/user-attachments/assets/117ed50e-9cdb-4918-ac88-376175f92b2a
> feat(ui): Look for code improvements

- src/locales/en/en.json
- src/ui/pages/ProfileSetup/ProfileSetup.test.tsx
- src/ui/pages/ProfileSetup/ProfileSetup.tsx
- src/ui/pages/ProfileSetup/ProfileSetup.types.ts
- src/ui/pages/ProfileSetup/components/SetupGroup/SetupGroup.scss
- src/ui/pages/ProfileSetup/components/SetupGroup/SetupGroup.tsx
- src/ui/pages/ProfileSetup/components/SetupGroup/SetupGroup.types.ts
- src/ui/pages/ProfileSetup/components/SetupGroup/index.ts
- src/ui/pages/ProfileSetup/components/SetupProfileType/SetupProfileType.tsx
Setup group profile. 
https://github.com/user-attachments/assets/eaaa6785-6b51-4da4-bd39-4cf9996480dd
https://github.com/user-attachments/assets/53f45bbb-038a-43a8-a281-13a233d97300
https://github.com/user-attachments/assets/2b2de9ab-9e21-4b44-9b1e-15e9da38f07d
https://github.com/user-attachments/assets/e92cc72a-ffc0-4e47-bef5-7d187e35c32b
> feat(ui): UI - First profile setup: group

- src/locales/en/en.json
- src/routes/index.tsx
- src/routes/paths.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/Avatar/Avatar.scss
- src/ui/components/CustomToast/CustomToast.tsx
- src/ui/globals/types.ts
- src/ui/pages/Connections/Connections.test.tsx
- src/ui/pages/Connections/Connections.tsx
- src/ui/pages/Credentials/Credentials.test.tsx
- src/ui/pages/Credentials/Credentials.tsx
- src/ui/pages/Notifications/Notifications.test.tsx
- src/ui/pages/Notifications/Notifications.tsx
- src/ui/pages/Profiles/Profiles.scss
- src/ui/pages/Profiles/Profiles.test.tsx
- src/ui/pages/Profiles/Profiles.tsx
- src/ui/pages/Profiles/Profiles.types.ts
Please include a summary of the changes and a brief description about this PR.
https://github.com/user-attachments/assets/142e5725-6dcc-45d8-9b93-40f5589e595d
> feat(ui): Profiles page

- src/core/agent/agent.ts
- src/core/storage/sqliteStorage/migrations/index.ts
- src/core/storage/sqliteStorage/migrations/migrations.types.ts
- src/core/storage/sqliteStorage/sqliteSession.ts
Please include a summary of the changes and a brief description about this PR.
> feat(core): implement cloud migrations base

- package-lock.json
- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
We store the IPEX AGREE history items to track it's completion after deleting notifications, and filter it from the core. But the filter was never working correctly.
> fix(core): ipex agree connection history items not being filtered properly

- .github/workflows/docker-builds.yaml
It's tested already [here](https://github.com/cardano-foundation/veridian-wallet/actions/runs/16467493686/job/46548889867?pr=1280) and it works : D
> chore(gha): enable external prs to build docker images

- .github/workflows/docker-builds.yaml
- services/credential-server-ui/src/components/RequestPresentationModal/RequestPresentationModal.tsx
- services/credential-server-ui/src/services/credential.ts
- services/credential-server-ui/src/services/credential.types.ts
Fix issue credential UI not passing presentation attributes to server
https://github.com/user-attachments/assets/0e298447-bcdc-4cc0-b5e1-01f7f8c0bb16
[VT20-2011]: https://cardanofoundation.atlassian.net/browse/VT20-2011?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Credential UI not passing presentation attributes to server

- src/store/index.ts
- src/ui/pages/LockPage/LockPage.test.tsx
- src/ui/pages/LockPage/LockPage.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.test.tsx
- src/ui/pages/SetupBiometrics/SetupBiometrics.test.tsx
- src/ui/pages/SetupBiometrics/SetupBiometrics.tsx
If you don't remember your passcode and you don't have a seed phrase to help you recover your wallet, clicking on "Forgot passcode" will restart the onboarding process.
https://github.com/user-attachments/assets/d3d963ab-c620-488a-9123-3c1773b6de5d
> fix(ui): Broken "Forgot Passcode" button in Welcome Back screen

- package-lock.json
- package.json
> chore: fix npm ci after audit fix

- src/locales/en/en.json
- src/store/reducers/profileCache/profilesCache.ts
- src/store/reducers/stateCache/stateCache.test.ts
- src/store/reducers/stateCache/stateCache.types.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/Scan/hook/useScanHandle.ts
- src/ui/components/Scanner/Scanner.tsx
- src/ui/globals/types.ts
- src/ui/pages/ProfileSetup/ProfileSetup.test.tsx
- src/ui/pages/ProfileSetup/ProfileSetup.tsx
- src/ui/pages/ProfileSetup/components/GroupSetup/GroupSetup.tsx
- src/ui/pages/SetupGroupProfile/components/SetupConnections/SetupConnections.scss
- src/ui/pages/SetupGroupProfile/components/SetupConnections/SetupConnections.test.tsx
- src/ui/pages/SetupGroupProfile/components/SetupConnections/SetupConnections.tsx
Update group setup page, allow joiner can connect to another members as Joiner 
https://github.com/user-attachments/assets/83e778a1-b6b3-4225-9f55-30470dc0d600
> feat(ui): Group Profile Creation - Connect members as Joiner 

- .github/workflows/gh-verify-branch.yaml
- .github/workflows/gh-verify-pr.yaml
- src/locales/en/en.json
- src/ui/components/ConnectdApp/ConnectdApp.scss
- src/ui/components/ConnectdApp/ConnectdApp.tsx
- src/ui/globals/types.ts
Just renamed wallet connections and Cardano connections to dApp connections in order to align better with the new app structure. 
No functional changes were made, so I only tested on the browser since as far as I was told the current test environment on emulators is prone to bugs and may not fully represent the true experience.
https://github.com/user-attachments/assets/ba393fc2-322f-4432-b7cc-a9e19fed28cd
> chore(ui): Rename Cardano Connect references to dApps

- src/ui/components/AppWrapper/AppWrapper.tsx
Impossible to access the app when running the app from scratch on incognito window or after wiping the wallet on a regular window in the browser. 
App is accessible on the emulators and phones but not in the browser preview.
> fix(ui): NativeBiometric breaking app in browser preview

- src/ui/components/Scan/Scan.scss
- src/ui/components/Scan/Scan.test.tsx
- src/ui/components/Scan/Scan.tsx
- src/ui/components/ShareProfile/ShareProfile.test.tsx
- src/ui/pages/ProfileSetup/ProfileSetup.scss
- src/ui/pages/ProfileSetup/ProfileSetup.test.tsx
- src/ui/pages/Profiles/Profiles.test.tsx
- src/ui/pages/SetupGroupProfile/SetupGroupProfile.test.tsx
- src/ui/pages/SetupGroupProfile/components/SetupConnections/SetupConnections.scss
- src/ui/pages/SetupGroupProfile/components/SetupConnections/SetupConnections.test.tsx
After some recent refactoring, the Scan component is still using some old class names and test IDs. Updating the Scan component to make sure all class names and test IDs are aligned, allowing for more accurate development.
> chore(ui): Update base app to allow components reusability (Scan)

- src/ui/pages/NotificationDetails/NotificationDetails.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.tsx
- src/ui/pages/NotificationDetails/components/CredentialShareRequest/CredentialShareRequest.tsx
- src/ui/pages/Notifications/NotificationItem.tsx
- src/ui/pages/Notifications/Notifications.test.tsx
- src/ui/pages/Notifications/components/EarlierNotification.test.tsx
Please include a summary of the changes and a brief description about this PR.
https://github.com/user-attachments/assets/6e6c44f3-7438-4378-8e82-da99b39d71d5
> feat: update requester name and logo

- src/core/agent/services/ipexCommunicationService.ts
Updated new value of `IpexCommunicationService` for the social media access credential.
> fix(ui): Update social media access credential

- src/ui/components/CardDetails/CardDetailsItem/CardDetailsItem.tsx
- src/ui/pages/NotificationDetails/components/CredentialIssuanceRequest/CredentialIssuanceRequest.tsx
- src/ui/utils/formatters.ts
Changing how the time is formatted for parent and child to be the same and showing timezone.
> feat(ui): Align start and end date with local timezone for parent and child
