cardano-foundation/veridian-wallet

- ios/App/Podfile.lock
- src/ui/components/layout/TabLayout/TabLayout.scss
- src/ui/components/layout/TabLayout/TabLayout.tsx
- src/ui/pages/Connections/Connections.scss
- src/ui/pages/Connections/Connections.test.tsx
- src/ui/pages/Connections/Connections.tsx
- src/ui/pages/Connections/components/AlphabetSelector.tsx
- src/ui/pages/Connections/components/AlphabeticList.tsx
- src/ui/pages/Connections/components/ConnectionItem.tsx
Part of the main Standardise pages story, in this PR I am updating the Connections tab layout.
I have also found and fixed a bug related to the alphabetic menu being pushed up when the user clicks on the search bar and the keyboard shows up on the screen.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/119612231/262c7539-471e-4cbc-9912-582c243adb31
> feat(ui): Standardise pages - Connections tab layout

- src/ui/components/VerifyPasscode/VerifyPasscode.scss
- src/ui/components/VerifyPasscode/VerifyPasscode.tsx
Part of the larger standardisation story for modals, in this PR I have refactored the layout of the Verify Passcode modal making use of some components recently created and used in other PRs such as the `ResponsivePageLayout`, the `PasscodeModule` and the `PageFooter` in order to responsively render the aforementioned modal in a way that takes advantage of what I did in my PR for the Passcode login and the one for the Terms and conditions modal.
**Note:**
1) In the screenshots below I am showing what the user will see when a wrong passcode is entered in order to show all of the components in a single shot.
2) As we already agreed some time ago with Robert, the reason why the subtitle isn't visible in smaller devices is to save space (same as what happens in the login screen).
---
> fix(ui): Standardise Modals - Verify Passcode layout

- src/locales/en/en.json
- src/routes/nextRoute/nextRoute.ts
- src/routes/paths.ts
- src/ui/components/IdentifierThemeSelector/IdentifierThemeSelector.scss
- src/ui/components/IdentifierThemeSelector/IdentifierThemeSelector.tsx
- src/ui/components/PageHeader/PageHeader.tsx
- src/ui/components/PageHeader/PageHeader.types.ts
- src/ui/components/layout/PageLayout/PageLayout.tsx
- src/ui/components/layout/PageLayout/PageLayout.types.ts
- src/ui/components/layout/PageLayout/Pagelayout.test.tsx
- src/ui/components/layout/TabLayout/TabLayout.tsx
- src/ui/components/layout/TabLayout/TabLayout.types.ts
- src/ui/components/navigation/TabsMenu/TabsMenu.tsx
- src/ui/pages/Chat/Chat.tsx
- src/ui/pages/Connections/Connections.tsx
- src/ui/pages/CredCardDetails/CredCardDetails.tsx
- src/ui/pages/Creds/Creds.test.tsx
- src/ui/pages/Creds/Creds.tsx
- src/ui/pages/Crypto/index.ts
- src/ui/pages/Identifiers/Identifiers.test.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
- src/ui/pages/Menu/Menu.scss
- src/ui/pages/Menu/Menu.test.tsx
- src/ui/pages/Menu/Menu.tsx
- src/ui/pages/Menu/index.ts
As described in the ticket linked below, in this PR I have adjusted/replaced the menu options in the tab menu at the bottom of the screen, removing the old Crypto tab and replacing it with a new Menu tab, on which we will be able to access different menu sections (for now those sections aren't clickable).
As part of this PR we have also decided to remove the hamburger menu from everywhere in the app since we will now access all app settings through this new menu tab.
---
> feat(ui): Menu bar layout

- src/core/agent/modules/signify/signifyApi.test.ts
- src/core/agent/modules/signify/signifyApi.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
Allow for the creation of a delegated multi-sig identifier in the wallet
> feat(core): Delegated multi sig

- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.types.ts
- src/ui/components/CreateIdentifier/components/IdentifierStage0.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage2.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage3.tsx
No changes to the UI, everything still looks the same all the way until the user will see the toast message confirming a request was sent. In this PR I am just hooking up the request for the Multi-Sig creation as described in the ticket linked below.
**NOTE:**
1- `colors`: we don't need this anymore and it will need a dedicated ticket for being removed from everywhere across the app.
2- As a temporary solution, I am getting `ourIdentifier` by returning the first Keri identifier available in our wallet. This will need to be refined further and a dedicated identifier will need to be created under the hood without showing up in the app with the other ones (Fergal will help finding a solution for this).
> feat(ui): Multi-sig feature - Sending the Multi-Sig Request

- services/credential-issuance-server/package-lock.json
- services/credential-issuance-server/package.json
- services/credential-issuance-server/src/cli/multiSigIncept.ts
- services/credential-issuance-server/src/modules/signify/signifyApi.ts
- services/credential-issuance-server/src/modules/signify/utils.ts
- services/credential-issuance-server/tsconfig.json
- src/core/agent/modules/signify/signifyApi.test.ts
- src/core/agent/modules/signify/signifyApi.ts
- src/core/agent/modules/signify/signifyApi.types.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/identifierService.types.ts
- src/ui/components/IdentifierCardInfoKeri/IdentifierCardInfoKeri.tsx
This allows the UI to retrieve details about an incoming multi-sig inception notification event. It will return the connection short details for the other parties, separated by sender and "other" parties who are not you or the sender. It will also return the threshold and the identifier short details that we control (this will help organise the UI after accepting).
There are some comments on optimisations we can make once we have these features in and refactor.
I also added a cli command to the credential service package.json that will launch a CLI multi-sig inception with 2 other parties, Alice and Bob. This makes it a lot easier to test receiving an inception event. (this script can be improved for sure but is a decent first start)
- Does not have any elements that will affect …
> feat(core): interface to return multi-sig contact details for UI

- configs/dev-comm.yaml
- services/docker-compose.yaml
- services/external/keria-config/cf-backer-oobis.json
One from previous PR had a misconfigured OOBI, and would not generate a new one without losing the AID. This should be improved in the cardano-backer repo.
> build(core): working cardano-backer 2

- src/core/storage/secureStorage/secureStorage.test.ts
- src/core/storage/secureStorage/secureStorage.ts
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
Secure storage items (at least on on iOS) are persisted across installs (as they should be). But for dev purposes until we have a proper release we clear this so we can re-show onboarding and also reset the Signify bran in case there is a cloud tenant issue. So signify bran is also reset now.
> feat(core): reset signify-bran on re-install (dev)

- src/ui/components/TermsModal/TermsModal.scss
- src/ui/pages/CreatePassword/CreatePassword.scss
- src/ui/pages/GenerateSeedPhrase/GenerateSeedPhrase.scss
- src/ui/pages/SetPasscode/SetPasscode.scss
- src/ui/pages/VerifySeedPhrase/VerifySeedPhrase.scss
Fix header's background color on android devies
---
[DTIS-741]: https://cardanofoundation.atlassian.net/browse/DTIS-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): fix header background color on android devices

- services/credential-issuance-server/src/ariesAgent.ts
- src/core/agent/modules/signify/signifyApi.test.ts
- src/core/agent/modules/signify/signifyApi.ts
- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
If an OOBI we are resolving contains the `name` query parameter as in the [OOBI](https://github.com/WebOfTrust/ietf-oobi) spec, this will be used as the alias for that new KERI contact.
Likewise, we can also assign a name to OOBIs we generate for a KERI AID.
Finally, I also disabled deleting a contact from KERIA - I have a task on Jira to uncomment this, but this behaviour is broken in KERIA as far as I can tell and so lets just remove it for now.
> feat(core): support for OOBI aliases

- package-lock.json
- package.json
- src/ui/App.test.tsx
- src/ui/App.tsx
This PR fixed top status bar not visible on phone dark mode. I tried to identify the error on both `ios` and `android` and it seem this error only occur on `ios` (couldn't identify on android).
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/ae8bf98b-8eda-4f53-8b6a-9c7838898944
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/75329613-c5fe-4a90-9fe7-9ff5c897fb8d
This error occur on phone header status bar. So I don't record evidence for browser.
[DTIS-580]: https://cardanofoundation.atlassian.net/browse/DTIS-580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): phone top bar not visible

- src/ui/components/PageHeader/PageHeader.tsx
- src/ui/pages/SetPasscode/SetPasscode.test.tsx
- src/ui/pages/SetPasscode/SetPasscode.tsx
Fix navigate back from re-enter passcode issue.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/063c0821-0a11-4e8c-99f8-d937f8ae9800
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/ee6f310e-ce74-4faf-ac0b-7720ce7cb802
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/d8198a8a-5774-4184-a989-3b620541efc4
[DTIS-633]: https://cardanofoundation.atlassian.net/browse/DTIS-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(func): fix nav back issue on re-enter passcode screen

- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/components/Scanner/Scanner.types.ts
- src/ui/pages/Scan/Scan.tsx
This PR is fixing the bug that we noticed when deleting a freshly created connection.
While doing our investigation we noticed that this was only happening when the connection was being created by using the tab scanner instead of the one in the tab menu at the top. We went to the bottom of it and found that the issue was caused by the useEffect still running after we’ve redirected after the scan.
When we click the delete button, it changes `currentOperation` in Redux, which triggers this useEffect and does a history.push containing the `currentOperation` and `toastMsg`, overwriting the `history.location.state` from when we initially loaded the connection details page.
We came to the conclusion that the redirection should probably be handled by the scanner itself so that it redirects once …
> bugfix(ui): Cannot delete a connection without app reload

- src/ui/App.test.tsx
- src/ui/App.tsx
- src/ui/components/ArchivedCredentials/ArchivedCredentials.scss
- src/ui/components/ArchivedCredentials/ArchivedCredentials.test.tsx
- src/ui/components/ArchivedCredentials/ArchivedCredentials.tsx
- src/ui/components/ArchivedCredentials/ArchivedCredentials.types.ts
- src/ui/components/ArchivedCredentials/CredentialItem.tsx
- src/ui/components/CardsStack/CardsStack.test.tsx
- src/ui/components/IdentifierOptions/IdentifierOptions.tsx
- src/ui/components/VerifyPasscode/VerifyPasscode.tsx
- src/ui/components/VerifyPassword/VerifyPassword.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
- src/ui/pages/CredCardDetails/CredCardDetails.scss
- src/ui/pages/CredCardDetails/CredCardDetails.tsx
- src/ui/pages/CredCardDetails/components/CredContentAcdc.tsx
- src/ui/pages/Creds/Creds.tsx
- src/ui/pages/IdentifierCardDetails/IdentifierCardDetails.scss
- src/ui/pages/IdentifierCardDetails/IdentifierCardDetails.tsx
In this PR I fixed an error about restoring multiple credentials but only shows 1 extra in the list until app reload. 
The reason is we are update one by one item to redux store and the last one overwrites each of the previous ones.
Therefore I used bulk update instead update one by one item to redux store.
I also fixed comments:
=> Currently, we are adding/removing `ion-hide` class to hidden/display page after leave this page by using ion lifecycle hook `useIonViewDidEnter` and `useIonViewDidLeave`. 
But because ionic is saving the leaved page to stack and not destroy it after leave page, sometime when back page it make lifecycle hook `useIonViewDidEnter` not fired and it make `ion-hide` class not remove => page blank. I used router hook of ionic `useIonRouter` to navigate and destroy …
> fix(ui): restore multiple credentials

- services/credential-issuance-server/src/modules/signify/signifyApi.ts
- src/core/agent/services/connectionService.ts
We still have this "hack" in our wallet where we use a resolve OOBI endpoint on our test credential server to allow the server to find our wallet. Since we now have a name we can pass to this, this PR passes that through too.
It also updates the cred server to recognise the name/alias query parameter rather than defaulting to a UUID.
> feat(core): set name/alias when resolving via test credential server

- src/ui/components/CredentialOptions/CredentialOptions.tsx
- src/ui/components/IdentifierOptions/IdentifierOptions.tsx
- src/ui/components/IdentifierOptions/IdentifierOptions.types.ts
- src/ui/components/PageHeader/PageHeader.tsx
- src/ui/components/VerifyPasscode/VerifyPasscode.test.tsx
- src/ui/components/VerifyPasscode/VerifyPasscode.tsx
- src/ui/components/layout/PageLayout/Pagelayout.test.tsx
- src/ui/hooks/appIonRouterHook.ts
- src/ui/hooks/index.ts
- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
- src/ui/pages/CreatePassword/CreatePassword.tsx
- src/ui/pages/CredentialDetails/CredentialDetails.test.tsx
- src/ui/pages/CredentialDetails/CredentialDetails.tsx
- src/ui/pages/GenerateSeedPhrase/GenerateSeedPhrase.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.test.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.tsx
- src/ui/pages/Onboarding/Onboarding.test.tsx
- src/ui/pages/Onboarding/Onboarding.tsx
- src/ui/pages/PasscodeLogin/PasscodeLogin.test.tsx
- src/ui/pages/PasscodeLogin/PasscodeLogin.tsx
- src/ui/pages/SetPasscode/SetPasscode.test.tsx
- src/ui/pages/SetPasscode/SetPasscode.tsx
- src/ui/pages/VerifySeedPhrase/VerifySeedPhrase.test.tsx
- src/ui/pages/VerifySeedPhrase/VerifySeedPhrase.tsx
This PR to fix onboarding pages still display after completed. I think this issue same as https://github.com/cardano-foundation/cf-identity-wallet/pull/409 when `useIonDidLeave` and `useIonDidEnter` hooks not fired. And I removed onboarding pages on DOM after it completed by using ionic router. 
But I still keep current page on DOM to keep up the good performance if user back to previous page to do something and navigate to current page after it done (Actually, I wanna keep all onboarding pages and only remove it after verify seed page completed but unfortunately ionic router not support it).
Beside that, I also applied this action to another pages except some page is sending history state when navigation (ex: `/onboarding` page) because it seem ionic router not support sending history …
> fix(ui): remove onboarding page from DOM after completed

- src/ui/components/layout/PageLayout/PageLayout.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
- src/ui/pages/ConnectionDetails/components/ConnectionDetailsHeader.tsx
- src/ui/pages/ConnectionDetails/components/ConnectionNote.test.tsx
- src/ui/pages/ConnectionDetails/components/ConnectionNote.tsx
- src/ui/pages/ConnectionDetails/components/ConnectionNote.types.ts
- src/ui/pages/ConnectionDetails/components/EditConnectionsModal.scss
- src/ui/pages/ConnectionDetails/components/EditConnectionsModal.test.tsx
- src/ui/pages/ConnectionDetails/components/EditConnectionsModal.tsx
- src/ui/pages/ConnectionDetails/components/EditConnectionsModal.types.ts
Fix connection note content not update after save. It seem the issue occur because object reference. 
After we get data from core API, we push it in 2 states: `notes` and `coreNotes`. 
And when update note we only update note object (`title`, `message`) properties and not create new note object to break reference to old object => it also update object store in `coreNotes` (because they are same reference).  
And when we save change, We are comparing object in updated note list and `coreNotes` to find note need update. But because above issue => data in update note list is equal `coreNotes` => cannot find updated item => no change update to core by API.
Beside that, I found some bugs are note title length not update when we change note title, delete new note, open 2 edit note modal,... => …
> fix(ui): fix connection note content not update after save

- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
Fix navigate back from connection detail after delete it.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/33c1e506-a4a1-4685-b41e-afd35d3a2b59
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/6eda205c-a9ce-44a7-85ed-0d73f200d532
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/3e564a69-d37b-40b3-81b4-59f0fa322e6d
[DTIS-807]: https://cardanofoundation.atlassian.net/browse/DTIS-807?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): fix nav back after delete connection

- package-lock.json
- package.json
- src/ui/App.test.tsx
- src/ui/App.tsx
This PR use to lock phone screen orientation to portrait to make app responding to phone orientation
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/265343f2-e5e7-4156-b98c-c48693681b2e
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/6d9b20d2-f1d8-49df-9d15-2aeb4e873860
This feature only work on mobile phone app. I think we don't need evidence on browser.
[DTIS-581]: https://cardanofoundation.atlassian.net/browse/DTIS-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): app responding to phone orientation

- src/core/agent/agent.types.ts
- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
- src/ui/components/Scanner/Scanner.tsx
There was some bugs related to when connections were stored or not stored if the OOBI contains the multisig `groupId` query param. Now, a new connection is always stored for simplicity and in case we need this info in the future for non-initiators of multisigs.
The get all connections interface filters these out now but this should be refactored by Bao once he's back to do this in the SQL - I wasn't sure if I'd cause a regression by altering to allow filtering by `undefined` in the tags.
Worth noting that the sync all connections function won't be context aware when syncing if it the connection is a multi-sig member or a normal connection - this is a todo and low priority.
Also re-adjusted the query params of OOBIs. The change from Patrick was inserting `+` instead of `%20` for spaces …
> fix(core): always store multisig contact

- src/ui/components/AppWrapper/AppWrapper.tsx
In case we receive a multi-sig inception event, but don’t know all of the contacts yet - we should have a way of pushing a retrying.
[DTIS-740]: https://cardanofoundation.atlassian.net/browse/DTIS-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(core): retry mechanism for multisig missing contacts

- src/core/cardano/walletConnect/identityWalletConnect.ts
- src/core/cardano/walletConnect/peerConnection.ts
- src/core/cardano/walletConnect/peerConnection.types.ts
Adjust the start method to accept an identifier (KERI AID) which will be the selected identifier in getIdentifierOobi of identityWalletConnect.ts (right now it selects the first one)
> feat(core): adjust the start method in peerConnection to accept an identifier

- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
To avoid the warning in the UI and to reduce payload, we change the parameter of `getMultisigIcpDetails` to `notificationsSaid`.
> refactor(core): avoid serialisation warning for getting multi-sig icp details

- src/ui/pages/Menu/components/Settings/Settings.test.tsx
Remock test for Disable/enable biometrics toggle unit test
> test: Remock case enable/diable biometrics

- src/ui/components/PageHeader/PageHeader.scss
- src/ui/components/PageHeader/PageHeader.tsx
- src/ui/components/Scanner/Scanner.scss
- src/ui/components/VerifyPasscode/VerifyPasscode.scss
- src/ui/components/layout/ResponsivePageLayout/ResponsivePageLayout.scss
- src/ui/components/layout/TabLayout/TabLayout.scss
- src/ui/pages/LockPage/LockPage.scss
- src/ui/pages/SetPasscode/SetPasscode.scss
This PR used to update layout breakpoint for `ResponsivePageLayout` component to make it same as other layouts.
`ResponsivePageLayout` now is using by:
- VerifyPasscode
- WalletConnect
- FullPageScanner
- CredentialRequest
- LockPage
- Onboarding
- SetPasscode
- VerifySeedPhrase
- [x This PR has been tested/validated in IOS, Android and browser.
---
[DTIS-884]: https://cardanofoundation.atlassian.net/browse/DTIS-884?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> bugfix(ui): Breakpoints misalignment between layouts

- src/ui/pages/SidePage/components/IncomingRequest/components/MultiSigRequest.tsx
- src/ui/pages/SidePage/components/IncomingRequest/components/SignTransactionRequest.tsx
Hide 'Ignore' Button in user decision prompts (workaround until Notifications feature done)
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/d2396f89-1af6-4c60-81da-de289fbd8b53
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/d453e882-618c-40e7-80a2-7d9de0dcb21a
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/878ed96d-b15e-4f2b-9f90-cbe6e92a0f23
[DTIS-913]: https://cardanofoundation.atlassian.net/browse/DTIS-913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Hide 'Ignore' Button in user decision prompts (workaround until Notifications feature done)

- package-lock.json
- package.json
- src/ui/hooks/useBiometricsHook.ts
- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/Settings/Settings.tsx
This PR use to update missing logic of enable biometrics on setting page:
1. Add verify password/passcode, verify biometry when user enable biometric auth
2. Nav to setting page when biometry not enrolled
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/19c23ac4-9a42-47fc-8fc0-65b72a3b7b14
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/5ba75fad-a2c3-429e-a76c-359ee8157e45
[DTIS-914]: https://cardanofoundation.atlassian.net/browse/DTIS-914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Enable Biometrics with Password/Passcode Confirmation

- docker-compose.yaml
- services/docker-compose.yaml
Some compose installations don't require .git but appears others do.
> build: .git in compose files

- src/ui/components/SideSlider/SideSlider.test.tsx
- src/ui/components/SideSlider/SideSlider.tsx
- src/ui/components/SideSlider/SideSlider.types.ts
- src/ui/pages/SidePage/SidePage.test.tsx
- src/ui/pages/SidePage/SidePage.tsx
Refactor `SideSlider` component that used by `IncommingRequest` component to make sure incoming requests always overlay the rest of the app.
I provided new option for `SideSlider` is render as modal. Because some component maybe use alert or modal inside it ( ex: `WalletConnect` request will display alert when user decline) and if we fixed value of `zIndex` sometime it will overlay alert and modal of page content.
And because some component using `SideSlider` need render inside app tab (ex: Settings, Connect wallet) therefore I also keep old render method.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/15bcd9b5-c3d0-4d1b-b17a-5491eeb26240
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/4653f126-41e8-4aea-b94a-ec6813d7377a …
> feat(ui): Overlay IncomingRequest over the entire app

- src/ui/pages/SidePage/components/WalletConnect/WalletConnect.scss
- src/ui/pages/SidePage/components/WalletConnect/WalletConnect.tsx
- src/ui/pages/SidePage/components/WalletConnect/WalletConnectStageOne.tsx
Remove green tick animation when clicking `Connect` button wallet connect screen
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/b0e1bea9-dc05-451a-a720-352384b94821
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/b68ecbba-fe62-406a-bb1d-bad2c7caf90c
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/ef8aadaa-356e-4440-bf1e-bc22713cc0b8
[DTIS-950]: https://cardanofoundation.atlassian.net/browse/DTIS-950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Remove green tick animation when clicking Connect

- src/core/cardano/walletConnect/peerConnection.ts
- src/locales/en/en.json
- src/routes/backRoute/backRoute.test.ts
- src/routes/nextRoute/nextRoute.test.ts
- src/store/reducers/walletConnectionsCache/walletConnectionsCache.test.ts
- src/store/reducers/walletConnectionsCache/walletConnectionsCache.ts
- src/store/reducers/walletConnectionsCache/walletConnectionsCache.types.ts
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/CardList/CardList.scss
- src/ui/components/Scanner/Scanner.tsx
- src/ui/components/SideSlider/SideSlider.tsx
- src/ui/components/SideSlider/SideSlider.types.ts
- src/ui/globals/types.ts
- src/ui/pages/Menu/components/ConfirmConnectModal/ConfirmConnectModal.scss
- src/ui/pages/Menu/components/ConfirmConnectModal/ConfirmConnectModal.test.tsx
- src/ui/pages/Menu/components/ConfirmConnectModal/ConfirmConnectModal.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.scss
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.test.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.types.ts
- src/ui/pages/SidePage/SidePage.test.tsx
- src/ui/pages/SidePage/SidePage.tsx
- src/ui/pages/SidePage/components/IncomingRequest/IncomingRequest.tsx
- src/ui/pages/SidePage/components/WalletConnect/WalletConnect.test.tsx
- src/ui/pages/SidePage/components/WalletConnect/WalletConnect.tsx
- src/ui/pages/SidePage/components/WalletConnect/WalletConnectStageOne.tsx
- src/ui/pages/SidePage/components/WalletConnect/WalletConnectStageTwo.tsx
- src/ui/utils/formatters.test.ts
- src/ui/utils/formatters.ts
Auto open connection modal after create connect. Beside that, I also update new behaviour when user create or connect new connection, they must disconnect connected wallet.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/5ffc0094-ee4c-41db-9fb8-c52d645adf1c
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/2df26130-0877-4283-aca7-7b90427266c6
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/ebf95784-03ce-4274-ad9f-cf43ba75343e
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/fb41773e-5544-4422-84ed-1a2744cc45a8
[DTIS-952]: https://cardanofoundation.atlassian.net/browse/DTIS-952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Auto-open the modal for the connection

- android/app/capacitor.build.gradle
- android/capacitor.settings.gradle
- ios/App/Podfile
- ios/App/Podfile.lock
- package-lock.json
- package.json
- src/core/agent/agent.ts
- src/core/agent/services/identifierService.ts
- src/core/cardano/walletConnect/peerConnection.ts
- src/core/storage/preferences/preferencesStorage.ts
- src/core/storage/preferences/preferencesStorage.types.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/pages/SetPasscode/SetPasscode.test.tsx
- src/ui/pages/SetPasscode/SetPasscode.tsx
- Re-introduce preferences storage until we properly handle `APP_ALREADY_INIT` flag. Otherwise we break some existing deployments.
- Fix on identifier deletion to not require peer connect to be activated.
> End of sprint fixes

- src/core/storage/secureStorage/secureStorage.ts
- src/locales/en/en.json
- src/routes/backRoute/backRoute.test.ts
- src/routes/backRoute/backRoute.ts
- src/routes/index.tsx
- src/routes/nextRoute/nextRoute.test.ts
- src/routes/nextRoute/nextRoute.ts
- src/routes/paths.ts
- src/store/reducers/stateCache/stateCache.test.ts
- src/store/reducers/stateCache/stateCache.ts
- src/store/reducers/stateCache/stateCache.types.ts
- src/ui/App.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/SeedPhraseModule/SeedPhraseModule.scss
- src/ui/components/SeedPhraseModule/SeedPhraseModule.tsx
- src/ui/components/SeedPhraseModule/SeedPhraseModule.types.ts
- src/ui/pages/CreatePassword/CreatePassword.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.test.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
- src/ui/pages/Onboarding/Onboarding.tsx
- src/ui/pages/VerifyRecoverySeedPhrase/VerifyRecoverySeedPhrase.scss
- src/ui/pages/VerifyRecoverySeedPhrase/VerifyRecoverySeedPhrase.test.tsx
- src/ui/pages/VerifyRecoverySeedPhrase/VerifyRecoverySeedPhrase.tsx
- src/ui/pages/VerifyRecoverySeedPhrase/VerifyRecoverySeedPhrase.types.ts
- src/ui/pages/VerifyRecoverySeedPhrase/index.ts
- src/ui/pages/VerifySeedPhrase/VerifySeedPhrase.test.tsx
Implement recovery wallet flow when user click on `I already have a wallet` button.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/ce9a1452-cdcb-45f1-9aec-d2dc4ee3b7bd
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/dba74a4e-cc77-4e97-b1b3-e1f7193e3fad
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/e1e7975b-7006-469d-b10f-7900b0a5a850
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/3eec4c0d-8754-4d79-a7cf-0625487b58c2
[DTIS-898]: https://cardanofoundation.atlassian.net/browse/DTIS-898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): I already have a wallet

- .github/workflows/docker-builds.yaml
Not required to be pushed so often, and right now not directly used.
> ci(gha): stop docker builds on every push

- src/ui/pages/CreatePassword/CreatePassword.scss
- src/ui/pages/CreatePassword/CreatePassword.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.scss
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
Pin validate button to bottom of `Create SSI agent` page
- [] Added new Unit/Component testing (if relevant).
---
[DTIS-971]: https://cardanofoundation.atlassian.net/browse/DTIS-971?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): pin ssi agent validate button to bottom of page

- src/core/agent/agent.types.ts
- src/core/agent/records/notificationRecord.ts
- src/core/agent/services/credentialService.test.ts
- src/core/agent/services/credentialService.ts
- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
- src/core/agent/services/signifyNotificationService.test.ts
- src/core/agent/services/signifyNotificationService.ts
- src/ui/App.test.tsx
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/pages/SidePage/components/IncomingRequest/IncomingRequest.test.tsx
- src/ui/pages/SidePage/components/IncomingRequest/IncomingRequest.tsx
- src/ui/pages/SidePage/components/IncomingRequest/components/RequestComponent.test.tsx
- From now on, notifications from KERIA will go to a notifications section of the wallet, and not appear in the normal queue of notifications.
- The normal queue of notifications will only be for (at the moment) peer connect.
> feat(core): rework core notification flow

- src/core/storage/secureStorage/secureStorage.ts
- src/routes/backRoute/backRoute.test.ts
- src/routes/backRoute/backRoute.ts
- src/routes/index.tsx
- src/routes/nextRoute/nextRoute.test.ts
- src/routes/nextRoute/nextRoute.ts
- src/store/reducers/stateCache/stateCache.ts
- src/ui/App.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/navigation/TabsMenu/TabsMenu.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/CreatePassword/CreatePassword.tsx
- src/ui/pages/VerifySeedPhrase/VerifySeedPhrase.test.tsx
Fix the issue about display wrong screen after restart app on onboarding flow.
Beside that I also update logic of back button of onboarding flow, that I got from Robert: 
When in the onboarding flow and NOT having left the flow:
- Passcode - back to intro screens
- Passcode confirm - back to create passcode
- Password - back to create passcode
- Generate seed phrase - back to create password
- Verify seed phrase - back to generate seed phrase
- Enter SSI - back to generate seed phrase
When in the onboarding flow and having left the flow at various points:
- If the user leaves without having created a passcode they will land on the intro screens and will go through the flow as normal
- If the user leaves after having created a passcode they will need to enter their passcode to create a …
> fix(ui): The URL should not affect the onboarding flows initial page after app restart

- src/ui/components/AppWrapper/hooks/useActivityTimer.tsx
- src/ui/components/VerifyPasscode/VerifyPasscode.test.tsx
Fix UT: `It renders verify passcode when clicking on the big button` failed when placed on bottom.
I got an error `TypeError: remove is not a function` when move this test case to bottom. I tried skip this test case and `TypeError` continue occur on `Render passcode` test case. 
With version 6 of `@capacitor/app`, we cannot call `remove` function directly on plugin listener handle (https://github.com/ionic-team/capacitor/blob/main/core/src/web-plugin.ts#L58). (We also got warning when call `remove` function directly with version 5).
Therefore I guess this issue occur when we call `remove` function directly.
[DTIS-255]: https://cardanofoundation.atlassian.net/browse/DTIS-255?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): UI: Jest: Test fails when placed at the bottom

- src/core/agent/services/identifier.types.ts
- src/core/agent/services/identifierService.ts
- src/locales/en/en.json
- src/ui/pages/SidePage/components/WalletConnect/WalletConnectStageTwo.tsx
Filter the list of identifiers to show only single signature identifier when connect dApp on Cardano Connect screen. This PR do not change UI, therefore I only capture on web browser.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/60bffb66-fc2a-43dd-a59f-2bfbba35452e
[DTIS-977]: https://cardanofoundation.atlassian.net/browse/DTIS-977?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Only show single sig identifiers in Cardano Connect

- jest.config.ts
- services/credential-server-ui/src/App.test.tsx
In the previous merge from this [PR](https://github.com/cardano-foundation/cf-identity-wallet/commit/7e3854295d1ceaa1f93b1794bd94e08c3954aa95) I included a test that it's not relevant and it's making tests fail. In this PR that test has been removed since it's not necessary. Additionally the `credential-server-ui` has been included in the ignored patterns in the jest configuration file.
> fix: removed from test credential server UI

- src/core/agent/agent.types.ts
- src/core/storage/secureStorage/secureStorage.ts
- src/routes/backRoute/backRoute.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.test.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
- src/ui/pages/Menu/components/Settings/Settings.scss
- src/ui/pages/Menu/components/Settings/Settings.tsx
- src/ui/pages/Onboarding/Onboarding.tsx
As requested in [this comment](https://github.com/cardano-foundation/cf-identity-wallet/pull/527#discussion_r1662391800), this PR use to move RECOVERY_WALLET to the Basic storage.
Because this PR not update anything about UI, therefore I just capture evidence on browser
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/ac563ee3-c675-4a56-8f81-ba4fe219568c
[DTIS-1004]: https://cardanofoundation.atlassian.net/browse/DTIS-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): UI: Update secure storage

- src/routes/index.tsx
https://github.com/cardano-foundation/cf-identity-wallet/pull/535/files seems to have broken some things. We will be changing the onboarding routing again based on a discussion this morning, so for now this fixes the issue where when you try to load the identifier details, it fails as `params.id` is `undefined`.
> fix(ui): correct params.id for identifier details screen

- src/core/agent/agent.types.ts
- src/core/agent/services/connectionService.ts
- src/locales/en/en.json
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage0.tsx
- src/ui/components/Scanner/Scanner.test.tsx
- src/ui/components/Scanner/Scanner.tsx
- src/ui/globals/types.ts
- src/ui/pages/Connections/Connections.tsx
Fix an issue about display wrong message when scanning a QR to join multi-sign identifier. I added new flag on resolve oobi event to know this event has been dispatched by scan multi-sign data. It seem dev server has issue and I can't test on emulator now, therefore I only capture evidence on browser.
---
https://github.com/cardano-foundation/cf-identity-wallet/assets/162310763/101cbed4-0702-4649-be51-f29f44584cd2
[DTIS-813]: https://cardanofoundation.atlassian.net/browse/DTIS-813?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Unable to show the correct toast message when scanning a QR to join a Multi-Sig

- README.md
This PR just add the `make init` that is required to configure the git hooks that will check for conventional commits :)
> doc(README): add 'make init' requirement

- .github/workflows/gh-vercel-branch-deploys.yaml
- .github/workflows/gh-vercel-pr-deploys.yaml
Instead of `[arc-runner-set]` which is currently down.
> build(gha): hosted runners

- src/ui/components/Scanner/Scanner.tsx
- src/ui/components/Scanner/Scanner.types.ts
- src/ui/pages/Scan/Scan.test.tsx
- src/ui/pages/Scan/Scan.tsx
Fix an issue about camera is still active in the background after scanning. 
Sometime, after we close `Share identifier` and nav to `Identifiers` tab, `useIonViewWillEnter` hook of  `Identifiers` tab not triggered and `routes` value on redux store not updated. 
It make active camera condition is `true` (`routePath === TabsRoutePath.SCAN`) and trigger `startScan` function.
---
https://github.com/user-attachments/assets/517b6948-e99f-4eb5-b653-b849ff8c9ad0
https://github.com/user-attachments/assets/ee5897b1-6210-44d0-95ff-3639dc7a58da
[DTIS-1013]: https://cardanofoundation.atlassian.net/browse/DTIS-1013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): fix background issue after join multi sign

- src/ui/__fixtures__/filteredIdentifierFix.ts
- src/ui/__fixtures__/identifierFix.ts
- src/ui/components/CardSlider/CardSlider.test.tsx
- src/ui/components/IdentifierOptions/IdentifierOptions.test.tsx
- src/ui/components/IdentifierOptions/IdentifierOptions.tsx
- src/ui/pages/IdentifierDetails/IdentifierDetails.test.tsx
- src/ui/pages/IdentifierDetails/components/IdentifierContent.tsx
In this PR we are not adding anything new to the UI, therefore I won't be testing it on all the emulators as usual. This is a  bugfix for hiding the button and the menu option for rotating the keys when the identifier is managed my a multi sig, since this requirement wasn't specified in the original Acceptance Criteria as discussed [here](https://cardanofoundation.slack.com/archives/C04DUEK6B25/p1720617663980479).
In the video below you can see how this button shows up when I open a single signer AID, while this will be hidden when opening a multi sig, both in the page and in the options modal.
---
https://github.com/user-attachments/assets/2c2c3a04-6fe6-400b-aa33-0c084f9dab24
> fix: remove button for multi sigs

- src/core/agent/records/connectionNoteRecord.ts
These were being pulled when you fetch the list of connections as they had the same type (regression during refactoring).
> fix(core): correct record type for connection notes

- src/core/agent/records/credentialStorage.ts
- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
> feat(core): archived or deleted credentials should not be presentable

- src/ui/pages/SidePage/components/WalletConnect/WalletConnectStageTwo.tsx
Every time that a new connection was stablished using Cardano Connect a toast with the text `unable to connect` was showing up even if the connection was successfully stablished a few seconds later. This PR prevents this from happening.
> fix(ui): prevent unable to connect toast to show with every conection

- src/core/cardano/walletConnect/peerConnection.ts
@rcmorano has updated the CF's bittorrent tracker host and IP to reduce the discovery time for a new connection when using CIP-45 in Cardano Connect. In this PR I have updated the url that we were previously using with the new one.
> chore(core): Updated CF's bittorrent tracker url

- src/ui/App.tsx
- src/ui/components/PageHeader/PageHeader.tsx
- src/ui/components/PageHeader/PageHeader.types.ts
- src/ui/components/layout/TabLayout/TabLayout.tsx
- src/ui/hooks/swipeBackHook.ts
- src/ui/hooks/useIonHardwareBackButton.ts
- src/ui/pages/Connections/Connections.tsx
- src/ui/utils/swipeback.ts
Disable swipe back action on IOS to fix an issue about render blank page after swipe back.
I tested on android and swipe working well (same as hardware back button):
https://github.com/user-attachments/assets/9c434c4a-c8fe-40f5-8c06-b20df2bce731
---
https://github.com/user-attachments/assets/7a7b7f0a-6f4d-4e4a-956c-2c003a6efba2
https://github.com/user-attachments/assets/b2cfd0a7-fe19-40a2-9c26-8049592e83c9
[DTIS-978]: https://cardanofoundation.atlassian.net/browse/DTIS-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Disable back button swipe where it's breaking things

- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.tsx
If the currently connected dApp is completely deleted, we shouldn’t be warned about breaking the connection.
> fix(ui): disconnect dapp before deleting dapp record

- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.test.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.tsx
There is a dialog we show if we have no identifiers at all, but it should be shown if we don’t have any default identifiers since this is all we can use to vote.
> fix(ui): prevent connect wallet when we only have multisig identifiers

- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
Fixing bug that will allow to map and display all history events in a connection page.
Only taking screenshot in the browser to show that it's working as I am not really adding anything new to the UI.
---
> fix(ui): Only one connection history item is shown in the UI

- src/locales/en/en.json
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.scss
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.test.tsx
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.tsx
Adding link to our Discord channel on the error page when a multi sig participant has forgotten to scan someone in their group.
---
https://github.com/user-attachments/assets/91d4c9cf-ee5a-4af7-863c-cd1853f98680
https://github.com/user-attachments/assets/6a6dca2a-3e5f-48c4-ae12-58fe5ba9f5a7
https://github.com/user-attachments/assets/8c13c999-9a67-479f-9822-74b36b750692
> feat(ui): Help center contacts missing

- src/ui/components/ArchivedCredentials/ArchivedCredentials.tsx
- src/ui/pages/CredentialDetails/CredentialDetails.tsx
- src/ui/pages/Credentials/Credentials.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCrendential.test.tsx
Fix credential animation cut off when credential received too fast
---
https://github.com/user-attachments/assets/02664ac4-e6ce-41b1-8cff-230b86ea9bd8
https://github.com/user-attachments/assets/6b5da1a2-af47-4446-810f-d07471a4bee3
[DTIS-1168]: https://cardanofoundation.atlassian.net/browse/DTIS-1168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Credential animation cut off when credential received too fast

- src/core/agent/records/credentialMetadataRecord.test.ts
- src/core/agent/records/credentialMetadataRecord.ts
- src/core/agent/records/credentialMetadataRecord.types.ts
- src/core/agent/records/credentialStorage.test.ts
- src/core/agent/services/credentialService.test.ts
- src/core/agent/services/credentialService.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/utils.ts
- src/store/reducers/credsArchivedCache/credsArchivedCache.test.ts
- src/store/reducers/credsCache/credsCache.test.ts
- src/ui/__fixtures__/credsFix.ts
- src/ui/__fixtures__/filteredCredsFix.ts
- src/ui/__fixtures__/shortCredsFix.ts
- src/ui/components/CredentialCardTemplate/CredentialCardTemplate.tsx
Expose schema of a credential in short details
> feat(core): expose schema of a credential in short details

- README.md
URL for deployments against the default KERIA URL for Vercel and mobile deployments.
Soon, these will all move to our K8s setup.
> docs(readme): update cred server URL

- src/core/storage/sqliteStorage/migrations/index.ts
- src/core/storage/sqliteStorage/migrations/migrations.types.ts
- src/core/storage/sqliteStorage/migrations/v0.0.1-init_sql.ts
- src/core/storage/sqliteStorage/migrations/v0.0.2-credentialPrefix.ts
- src/core/storage/sqliteStorage/sqliteSession.ts
- src/core/storage/sqliteStorage/utils.ts
Recently we added a `0.0.2` migration which reads JSON blobs from the DB and updates them. This requires the tables to be in place.
Since we were migrating all outstanding migrations in one single transaction, this is a problem as the SQL statements to apply required tables to already be in place.
The simplest and most safe thing to do here is to have a single transaction per migration and write the new version each time.
Manual testing on the previous PR was against wallets which were already on `0.0.1` so the issue didn't surface. E2E tests when integrated will solve that though.
This PR also adds better typing to the migrations.
> fix(core): db transaction per migration

- src/ui/components/SideSlider/SideSlider.scss
- src/ui/components/SideSlider/SideSlider.test.tsx
- src/ui/components/SideSlider/SideSlider.tsx
- src/ui/components/SideSlider/SideSlider.types.ts
Fix Closing settings animation is sluggish. Beside that, I also fixed cadarno connect open animation missing after close setting.
https://github.com/user-attachments/assets/9a7c45c9-2dd4-49d2-9ff7-ef738640e32b
---
https://github.com/user-attachments/assets/d4c2c127-45e9-4a5e-b35e-185ce97a7798
https://github.com/user-attachments/assets/e3ebc72c-080f-4347-93e0-a8bef0a4a5f1
https://github.com/user-attachments/assets/3b6ba284-91c4-47bd-b9b7-6dd7c7800f55
[DTIS-1198]: https://cardanofoundation.atlassian.net/browse/DTIS-1198?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Closing settings animation is sluggish but cardano connect is not

- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/locales/en/en.json
- src/store/reducers/walletConnectionsCache/walletConnectionsCache.test.ts
- src/store/reducers/walletConnectionsCache/walletConnectionsCache.ts
- src/store/reducers/walletConnectionsCache/walletConnectionsCache.types.ts
- src/ui/components/ArchivedCredentials/ArchivedCredentials.test.tsx
- src/ui/components/ArchivedCredentials/ArchivedCredentials.tsx
- src/ui/pages/IdentifierDetails/components/IdentifierContent.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.tsx
- src/ui/pages/SidePage/SidePage.tsx
- src/ui/pages/SidePage/components/WalletConnect/WalletConnectStageTwo.tsx
Bug fixes for spike [DTIS-1178](https://cardanofoundation.atlassian.net/browse/DTIS-1178)
About SSI Agent information modal is empty. Robert is waiting from Fergal and Thomas.
---
https://github.com/user-attachments/assets/cb542170-ad67-4215-9df0-eddd2036a84a
https://github.com/user-attachments/assets/e4d7fb06-20c8-4f27-a743-278fc938de8e
https://github.com/user-attachments/assets/793b01d4-dd74-45c0-bc5a-91a6c0c83192
https://github.com/user-attachments/assets/5042ee14-3e5e-4b77-b33a-ce50074c448d
https://github.com/user-attachments/assets/00f83bd0-110d-4b54-a9af-8d291fda5307
https://github.com/user-attachments/assets/1836ffc0-3cb0-48ba-b272-0b500ea0886b
https://github.com/user-attachments/assets/86f18c0e-3aee-4ca2-8e8f-574609630a7e …
> fix(ui): Bug fixes for spike DTIS-1178

- android/app/capacitor.build.gradle
- android/capacitor.settings.gradle
- capacitor.config.ts
- ios/App/Podfile
- ios/App/Podfile.lock
- package-lock.json
- package.json
- src/ui/components/SeedPhraseModule/SeedPhraseModule.tsx
- src/ui/hooks/privacyScreenHook.ts
Disallow screenshots on recovery phase, hide app contents when in app switcher
---
It seem this plugin is not working on emulator. Therefore, I tried to test on my android phone. (So sorry if video so shaky, I need use another phone to record it)
https://github.com/user-attachments/assets/2784f72c-a2be-452d-8ed1-1caf658c83b8
https://github.com/user-attachments/assets/f7e93a4b-74b3-4bdb-96cf-201a5f24ba7e
https://github.com/user-attachments/assets/38298ed5-8d6e-424b-bf7c-acf7b44fadb4
https://github.com/user-attachments/assets/22f68150-4f6a-4cc9-bf0f-60951b4d28a1
[DTIS-1202]: https://cardanofoundation.atlassian.net/browse/DTIS-1202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Disallow screenshots on recovery phase, hide app contents when in app switcher

- src/ui/components/ArchivedCredentials/ArchivedCredentials.test.tsx
- src/ui/components/ArchivedCredentials/CredentialItem.tsx
- src/ui/components/SwitchCardView/CardList.tsx
Avoid spacing strings from the core based on capitals or numbers on multisign identifier and archived cred.
---
[DTIS-1235]: https://cardanofoundation.atlassian.net/browse/DTIS-1235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Avoid spacing strings from the core based on capitals or numbers

- src/ui/components/Scanner/Scanner.tsx
- src/ui/globals/types.ts
- src/ui/pages/Identifiers/Identifiers.test.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
- src/ui/pages/Scan/Scan.test.tsx
- src/ui/pages/Scan/Scan.tsx
Nav to identifiers tab and open scanned multisig identifier.
---
https://github.com/user-attachments/assets/b4575658-5876-4dea-ad76-7d21c5fa8f99
[DTIS-1233]: https://cardanofoundation.atlassian.net/browse/DTIS-1233?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DTIS-1231]: https://cardanofoundation.atlassian.net/browse/DTIS-1231?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Scanning a multi-sig QR code (after first scan) from the normal scanner causes an infinite spinner

- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
Enable validate button after connect fails 
---
https://github.com/user-attachments/assets/d1956d09-2791-4b67-8b7e-56b265ee5acc
[DTIS-1221]: https://cardanofoundation.atlassian.net/browse/DTIS-1221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Validate btn on SSI agent screen disabled if connect fails

- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
Limit get matching creds to credentials held by the recipient of the apply message
> feat(core): limit get matching creds by identifier

- src/core/agent/agent.ts
- src/core/agent/agent.types.ts
- src/core/agent/services/signifyNotificationService.test.ts
- src/core/agent/services/signifyNotificationService.ts
- src/core/agent/services/utils.ts
- src/store/reducers/stateCache/stateCache.ts
- src/ui/App.test.tsx
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/hooks/useOnlineStatusEffect.ts
App was "online" in Redux by default, so if KERIA is down on start-up, it always thought it was online.
Now also only change online status in one place based on updates from core event bus/service.
Stop re-initialising signifyClient agent service props and don't set offline in recursive calls of `agent.connect`. (both of these were causing timing issues and causing it to flicker from online to offline and back continuously).
> fix: offline mode bugs

- src/ui/pages/Connections/Connections.test.tsx
- src/ui/pages/Connections/Connections.tsx
Fix issue about deleting a pending connection that doesn’t exist
---
https://github.com/user-attachments/assets/8be15edd-8bf3-4912-81a2-a69713acc2eb
[DTIS-1267]: https://cardanofoundation.atlassian.net/browse/DTIS-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Deleting a pending connection fails

- src/core/cardano/walletConnect/identityWalletConnect.ts
We shouldn't be caching the signer like this because if we issue a key rotation while still connected, it will try to sign with the old keys.
We could clear the cache for that identifier if a key rotation occurs but honestly it's not worth the complexity.
@jorgenavben Can you test this against ballot?
> fix(core): stop caching signer for cip-45

- src/core/agent/agent.types.ts
- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
Display pending credential in UI automatically for multi-sig
> feat(ui): display pending credential in UI automatically for multi-sig

- src/locales/en/en.json
- src/ui/components/CreateIdentifier/components/IdentifierStage1.test.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1.tsx
- src/ui/components/CreateIdentifier/components/IdentifierStage1BodyInit.tsx
- src/ui/components/layout/TabLayout/TabLayout.scss
- src/ui/components/layout/TabLayout/TabLayout.tsx
- src/ui/pages/Credentials/Credentials.tsx
- src/ui/pages/Identifiers/Identifiers.tsx
- src/ui/pages/Menu/Menu.tsx
- src/ui/pages/Menu/components/Profile/Profile.test.tsx
- src/ui/pages/Notifications/Notifications.tsx
- src/ui/pages/Scan/Scan.tsx
Fixing a bug that should show the person we scanned when we are invited to a group id.
Also fixed the following bug:
**NOTES:**
In the videos there is an issue with the notification not arriving on time on the emulators. I asked Fergal and this is a core issue currently being fixed in another PR.
---
https://github.com/user-attachments/assets/93b3866d-6121-42ef-a19c-da703240a365
https://github.com/user-attachments/assets/f1f33478-2e1c-4c56-9242-6e418f8d2307
https://github.com/user-attachments/assets/172299c3-303e-4ac8-a557-5c63a2ae6610
> fix(ui): Wrong screen footer after scanning group invitation

- src/core/agent/agent.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
We were just deleting the notification record and not marking it as read on KERIA. So if the DB was lost and wallet recovered, the notification was re-appearing.
Also moved it to the bottom of the function. We should only delete the notification once it has successfully been actioned completely in case it fails halfway through.
> fix(core): mark multisig/icp as read on KERIA once actioned

- src/ui/components/Scanner/Scanner.scss
- src/ui/components/Scanner/Scanner.tsx
- src/ui/pages/LockPage/LockPage.scss
- src/ui/pages/Scan/Scan.scss
Fix UI bug:
- Camera height
- Identifier Multisig display in front of Lock Page
---
https://github.com/user-attachments/assets/bc5e04bf-a3fd-47f4-a9ec-bbecaa5d794a
https://github.com/user-attachments/assets/34e00a6d-607d-43a3-aca3-0de7bacac59c
[DTIS-1305]: https://cardanofoundation.atlassian.net/browse/DTIS-1305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): UI: More bug fixes

- src/core/agent/services/connectionService.ts
Fixes an issue raised by @Sotatek-DukeVu in #721 
We had this cache for resolved OOBIs and when deleting the connection we weren't clearing the cache.
I've actually just removed the cache altogether since its unnecessary. I added the cache for repeated solutions of schema OOBIs but the reality is that will be changing soon too.
> fix(core): allow repeated oobi resolves to re-create contact

- src/core/agent/records/identifierStorage.ts
#723 introduced this because we always expected deleted identifiers to already be archived.
> fix(core): deleted identifiers should not be returned from get all

- .github/workflows/docker-builds.yaml
- .github/workflows/gh-verify-pr.yaml
We have PR workflows and workflows for pushes to develop and main.
For merges from develop to main - we don't need the PR workflow and can just use the push workflow.
> ci(gha): stop running PR pipelines for PRs to main

- src/ui/pages/Notifications/Notifications.tsx
For some reason, notifications aren't sorted from the newest to the oldest. Adding this small fix to make sure they are.
Since I am not adding anything new to the UI, I will only take screenshots on the browser.
---
> bugfix(ui): Sort notifications by chronological order

- src/core/cardano/walletConnect/peerConnection.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.tsx
Disconnect cardano wallet firing twice
---
https://github.com/user-attachments/assets/8511f429-1f01-48a2-9742-fccbb5d27bfa
https://github.com/user-attachments/assets/7be41f05-7c0e-4954-847c-3de5c7df92b1
[DTIS-1342]: https://cardanofoundation.atlassian.net/browse/DTIS-1342?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Disconnect wallet firing twice 

- src/locales/en/en.json
- src/ui/__fixtures__/credRequestFix.ts
- src/ui/components/CardList/CardList.scss
- src/ui/components/layout/ScrollablePageLayout/ScrollablePageLayout.scss
- src/ui/pages/Menu/components/Settings/components/RecoverySeedPhrase/RecoverySeedPhrase.scss
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential.scss
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.test.tsx
Adding tabs to let the user choose between providing an active or a revoked credential when asked to provide one.
We are still showing the alert when the user receives a request but they don't have any suitable credential, but we are now also adding a dedicated message inside each tab in case they have one which falls into one category and not in the other. Some demo of this have been added below the videos for iOS and Android and tested in the browser.
---
https://github.com/user-attachments/assets/ec309b99-004e-4c8b-826f-fc7b9fc56d73
https://github.com/user-attachments/assets/66394a92-130a-4a67-9677-41d15e24d8c2
https://github.com/user-attachments/assets/9dc90520-1cde-4c54-bf57-b19342517b65
https://github.com/user-attachments/assets/bf64475d-893d-4953-a52b-272d2c240d6a …
> feat(ui): Credential request improvements

- src/locales/en/en.json
- src/ui/components/CredentialDetailModule/CredentialDetailModule.tsx
- src/ui/components/CredentialDetailModule/components/CredentialContent.test.tsx
- src/ui/components/CredentialDetailModule/components/CredentialContent.tsx
Add Credential ID to the Credential Details Page allowing the user to know and use this value.
I won't be adding any new UI feature, just adding one more value to the already existing list, therefore I will only take a screenshot from the browser.
---
> feat(ui): Add Credential ID to the Credential Details Page

- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
Making the receive credential animation quicker because at the moment it seems like we are stuck at the end of the animation.
---
https://github.com/user-attachments/assets/9ccdc2ea-c271-41b9-bc61-907b3db19f60
https://github.com/user-attachments/assets/bc5e6056-eeb6-4dd1-9464-ba20816a4b5d
> fix(ui): remove delay from the receive credential animation

- src/ui/components/CardDetails/CardDetailsAttributes/CardDetailsNestedAttributes.tsx
The error was caused by a missing regex that was supposed to distinguish between attributes when receiving a normal string vs a date converted to string. 
The following date to string formats are accepted:
"2024-01-22T16:03:44.643Z",
"2024-09-18T14:53:15.497000+00:00",
"2024-09-18T14:53:15.497-05:00",
I am only testing it on browser since I am not introducing any new UI elements to the existing design.
---
> fixx(ui): SignRequest does not parse category id correctly

- src/ui/App.scss
- src/ui/components/CreateIdentifier/components/IdentifierStage0.tsx
Fix multisig scan issue. Reason because when full page scan open it will hide all element on app. I also fix create identifier modal not display when open full page scan.
---
https://github.com/user-attachments/assets/1b345e5d-e8ec-41bd-84d7-f6c7d6d0c85c
[DTIS-1461]: https://cardanofoundation.atlassian.net/browse/DTIS-1461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): fix scan issue after create multisig

- android/build.gradle
- capacitor.config.ts
- src/core/storage/secureStorage/secureStorage.ts
- src/core/storage/sqliteStorage/sqliteSession.ts
This PR updates the `open` method from sqlite to enhance the security of database connections by integrating encryption for non-web platforms. It checks if encryption is enabled and whether a secret is already stored. If no secret is stored, it generates a new one using `Agent.agent.getBranAndMnemonic()` and securely stores it using `SecureStorage`. This approach ensures that sensitive data handled by the application is more secure across platforms.
The sqlite plugin stores the key provided for encryption independently to which we cannot access or check the value of the key, that is why we store thhis new key-value using our `SecureStorage` in order to have 100% control of the encryption key.
From xcode you can get the path where the sqlite database is stored from the console, example: …
> feat: set encryption for db

- src/core/agent/agent.ts
- src/core/agent/services/credentialService.ts
- src/core/agent/services/identifier.types.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
Exposes the member identifiers for a group identifier when retrieving the details. The UI can use this along with the Redux caches to display the other connections for that identifier.
**Note:** It will also return the local member identifier related to this multi-sig, which will not be in the multisig connections cache - it can be skipped.
> feat(core): return members when retrieving group identifier

- src/core/agent/records/credentialStorage.ts
- src/core/agent/services/credentialService.ts
The filter for isDeleted in getCredentials should be removed in favour of filtering by isDeleted in getAllCredentialMetadata using the query tags in SQL
> perf(core): filter by isDeleted for credentials using tag query

- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/ipexCommunicationService.types.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
- src/ui/__fixtures__/credRequestFix.ts
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.types.ts
Keep the notification until the operation of ipex/offer is done and get identifierType for offer credential
> fix: keep notification until operation of ipex/offer done and get identifierType for offer credential

- jest.config.ts
- package-lock.json
- package.json
- src/ui/__mocks__/swiper.tsx
- src/ui/components/CardSlider/CardSlider.scss
- src/ui/components/CardSlider/CardSlider.test.tsx
- src/ui/components/CardSlider/CardSlider.tsx
- src/ui/components/CredentialCardTemplate/components/KeriCardTemplate/KeriCardTemplate.scss
- src/ui/components/CredentialCardTemplate/components/RareEvoCardTemplate/RareEvoCardTemplate.scss
- src/ui/components/IdentifierCardTemplate/IdentifierCardTemplate.scss
- src/ui/components/OptionsModal/OptionsModal.scss
- src/ui/components/Slides/Slides.scss
- src/ui/components/Slides/Slides.tsx
- src/ui/pages/Identifiers/Identifiers.scss
Updating the `Swiper` component to the latest release and updating how this is being used in the Identifiers tab so the start of the next card and the end of the card before (except on the first card) to make it more obvious it's a swiping motion.
---
https://github.com/user-attachments/assets/48936e96-e39a-416e-a9f8-2eb00f2e06ed
https://github.com/user-attachments/assets/4ac0702f-acdc-47ac-b2c5-a341510a7da2
> fix(ui): Update favourites cards slider

- src/locales/en/en.json
- src/ui/components/InputRequest/InputRequest.tsx
- src/ui/components/RecoverySeedPhraseModule/RecoverySeedPhraseModule.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential/ChooseCredential.tsx
Fix issues: 
- Missing accept button when accept multisig request
- Credential request notification not removed after user accept
- Remove unused alert on verify seed phrase
- Prevent dismiss set user name popup
---
https://github.com/user-attachments/assets/0c5c1009-cf1e-4756-9a26-9154d98b3d67
https://github.com/user-attachments/assets/19beea8f-a3be-4d6d-84a4-43d81f403c91
[DTIS-1508]: https://cardanofoundation.atlassian.net/browse/DTIS-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Cannot accept multi sig invitation

- src/core/__fixtures__/agent/keriaNotificationFixture.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
This will help us build back up the local version of it in case of recovery.
> feat: only mark linkedGroupRequests as read on KERIA once original notification deleted

- Earthfile
- docker-compose.yaml
- services/docker-compose.yaml
The Keria version used in the docker-compose file was returning an error every time that you tried to validate the SSI Agent details. [This commit](https://github.com/WebOfTrust/keria/commit/736947191069cfc1617a43f63dbc64210c351b5c) from @iFergal solves the issue. This PR upgrades the version of KERIA used in the docker-compose file to fix the issue.
> fix(docker): update build context to latest commit from keria

- package-lock.json
- package.json
- services/credential-server/package-lock.json
- services/credential-server/package.json
In support of DTIS-1378. This version will let us check if a credential has been revoked before accepting it, and simplify our revocation flow (and make it more reliable).
cc: @Sotatek-BaoHoanga
> build: bump signify version

- src/ui/App.test.tsx
- src/ui/App.tsx
Add global event to catch unhandled error and show toast message.
---
https://github.com/user-attachments/assets/23282d62-6a68-44a9-92c8-2ae87ff7cf9f
[DTIS-122]: https://cardanofoundation.atlassian.net/browse/DTIS-122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Generic error toasts in the UI

- src/ui/App.test.tsx
Fix UT on `App.test.tsx` file:
- `Force status bar style is dark mode on ios`: Currently, this UT is using mock implementation of `getPlatforms` function by using `mockImplementationOnce` function. It mean after first run `getPlatforms` mock implementation will be cleaned and other test will override mock implementation of `getPlatforms`. In this case we should use `mockImplementation` instead.
- `It renders SetUserName modal`: Update this test follow new implement of `SetUserName` modal.
---
[DTIS-892]: https://cardanofoundation.atlassian.net/browse/DTIS-892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Force status bar style is dark mode on iOS failing test

- src/core/agent/services/connectionService.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
deleting a Keria connection when the local connection metadata record does not exist
[DTIS-1470]: https://cardanofoundation.atlassian.net/browse/DTIS-1470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: deleting a keria connection when the local connection metadata record does not exist

- src/core/agent/agent.ts
- src/core/agent/services/connectionService.ts
Small issue from #806 - we should use `connections` to make sure it's initialised, and it should only be called when online.
Also, the function was always setting `isOnline` to true for some reason, fixed. That could've been the source of some issues with offline mode.
> fix(core): only process pending connection ops when online

- src/core/agent/services/connectionService.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
Deleting a keria connection when the record pendingDeletion is true
> feat(core): Deleting a keria connection when the record pendingDeletion is true

- src/core/agent/event.types.ts
- src/core/agent/services/connectionService.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/InputRequest/InputRequest.tsx
- src/ui/components/Scanner/Scanner.tsx
Add pending connections with the correct ID through the use of core emitted events.
---
https://github.com/user-attachments/assets/9ea3bd63-7ce5-4b8e-b710-e001b4aa4ab0
[DTIS-1530]: https://cardanofoundation.atlassian.net/browse/DTIS-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Missing connection name should not update Redux twice

- src/locales/en/en.json
- src/ui/components/InfoCard/InfoCard.tsx
- src/ui/components/InfoCard/InfoCard.types.ts
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.scss
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.scss
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.test.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
- src/ui/styles/colors.scss
Display revocation notification for credentials before user acceptance
---
https://github.com/user-attachments/assets/cf2301e7-6d0c-451d-aec6-6a52e2bbf887
[DTIS-1352]: https://cardanofoundation.atlassian.net/browse/DTIS-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Display revocation notification for credentials before user acceptance

- src/ui/pages/Identifiers/Identifiers.tsx
Fix pending group identifier showing as completed
---
https://github.com/user-attachments/assets/13524842-0cde-42db-b45e-60c8fa9b58ef
[DTIS-1556]: https://cardanofoundation.atlassian.net/browse/DTIS-1556?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix(ui): Pending group identifier showing as completed

- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
Update logic with random salt in name when deleting identifier
> fix(core): update logic with random salt in name when deleting identifier

- src/core/agent/agent.ts
- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/utils.ts
- tsconfig.json
Change ESNext and pass { cause: e } to propagate error stacks
> feat(core): change ESNext and pass { cause: e } to propagate error stacks

- src/core/agent/agent.test.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
Update the name of the local member in the signify group identifier when deleting the identifier
> fix: update name of local member in signify group identifier when deleting

- src/locales/en/en.json
- src/ui/components/CredentialDetailModule/components/MultisigMember.tsx
- src/ui/components/CredentialDetailModule/components/MultisigMember.types.ts
- src/ui/globals/types.ts
- src/ui/pages/NotificationDetails/components/CredentialRequest/ChooseCredential/ChooseCredential.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.types.ts
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.scss
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.tsx
Update credentials presentation flow. Now initiator must be chosen present credential first. Other members can accept or reject it.
---
https://github.com/user-attachments/assets/5afe32cf-c74b-4e0a-8b9b-786160854115
https://github.com/user-attachments/assets/a2b0ce2e-e8ea-407f-9ff1-df5d15c9d2e4
[DTIS-1567]: https://cardanofoundation.atlassian.net/browse/DTIS-1567?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): UI: IPEX multi-sig credentials presentation

- src/core/agent/agent.types.ts
- src/core/agent/event.types.ts
- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
- src/store/reducers/notificationsCache/notificationsCache.test.ts
- src/store/reducers/notificationsCache/notificationsCache.ts
- src/ui/App.test.tsx
- src/ui/__fixtures__/notificationsFix.ts
- src/ui/components/AppWrapper/AppWrapper.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/AppWrapper/coreEventListeners.ts
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
- src/ui/pages/Notifications/Notifications.tsx
- src/ui/pages/Notifications/components/NotificationOptionsModal.test.tsx
- src/ui/pages/Notifications/components/NotificationOptionsModal.tsx
This PR allows the UI to more closely match our notifications design for group IPEX for refreshing. Refreshing here means marking the notification as unread, and setting it's `createdAt` date to now. We will be renaming createdAt in the future to better reflect this.
Changes:
- When the leader accepts a credential, the notification will be refreshed for other members
- When the leader proposes a credential from a request, the notification will be refreshed for other members
- When a credential presentation meets the threshold, the notification will be refreshed for all members instead of being removed
When the threshold is met for receiving a credential, the notification will still be deleted because the user can see that the credential went from pending to confirmed. (There is connection …
> feat: refresh IPEX notifications on major signing events

- src/ui/styles/colors.scss
Fixing bug related to a broken card color as a result of a recent update to our colors stylesheet.
> fix(ui): Broken card color

- src/core/storage/sqliteStorage/migrations/index.ts
This was to test how we do it and was proven. I’d clean this up pre-release and keep it in the history for future needs.
> feat: removal of v0.0.2 migration (consolidate)

- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/utils.ts
We mark notifications as read once we have deleted them, or we are done processing them if they are not user facing.
A notification can only be marked once, or it will return 404.
It’s possible that we mark it as read, and crash before deleting the notification in the local database of the wallet.
When we try to delete again, we will hit this 404 error.
> feat(core): marking notification as read when deleting distributed reliability

- src/core/__fixtures__/agent/ipexCommunicationFixtures.ts
- src/core/agent/services/keriaNotificationService.test.ts
Covered by "Should call createLinkedIpexMessageRecord with TEL status is revoked and exists locally"
This is for https://cardanofoundation.atlassian.net/browse/DTIS-1575 but with recent refactoring to only update connection history from long running operations for IPEX, all the expects were in place.
> test(core): remove duplicate test

- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/ui/App.test.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.test.tsx
- src/ui/components/CreateIdentifier/CreateIdentifier.tsx
KAWA is KERI's witness agreement algorithm. Given a correctly configured witness pool (with correct thresholds) it can guarantee immunity based. See table here: https://github.com/WebOfTrust/keripy/discussions/837
For our first release, I've taken that table from witness count 6 up, and using the lower threshold to allow for higher availability. Maximum pool size of 12, can be extended if needed.
KAWA, given the constraints guarantees immunity by way of a witness pool will either produce a fully signed event or none at all.
> feat(core): sane KAWA thresholds

- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
When we receive the notification we check the TEL (transaction event log - for tracking revocations) status of the credential. Everything is async in KERI, so it's possible that the status is still `iss` and not `rev`. We handled this case for already accepted credentials. This PR now handles it when you have not yet accepted the credential.
The bug (which is intermittent) is that you would have 2 identical notifications (in appearance). But now the new notification replaces the old.
In case the old notification is deleted, then it will appear as if it's the first, which is as expected.
> fix(core): handle delayed rev telStatus when cred not accepted

- src/core/storage/secureStorage/secureStorage.ts
- src/ui/components/VerifyPassword/VerifyPassword.tsx
Fix for catching error from iOS when key not in the secure storage.
> fix: catch ios key not found error in secure storage

- src/core/storage/sqliteStorage/sqliteStorage.ts
In case it's an empty list, you will end up with a query of `''` on the join. Then the final outer query string will end up with ` AND <otherquery2> AND <otherquery3>`, which is invalid. Should be `<otherquery2> AND <otherquery3>`.
> fix(core): $and $or queries should be skipped for empty arrays

- src/locales/en/en.json
- src/ui/pages/Notifications/NotificationItem.tsx
- src/ui/pages/Notifications/Notifications.test.tsx
- src/ui/pages/Notifications/Notifications.tsx
Add new alert to inform user that they can accept credential from unknown issuer.
---
https://github.com/user-attachments/assets/c5ab2e77-295f-4066-a0fe-50f3218acc0e
> feat(ui): display alert when unknown connection want to issue

- src/ui/pages/NotificationDetails/NotificationDetails.tsx
After user had accepted notification, core sent `NotificationRemoved` event to UI and current notification will be removed.
Notification page had been closed before setTimeout call (Because notification has been deleted in redux).
---
https://github.com/user-attachments/assets/919d7a9c-3623-485a-b571-8dd99f687958
https://github.com/user-attachments/assets/eac5a3a5-b64d-4722-8115-52981922f7b4
[DTIS-1708]: https://cardanofoundation.atlassian.net/browse/DTIS-1708?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): Broken animation for accepting a credential

- CONTRIBUTING.md
Fixes the links to templates inside CONTRIBUTING.md
> Fix CONTRIBUTING.md links to templates

- package-lock.json
- package.json
For whatever bizarre reason, a fetch `Request` instance _with_ a body on Android WebViews will have a `req.body` value of `undefined`. No issues in Chrome (and both use Chromium), or iOS.
`await req.arrayBuffer()` still returns the body in bytes, so I just directly call this now. This also simplified the original code as I didn't realise this was available on the request as well as response, so removed the custom function I had in Signify to convert a `ReadableStream` to a `Uint8Array`.
> fix: building of essr tunneled req body 

- .github/workflows/docker-builds.yaml
- .github/workflows/gh-verify-branch.yaml
- .github/workflows/gh-verify-pr.yaml
No longer using develop. Need this to get tests back on PRs to main etc and general cleanup.
> ci(gha): remove develop branch and ignore on main

- src/core/agent/records/identifierMetadataRecord.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/multiSigService.ts
These are stored encrypted on KERIA using salty key stores with Signify. Locally storing in case of loss of access to cloud. We will iterate on this by allowing backup to other clouds etc in case cloud and device lost at same time.
> feat(core): locally backup sxlts for identifiers

- src/core/agent/agent.ts
If we emit the event from the storage service, the event emitter needs to be initialised before the storage services. Otherwise the events aren't published properly and caught.
> fix(core): eventEmitter should be instantiated before operation storage

- src/core/agent/agent.ts
- src/core/agent/services/utils.ts
- src/routes/backRoute/backRoute.test.ts
- src/routes/nextRoute/nextRoute.test.ts
- src/store/reducers/notificationsCache/notificationsCache.test.ts
- src/store/reducers/stateCache/stateCache.ts
- src/store/reducers/stateCache/stateCache.types.ts
- src/ui/components/AppWrapper/AppWrapper.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
- src/ui/pages/GenerateSeedPhrase/GenerateSeedPhrase.tsx
When you recover a wallet, the agent status wasn't being set to true like when you fresh onboard. It's a bit trickier here because when you recover, you sync the DB from KERIA so you need to initialise Redux too with `loadDatabase` so I added something in Redux for this.
- Not sure if necessary here.
> fix: after recovering successfully, update redux and mark agent online

- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
Now that we aren't passing the alias to KERIA when resolving the OOBI, the contact isn't auto created.
When creating the contact, we weren't storing the OOBI like before so this fixes that. It's needed when e.g. resolving new schemas etc.
> fix(core): store missing oobi for contact

- src/ui/pages/Menu/components/Settings/Settings.tsx
Fix issue about biometrics still enable after user cancel
---
https://github.com/user-attachments/assets/16904208-f765-4b40-adb6-07c3cfa05d0b
> fix(ui): If I cancel while enabling biometrics, it still gets enabled

- src/ui/components/CredentialDetailModule/CredentialDetailModule.tsx
- src/ui/components/IdentifierDetailModule/IdentifierDetailModule.tsx
- src/ui/components/VerifyPassword/VerifyPassword.tsx
- src/ui/components/layout/ResponsiveModal/ResponsiveModal.tsx
- src/ui/components/layout/ResponsiveModal/ResponsiveModal.types.ts
Disable backdrop dismiss on verify password modal
---
https://github.com/user-attachments/assets/f1388d47-f0e7-403a-bc6c-2147984a5240
https://github.com/user-attachments/assets/384a8d3b-2af7-4613-a863-879f30cc22f4
> feat(ui): Should not be stuck after dismissing verify password modal

- .github/workflows/gh-verify-pr.yaml
- README.md
- src/core/__fixtures__/agent/keriaNotificationFixtures.ts
- src/core/__fixtures__/agent/multiSigFixtures.ts
- src/core/agent/agent.test.ts
- src/core/agent/agent.types.ts
- src/core/agent/records/credentialMetadataRecord.test.ts
- src/core/agent/records/credentialStorage.test.ts
- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
- src/core/agent/services/credentialService.test.ts
- src/core/agent/services/identifierService.test.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
- src/core/storage/ionicStorage/ionicStorage.ts
- src/core/storage/sqliteStorage/sqliteStorage.ts
- src/store/reducers/credsArchivedCache/credsArchivedCache.test.ts
- src/store/reducers/credsCache/credsCache.test.ts
- src/ui/__fixtures__/credsFix.ts
- src/ui/__fixtures__/filteredCredsFix.ts
- src/ui/__fixtures__/shortCredsFix.ts
- src/ui/pages/Menu/components/Settings/components/ManagePassword/ManagePassword.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.test.tsx
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.tsx
It's important that if we start processing a notification or long running operation completion that it's idempotent so we can re-process it if needs be. This PR has some fixes to improve that, as well as covers many edge cases such as receiving notifications after deleting an identifier, or other out of order notifications.
I've made some adjustments to ensure that if we restore a wallet, we recover into a good state as well as possible.
> feat(core): idempotent processing of notifications and operations

- .nsprc
- package-lock.json
`npm audit fix` allowed us to remove `1102341`.
`1100267` and `1102339` are not relevant after proper inspection. Note that we cannot consider a vulnerability safe just because it relates to the build or e2e tests etc, but in this case, those vulnerabilities are not relevant.
From initial inspection, `1101851` is not relevant either and doesn't seem applicable to Meerkat. I will have a further think about this (ticket to track) in case there is some p2p version of the attack - at least our current usage of Meerkat does not seem to be open to this. I've also sent a message to Fabian to discuss.
> build: npm audit and revised notes after investigating further

- src/ui/components/VerifyPassword/VerifyPassword.tsx
Close verify password modal after recover password.
---
https://github.com/user-attachments/assets/7ace0a5b-1ac6-463f-82c8-44ceb1ba9464
> fix(ui): Forgot operations password - modal still open

- Earthfile
The directory names were updated, so pointing to the "old" UI until we've migrated.
> build(earthly): build old cred ui until new one is ready

- src/ui/pages/Menu/components/Settings/components/ManagePassword/ManagePassword.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.test.tsx
It seem Jest doesn't cleanup JSDOM after each test (maybe only for alert) (https://github.com/jestjs/jest/issues/1224), it make alert 's JSDOM of previous test still exist on current test and jest find duplicate text. Therefore, I was cleaned up JSDOM after the test that use `Alert` component.
---
> feat(ui): Fix flakeys test

- src/ui/components/CardDetails/CardDetailsAttributes/CardDetailsNestedAttributes.tsx
- src/ui/components/CardDetails/CardDetailsExpandAttributes/CardDetailsAttribute.tsx
- src/ui/components/CredentialDetailModule/components/CredentialContent.test.tsx
- src/ui/components/CredentialDetailModule/components/CredentialContent.tsx
- src/ui/components/IdentifierDetailModule/IdentifierDetailModule.scss
- src/ui/components/IdentifierDetailModule/IdentifierDetailModule.test.tsx
- src/ui/components/IdentifierDetailModule/components/IdentifierAttributeDetailModal/Advanced.tsx
- src/ui/components/IdentifierDetailModule/components/IdentifierContent.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/ConnectionDetails/components/ConnectionHistoryEvent.tsx
- src/ui/utils/formatters.ts
Add UTC offset on date time field
---
https://github.com/user-attachments/assets/532e501f-5a6d-468a-94b7-8d67f8868e0c
> feat(ui): i18n: considerations

- src/ui/components/PasswordModule/PasswordModule.test.tsx
- src/ui/components/PasswordModule/PasswordModule.tsx
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.scss
Disallow storing password in hint
---
https://github.com/user-attachments/assets/417cd864-d05c-4e61-910e-8ab4360ce94c
> feat(ui): prevent password hint contain password value

- package.json
We only need to call `npx cap sync` when adding new Capacitor dependencies. `npx cap copy` should be enough to copy the web files after we've made changes.
The main issue right now with `npx cap sync` is we merged #988 which contains some custom iOS build flags for security reasons, and `npx cap sync` will overwrite the changes.
> build: only copy files for build:cap

- android/app/src/main/res/values/strings.xml
- capacitor.config.ts
- ios/App/App/Info.plist
- services/credential-server/README.md
- src/index.html
- src/locales/en/en.json
Updating app name as it appears in app draw/home screen etc to Veridian.
> build: update app name to veridian

- src/locales/en/en.json
- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/Settings/Settings.tsx
Add warning if trying to enable biometrics when it's off in phone settings
---
https://github.com/user-attachments/assets/870a7842-d69f-4381-9c2a-173e120bd6b7
https://github.com/user-attachments/assets/95ee4929-a10b-45fb-a6f6-e889e5d5a758
> feat(ui): Add warning if trying to enable biometrics when it's off in phone settings

- android/app/build.gradle
- android/app/proguard-rules.pro
When build the app through command line in Android Emulator - the app keep crashing.
Adding the flags from the doc above fixes the issue. Then,
`npm run build:cap && cd android && ./gradlew assembleRelease`
Source: [link](https://github.com/capacitor-community/sqlite/blob/master/docs/AndroidMinify.md)
> fix: exclude minification of all SQLCipher classes

- ATTRIBUTIONS.md
- LICENSE
- README.md
We are migrating from MPL-2.0 to the more permissive Apache-2.0 to better foster adoption. Attributions have also been added to give credit.
> docs: migrate from MPL-2.0 to Apache-2.0 license and attributions

- src/ui/App.tsx
- src/ui/pages/LockPage/LockPage.test.tsx
- src/ui/pages/LockPage/LockPage.tsx
Bring back to create passcode screen and start onboarding journey from beginning when click on forgot password button before set up seed phrase
---
https://github.com/user-attachments/assets/0e6fe309-f0ad-4cd8-a9e4-b18554e580fd
> feat(ui): Welcome back - Ive forgotten my passcode when recovery phrase is not yet set

- src/ui/components/Scanner/Scanner.tsx
Only the main scanner and the connections page scanner should be versatile to accept different scans. The Cardano Connect scanner should only accept Meerkat/Peer IDs.
`handleConnectWallet` contains the validation too for meerkat ID formats, but it wasn't being hit before.
> fix(ui): cardano connect scanner should only accept meerkat ids

- src/ui/components/CredentialDetailModule/components/CredentialContent.test.tsx
- src/ui/components/IdentifierDetailModule/IdentifierDetailModal.tsx
- src/ui/components/IdentifierDetailModule/IdentifierDetailModule.test.tsx
- src/ui/components/IdentifierDetailModule/IdentifierDetailModule.tsx
- src/ui/components/IdentifierDetailModule/IdentifierDetailModule.types.ts
- src/ui/components/IdentifierOptions/IdentifierOptions.test.tsx
- src/ui/components/IdentifierOptions/IdentifierOptions.tsx
- src/ui/components/IdentifierOptions/IdentifierOptions.types.ts
- src/ui/pages/NotificationDetails/components/ReceiveCredential/ReceiveCredential.test.tsx
This restricts deletion of identifiers to within the normal identifier flow. Deleting an identifier as a `Related identifier` link within a notification is entirely problematic, and an unnecessary flow. So this blocks that, and for consistency from within the credential details view too.
> fix(ui): should not be able to delete an identifier from a notification

- android/proguard-overwrites/README.md
- android/proguard-overwrites/proguard-rules.pro
- ios/App/Podfile.lock
- package.json
- src/index.tsx
- src/security/freerasp.ts
- src/ui/App.test.tsx
- src/ui/App.tsx
- src/ui/components/AppWrapper/AppWrapper.tsx
The freeRASP production build wasn't working as there was a conflict with the R8 minification. See comments in https://github.com/talsec/Free-RASP-Capacitor/pull/29. The proguard file is part of that PR but is missing in the node_modules, so this is a temporary fix to stage them for the release build.
Also, I have set it so that freeRASP is not initialised at all unless we are in prod, because otherwise Android will complain about the cert signing hash.
> build: fix android free rasp build

- src/ui/components/ConnectionOptions/ConnectionOptions.test.tsx
- src/ui/components/ConnectionOptions/ConnectionOptions.tsx
- src/ui/components/ConnectionOptions/ConnectionOptions.types.ts
- src/ui/components/CredentialDetailModule/CredentialDetailModule.test.tsx
- src/ui/components/CredentialDetailModule/CredentialDetailModule.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.test.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.tsx
- src/ui/pages/ConnectionDetails/ConnectionDetails.types.ts
Similar to #1042. This restricts deletion of connections to within the normal connection flow. Deleting a connection as a issuer link within a credential or notification is problematic, and an unnecessary flow. So this blocks that.
> fix(ui): should only be able to delete connections from direct view and not linked views

- src/security/freerasp.ts
DEVELOPER_MODE and ADB_ENABLED should behave the same/similar, and we have DEVELOPER_MODE disabled so we need to disabled also this common config in android devices ADB_ENABLED.
> fix: disable freerasp threat ADB_ENABLED

- src/ui/components/PageFooter/PageFooter.tsx
- src/ui/components/PageFooter/PageFooter.types.ts
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.scss
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.tsx
Fix credential request secondary decline button styles
> fix: credential request secondary cta has the old design

- src/ui/pages/Connections/Connections.tsx
- src/ui/pages/Connections/components/ConnectionsBody/ConnectionsBody.tsx
- src/ui/pages/Connections/components/ConnectionsBody/ConnectionsBody.types.ts
Fix back button hidden after closing searched connection
---
https://github.com/user-attachments/assets/e84fd60e-2034-4e6e-9755-99f45774a5f9
> fix(ui): Back button hidden after closing searched connection

- src/core/__fixtures__/agent/multiSigFixtures.ts
- src/core/agent/services/multiSigService.test.ts
- src/core/agent/services/multiSigService.ts
- src/ui/pages/NotificationDetails/components/MultiSigRequest/ErrorPage.scss
When creating groups, we use a `groupCreationId` or `groupId` that is a random salt as an indicator to other wallets that we are trying to set up a group, and not to treat OOBIs as normal connections but OOBIs of local group member identifiers.
There was naive check in place before when processing a group inception of `len(otherLinkedContacts) == len(smids) - 2` - so when we exclude ourselves, and the group initiator (sending of the message), we should have X linked contacts.
This doesn't work in 2 scenarios:
1. Everyone scans everyones QR code successfully, but the initiator decides to exclude someone when sending the inception event. Our UI supports this by unchecking people when initiating.
2. Bob might scan Carol's OOBI, but the initiator Alice never scanned or knew about Carol. And …
> fix(core): properly check linked contacts for group inception

- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.types.ts
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.test.tsx
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequestInformation/CredentialRequestInformation.tsx
Whenever the threshold has been met for a presentation request, we should just show the `OK` button. This works correctly when we accept before reaching the threshold - this bug only applies when you have not accepted it but the threshold has been met already.
The CTA action when clicked was correct, but the text was `Accept`, and the `Decline` button was also showing.
> fix(ui): correct cta btn for threshold reached presentation when not accepted

- src/core/agent/records/credentialStorage.test.ts
- src/core/agent/records/credentialStorage.ts
- src/ui/pages/NotificationDetails/components/CredentialRequest/CredentialRequest.tsx
`handleBack` was added to the dependency array of the `useCallback` as it's called in the catch block. However, it's also called after declining the request, which deletes the notification.
So after `handleBack` is called, we were trying to fetch the notification details again (which makes no sense in general), and in this case, the notification had been deleted already so you get a `Something went wrong` pop-up.
https://github.com/user-attachments/assets/328bac04-e8c5-4994-900d-5f4223b6c3f4
https://github.com/user-attachments/assets/6d4fcae6-7774-4a0e-ae7c-ea2d38f52ec7
> fix(ui): stop fetching credential request info after calling handleBack

- src/store/reducers/stateCache/stateCache.ts
- src/ui/components/CreatePasscodeModule/CreatePasscodeModule.tsx
- src/ui/components/ForgotAuthInfo/ForgotAuthInfo.test.tsx
- src/ui/components/ForgotAuthInfo/ForgotAuthInfo.tsx
- src/ui/pages/CreatePassword/CreatePassword.tsx
- src/ui/pages/LockPage/LockPage.test.tsx
- src/ui/pages/LockPage/LockPage.tsx
During the onboarding, after setting the pincode and biometrics, if we re-launch the app we land on the lock page.
If we click `I've forgotten my passcode`, it gets reset.
At this point:
1. If you relaunch the app, you'll get a biometrics prompt on the welcome screen that does nothing.
2. When setting the new passcode, you will be prompted to set it up again, even though it's already set.
a. If you cancel the setup, you'll get a prompt saying you can set it up later, despite already being set.
> fix(ui): reset biometrics preference when resetting onboarding passcode

- src/locales/en/en.json
- src/ui/components/MaxLoginAttemptAlert/hooks/loginAttemptHook.ts
- src/ui/pages/LockPage/LockPage.tsx
We use the `appStateChanged` handler as a way to auto prompt biometrics if both the app and phone itself got locked, and we unlock the phone to immediately try biometrics.
We need this because we don't prompt for biometrics if the app locks itself, but the phone hasn't locked overall.
So this fix handles the case where we hit the user fallback in the native prompt (`Enter Passcode`) - we were only handling the case where the user selects `Cancel`.
> fix(ui): dont re-prompt biometrics after user fallback on iOS

- src/core/storage/secureStorage/secureStorage.ts
Currently we have the flag `afterFirstUnlockThisDeviceOnly` to handle when the keychain can accesible. We change to `whenUnlockedThisDeviceOnly ` so Keychain item can be accessed just when the phone is unlocked.
**afterFirstUnlockThisDeviceOnly:** The data in the Keychain item cannot be accessed after a restart until the device has been unlocked once by the user.
**whenUnlockedThisDeviceOnly:** The data in the Keychain can only be accessed when the device is unlocked. Only available if a passcode is set on the device.
Source: [library code](https://github.dev/auth0/SimpleKeychain/blob/8137acba43bb92f3212c7b7d229aa7b336c5adb2/SimpleKeychain/Accessibility.swift#L4)
Keychain and data protection:
https://support.apple.com/guide/security/keychain-data-protection-secb0694df1a/web
> fix: set accessibility in SecureStorage

- src/ui/pages/Menu/components/Settings/Settings.test.tsx
- src/ui/pages/Menu/components/Settings/Settings.tsx
We only allow "strong" biometrics, as determined by the OS for safety reasons. We already handle this on onboarding, and the lockpage, where we only show biometric options if strong biometrics are available.
However, we never correctly blocked the setting in the settings menu.
After this PR, the setting won't appear in dev mode (browser), emulators, or device's with weak or no biometrics. So this PR requires a real device to verify there's no regression.
> fix(ui): only show biometrics setting if strong biometrics available

- src/ui/components/CardDetails/CardDetailsBlock/CardDetailsBlock.scss
- src/ui/components/CardDetails/CardDetailsExpandAttributes/CardDetailsAttributes.scss
Removing margins and adding padding to match design.
**NOTE:** 
I couldn't test on iPhone 8 but I think that should be ok.
---
> fix(ui): Attributes section of credentials has extra padding at bottom

- services/credential-server-ui/package-lock.json
- services/credential-server-ui/src/components/IssueCredentialModal/Review.tsx
- services/credential-server-ui/src/components/RequestPresentationModal/Review.tsx
- services/credential-server-ui/src/utils/urlChecker.ts
- src/ui/pages/Menu/components/ConnectWallet/ConnectWallet.test.tsx
In an attempt to improve the regex for pasting or scanning an OOBI I mistakenly only allowed the pattern for a single connection, thinking that the pattern would be similar for multi sig.
Changing this to allow both formats and only testing on browser as the result would be the same.
Also fixing ome flakey unit tests and a security audit warning for the cred issuance tool.
---
https://github.com/user-attachments/assets/d4687f5d-0e29-43a5-8aee-3c3df2b22b23
> [cred-ui] Fix regex to allow pasting and scanning group ID

- services/credential-server-ui/src/utils/urlChecker.ts
Regex was recently fixed to allow for Multi Sig ID URL here: [[cred-ui] Fix regex to allow pasting and scanning group ID by sdisalvo-crd · Pull Request #1087 · cardano-foundation/veridian-wallet](https://github.com/cardano-foundation/veridian-wallet/pull/1087/files) 
But apparently that wasn’t covering everything as a new bug came up.
> fix: url pattern

- services/credential-server-ui/src/components/NavBar/NavBar.tsx
In the current tablet view, all available menu items are showing up, regardless of which one is the logged in user.
As a result, clicking on some of those links may result in an error depending on your permissions level.
In this PR I am passing down the correct filtered menu items to reflect what we have in desktop view and only show the appropriate links based on the logged in user permissions.
> fix(cred-ui): Incorrect pages in tablet menu

- src/ui/components/InputRequest/InputRequest.test.tsx
- src/ui/components/InputRequest/InputRequest.tsx
Disable CTA button when user input space on user name input.
---
https://github.com/user-attachments/assets/4ef12bcc-47e1-451c-ab71-4fb69a47a063
> fix(ui): After onboarding, the CTA is active when you set the name as empty space

- .nsprc
- android/app/src/main/AndroidManifest.xml
- package-lock.json
- package.json
The build.gradle values are used in the build process when building the apk to determine it's SDK version and min/max. The device compatibility list in the Play console appears to be based on those values.
The manifest file is used by the Play Store to determine if an app should be downloadable by someone or not. In recent versions, it seems we might be able to remove `uses-sdk` completely and rely on the build.gradle, so it's weird that the Play Store does not already ignore the values in this file.
This PR updates `uses-sdk` instead of removing it for the sake of risk and time.
P.S - I should name the release branches `release/1.0` or `release/1.0.X` as I'd prefer to not create a separate branch for each patch. Will fix later.
> build: fix android manifest for play store

- src/core/agent/services/ipexCommunicationService.test.ts
- src/core/agent/services/ipexCommunicationService.ts
Fix issue about store non-serializable value to redux
---
https://github.com/user-attachments/assets/654772b3-1435-4aa2-9685-67c19e0512f8
> fix(ui): A non-serializable value was detected in an action

- src/ui/components/CustomInput/CustomInput.test.tsx
- src/ui/components/CustomInput/CustomInput.tsx
- src/ui/components/SeedPhraseModule/SeedPhraseModule.tsx
- src/ui/hooks/useHideKeyboard.ts
- src/ui/pages/ConnectionDetails/components/ConnectionNote.tsx
Fix cannot hide keyboard while entering new identifier
---
https://github.com/user-attachments/assets/849595a9-ddfc-4770-9971-fd52d017fbe3
> fix(ui): Cannot hide keyboard while entering new identifier

- src/ui/components/CreateGroupIdentifier/CreateGroupIdentifier.scss
- src/ui/components/CreateIdentifier/CreateIdentifier.scss
- src/ui/components/layout/ResponsiveModal/ResponsiveModal.scss
- src/ui/components/layout/ResponsivePageLayout/ResponsivePageLayout.scss
- src/ui/components/layout/ResponsivePageLayout/ResponsivePageLayout.tsx
- src/ui/components/layout/ScrollablePageLayout/ScrollablePageLayout.scss
- src/ui/components/layout/ScrollablePageLayout/ScrollablePageLayout.tsx
- Last updates to edge to edge support that will fix bottom screen being cut off (all Androids)
- Setup identifier title off center (all Androids)
- Copy connection URL button looks weird (small Androids only)
**NOTES:**
Tested on all devices, including iOS large and small, but only captured screenshots and videos on Android.
https://github.com/user-attachments/assets/049e3e32-ee6b-4537-a4bc-fc50611b9af7
> fix: bottom screen and title alignment

- Earthfile
- docker-compose.yaml
- package-lock.json
- package.json
- src/core/__fixtures__/agent/identifierFixtures.ts
- src/core/agent/agent.ts
- src/core/agent/records/connectionRecord.ts
- src/core/agent/services/connectionService.test.ts
- src/core/agent/services/connectionService.ts
- src/core/agent/services/connectionService.types.ts
- src/core/agent/services/identifierService.ts
- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
- src/ui/components/InputRequest/InputRequest.tsx
- src/ui/components/Scanner/Scanner.tsx
This allows us to forward an OOBI to a new contact using the `/introduce` reply message. It will only work for KERIA agents that opt into it.
The `externalId` query param is also forwarded in our OOBI URL if it was in the contacts. This means the query param can contain a unique ID which could be shared embedded in an OOBI for a service via email. This allows the service to associate users (by email) with their wallet. This is just a temporary solution and a real solution should use proper KYC etc, since the email becomes a shared secret.
> feat(core): forward oobi introductions to new contacts (optional)

- src/ui/pages/Identifiers/Identifiers.tsx
- src/ui/pages/Identifiers/components/Welcome/Welcome.test.tsx
- src/ui/pages/Identifiers/components/Welcome/Welcome.tsx
Fix missing the QR screen after creating a group identifier
---
https://github.com/user-attachments/assets/f038b613-230d-42ab-b4dd-30c921467dfc
> fix(ui): Missing the QR screen after creating a group identifier

- src/locales/en/en.json
- src/ui/globals/types.ts
- src/ui/pages/NotificationDetails/components/RemoteSignRequest/RemoteSignRequest.test.tsx
- src/ui/pages/NotificationDetails/components/RemoteSignRequest/RemoteSignRequest.tsx
Complete remote signing UI with real data.
Steps to get notification:
- run `docker compose up -d`
- Go to this branch of our fork: https://github.com/cardano-foundation/signify-ts/tree/build/v1.1
- Create a new examples/integration-scripts/remoteSigning.test.tsx file
- Flow:
- Create identifier in our wallet
- Use Signify-TS script to create an agent and a new identifier and OOBI
- Add the OOBI as a connection in the wallet on my branch
- Use a different Signify-TS script to use the same identifier to send a remote signing request
```
const hab = await client1.identifiers().get('alice');
const payload = { d: "d&n", t: 2 };
const [_, ked] = Saider.saidify(payload);
await client1.exchanges().send(
'alice',
'remotesign',
hab,
'/remotesign/ixn/req',
ked,
[], …
```
> feat(ui): Complete remote signing UI with real data

- src/ui/components/Scanner/Scanner.tsx
Fix camera cannot access after scan QR. Scan tab still exist on DOM after we nav to another tab. If we scan other QR by `FullPageScan`, Scan tab and current tab call function to init camera together and sometime it make this issue.
---
https://github.com/user-attachments/assets/cd6ae6c4-729e-45d9-b209-7630ba678d56
> fix(ui): unable to access camera if scan an unrecognized QR

- src/locales/en/en.json
- src/security/freerasp.ts
This should never have been in the list of threats. The device ID can change if you uninstall the app completely and re-install, which is not a threat in our case. We have no other reaction to make to this either.
> feat: remove deviceid threat check (incorrect)

- services/credential-server/src/modules/signify/signifyApi.ts
- services/credential-server/src/routes.ts
Since we introduced the one-way scanning via the `/introduce` reply message, we have now lost the `createdAt` field of contacts in our server. keripy will auto add contacts if a resolved OOBI has an alias, but not a timestamp of creation time.
For now, I just want to stick in `createdAt` if we try to fetch a contact without a date as a temporary solution. I'd rather not add `createdAt` to keripy, at least not before aligning on its need. It's quite possible that the one-way scanning approach will change going forward to a request to connect setup, in which we can set the contact right away upon acceptance.
> fix(cred-serv): insert createdAt date as now (temp solution)

- services/credential-server-ui/src/pages/ConnectionDetails/CredentialsTable.tsx
- services/credential-server-ui/src/pages/CredentialDetails/CredentialsTable.tsx
Improvement to the KEY value of the credentials attribute tooltip to use a different one.
---
> feat(ui): Improve KEY value in credentials attribute tooltip

- CODE_OF_CONDUCT.md
- README.md
- SECURITY.md
- docs/Customizing-Splash-and-Icons.md
This PR updates missing references to the Identity Wallet by replacing them with Veridian Wallet, and also replaces outdated email addresses for reporting security issues.
> chore: update project references from Identity Wallet to Veridian Wallet

- services/credential-server/src/server.ts
Fixes a startup bug in the Credential Issuance Server where it attempts to use Signify before it’s fully ready, causing initialization to fail. This update ensures the server waits for Signify to be ready before proceeding, allowing proper startup and expected behavior.
> fix(cred-server): ensure signifyReady is called before starting the server

- src/locales/en/en.json
- src/ui/components/Alert/Alert.scss
- src/ui/components/Alert/Alert.tsx
- src/ui/components/Alert/Alert.types.ts
- src/ui/components/PageHeader/PageHeader.scss
- src/ui/components/PageHeader/PageHeader.tsx
- src/ui/components/VerifyPassword/VerifyPassword.scss
- src/ui/components/VerifyPassword/VerifyPassword.test.tsx
- src/ui/components/VerifyPassword/VerifyPassword.tsx
- src/ui/pages/Menu/components/Settings/components/ManagePassword/ManagePassword.test.tsx
---
https://github.com/user-attachments/assets/58762509-9754-4c60-ba6c-536cadaaaebd
https://github.com/user-attachments/assets/37c62c96-e735-4a85-a521-35ca92fdb070
> feat(ui): Confirm/Reset buttons under signing screen

- src/ui/pages/Credentials/Credentials.scss
- src/ui/pages/Identifiers/Identifiers.scss
Fixing a few bugs in the favourites slider:
- Missing padding
- Slides misaligned when adding and removing items
---
> fix(ui): Favourite identifiers and credential cards bugs

- Earthfile
Our version of keripy on our fork did not pin lmdb (or hio) and a new version of lmdb is not compatible with our deployment; this pins to latest used image that was working in dev.
> chore: KERIA with fixed hio,lmdb deps for keripy

- src/store/reducers/stateCache/stateCache.ts
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.test.tsx
- src/ui/pages/CreateSSIAgent/CreateSSIAgent.tsx
Fix issue about missing default profile after recovery wallet.
https://github.com/user-attachments/assets/5b678a02-c8af-4452-b28f-bcfa64d025a4
[VT20-1981]: https://cardanofoundation.atlassian.net/browse/VT20-1981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat(ui): No default profile after recovery

- src/ui/components/ProfileDetailsModal/components/ProfileContent.test.tsx
- src/ui/components/ProfileDetailsModal/components/ProfileContent.tsx
**Dynamic Profile Statistics Implementation**
---------------------------------------------
In this PR we are updating the Profile Details Modal from displaying static placeholder values to showing dynamic, accurate statistics that reflect each user's actual profile data in real-time. Users now see real credential counts, connection totals, and DApp connection numbers that update automatically when data changes, providing immediate visibility into their profile's current state.
> feat(ui): Dynamic Profile Statistics Implementation

- src/ui/pages/NotificationDetails/NotificationDetails.test.tsx
The test now passes. The issue was that the test was using notificationsFix[5] (which has route "/multisig/exn" for multisig receive), but the test setup didn't have the proper mocks for multisig operations, causing the component to not render.
> test(jest): Fix failing unit test in SEDI branch

- src/core/agent/services/keriaNotificationService.test.ts
- src/core/agent/services/keriaNotificationService.ts
One-way scanning (`/introduce` rpy msg) causes contact creation if the name query param is passed. Our core skips contact creation if it already exists so we don't overwrite the creation date for repeated OOBI resolutions, but this conflicts with one-way scanning. It also conflicts with our new profile based UX, so a further fix is needed on main for the recovery flow, but this will do here for now.
> fix(core): set contact details if connecting to previously one-way scanned contact
